### ISSUE TITLE
Write research plan

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#1]
**Background**
 - Who do we need to talk to/observe?: Frontliners, permit purchasers, resources specialists (folks who reconcile permit $); commercial/non-commercial permits? 
 - Where should we visit?: Where are the fuelwood sales happening right now? 
When should we visit?: What days of the week are good for observing F2F interactions between frontliners and purchasers?
 - Can we bring recording equipment? 
 - What will need to share prototypes with potential users?
 - Also ask folks about [entry points](https://github.com/USDAForestService/fs-open-forest/wiki/Entry-research-(June-2017))

**Acceptance criteria** 
- [x] Plan answers the above Qs 
- [x] We've checked with local staff to make sure the plan is feasible

**Tasks**
- [x] Write plan
- [x] Draft LEO research protocol
- [x] Fill in section on getting IC from the public
- [x] Create IC form, if needed
- [x] Articulate note taking procedure
- [x] Create note taking template

**Definition of done**
- [x] Plan has been reviewed by the team

**Comment by MelissaBraxton** [comment]
https://docs.google.com/document/d/13vpHPx_dNXuE0BJBE7ztfjx8dcM1W6CiaLanvcGZ3-k/edit
