### ISSUE TITLE
Onboard FS product staff 

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#10]
**Background**
_What should we consider when addressing this issue?_

**Acceptance criteria** 
- [x] Forest Management has identified the person and confirmed that they'll be able to work with us (supervisor approval, MOU if needed)
- [x] FS product folks have the required background and access to tools that they need to begin working with the team

**Tasks**
Onboard Beth
- [x] Review PM/PO role descriptions
- [X] Review project documentation, path analysis report
- [x] Oriented to GitHub
- [X] Invited to Slack
- [x] Review any research reports to date
- [X] Add them to team calendar events/meetings

Onboard Kris/Roxie
- [x] Review PM/PO role descriptions
- [x] Review project documentation, path analysis report
- [x] Oriented to GitHub
- [x] Invited to Slack
- [x] Review any research reports to date
- [x] Add them to team calendar events/meetings

**Definition of done**
- [x]  Acceptance criteria met

**Comment by MelissaBraxton** [comment]
Had initial meeting with Roxie, Beth, and Kris on 10/31/19. Followed up w/ Roxie on 11/7. Kris out this week, so blocked until we meet with her next week.
