### ISSUE TITLE
Deck for internal KO

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#101]
**Background**
Notes re: agenda from 5/14/20 mtg

- Review current roadmap and re-validate focus
- COVID-19 considerations 
    - personal/team impacts
    - impacts re: firewood permitting context - touchless permitting 
- Possible speed bumps - (risks) and mitigations

- Additional KO topics: 
- An idea of someone to bring on to help (product owner)
- Do we need to talk about an off-ramp/roadmap adjustments for free-use permits? 

**Acceptance criteria** 
- [x] We have a deck that communicates the above mtg priorities

**Tasks**
- [x] Draft deck
- [x] send to Beth and team to review
- [x] Revise based on feedback

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
Draft deck is [here](**https://docs.google.com/presentation/d/1WVzqVk8K7E2sL6tAPMY7WwOtoCaeRCC1TfKgcNqwHzY/edit#slide=id.g8033584d1b_0_57**)
