### ISSUE TITLE
Create materials for vendor KO

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#103]
**Background**
This issue about preparing all that we'll need to facilitate a successful kick off with the vendor team. 

**Acceptance criteria** 
- [ ] We have a plan and supporting material that we'll need to set up and begin working together

**Tasks**
- [ ] Draft high level KO agenda
- [ ] Circulate for team to review
- [ ] Draft deck
- [ ] Circulate for team to review

**Definition of done**
- [ ]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
[Agenda doc](https://docs.google.com/document/d/1Slz_qcaYiU319C1OkUVpAL-GIfes486qCCx6vUibcrc/edit)

[Draft deck](https://docs.google.com/presentation/d/10S-zG-At-Umjgap7JNOzn5Cl_VyIvkPS1nE9fgWEKb4/edit#slide=id.g85f0765a6c_0_36)
