### ISSUE TITLE
Review vendor contract 

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#104]
**Background**
We need a copy of the current contract and any recent mods so that we can be sure we're clear on how to collaborate with the vendor. 

**Acceptance criteria** 
- [ ] Everyone on the broader team understands how we can/should work together and any contractual issues. 

**Tasks**
- [ ] Get a copy of the contract and recent mods
- [ ] Review and surface relevant insights
- [ ] Communicate any insights to the broader team

**Definition of done**
- [ ]  Meets acceptance criteria

**Comment by Miatta18F** [comment]
Action complete on 6/11/20. Can go over during next standup.
