### ISSUE TITLE
Review mocks alongside current Open Forest landing page design and note possible changes

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#105]
**Background**
The Open Forest platform has further developed a landing page since we paused work on this project. We need to review the user needs statements we have for the first part of the firewood permitting journey, alongside the new OF landing page and our mocks to note discrepancies and opportunities for refinement, focusing on whether/how the OF landing page will meet the firewood permittee's needs. 

**Acceptance criteria** 
- [ ] We've documented how the OF landing page may need to be refined in order to meet the needs of firewood permit purchasers. 

**Tasks**
- [ ] Review OF landing page
- [ ] Review 18F mocks and task flow
- [ ] Review user needs statements from firewood permitting research
- [ ] Identify and document Qs and areas for refinement

**Definition of done**
- [ ]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
[OF landing pg](https://docs.google.com/document/d/1Gy-webAQnNLP_cYRwItdmVI2ydYaL9Aacyh1u1GXLGk/edit#)

**Comment by MelissaBraxton** [comment]
This work is now reflected under #107
