### ISSUE TITLE
Document pre-KO stakeholder interviews

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#106]
**Background**
Need to document pre-KO research in a findable place

**Acceptance criteria** 
- [ ] Pre-KO research is documented and findable to everyone on the team.

**Tasks**
- [ ] Synthesize findings
- [ ] Write topline
- [ ] Post to the wiki

**Definition of done**
- [ ]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
This is now covered under
