### ISSUE TITLE
As a permit purchaser, I need a secure way to enter required permit information online so that I can get my permit quickly.

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#109]
**Background**
_What should we consider when addressing this issue?_

**Acceptance criteria** 
- [ ] 
- [ ] 

**Tasks**
- [ ] 
- [ ] 

**Definition of done**
- [ ]  
- [ ]

**Comment by MelissaBraxton** [comment]
Here is a link to the [mock](https://github.com/USDAForestService/USFS-timber-permitting/blob/master/docs/design-deliverables/online-timber-permitting-ui/2019-12--mvp-usability-test/FS%20MVP1--6.0%20Order%20permit--permit%20details.jpg)

**Comment by MelissaBraxton** [comment]
Revised to reflect design work that had been done as part of phase one, and added a link to the mock.

**Comment by Dmac26** [comment]
@csstarling - I was looking through the card here to make sure we had all of the bullet points checked off and it looks like there was a bullet calling for the user to enter vehicle information. However, it seems like that got changed somewhere along the way since the current mock for this page doesn't include a vehicle information section. Is that a change we wanted to make or should we be requiring users to enter vehicle info?

**Comment by Dmac26** [comment]
@carlsonem - As we're finishing off this card I'm wondering about the dropdown selection for the number of cords a user can choose. I'll post a screenshot below here of what it looks like.

Currently a user can only select the minimum number of cords, 4. I'm guessing we want more options than that. Look back over the content documents, some of the forests allow for a maximum of 20 per household per year, some 12, and some 10.... Some don't even mention a limit.

So do we want to just give the user the ability to choose up to 20 or do we want that option and validation to change with each forest?

![Firewood_Dropdown.png](https://images.zenhubusercontent.com/5d93a896a615ef000109902d/178a118d-f27f-4d1f-9699-60d0e654f171)

**Comment by MelissaBraxton** [comment]
Added design and code review tasks.

**Comment by MelissaBraxton** [comment]
Happened to see your note, @Dmac26  - That is a great design Q! I'd imagine @aQuib and @jstrothman will have ideas here as well.

**Comment by csstarling** [comment]
@Dmac26 @aQuib @jstrothman : If it were my forest in this pilot I wouldn't want the customer to be given the option to buy more cords than the forest allows.  _So I would think we would want the option and validation to change with each forest._

**Comment by jstrothman** [comment]
@Dmac26 @csstarling @aQuib I agree that for the number of cords, we should only allow a number within the range that the given forest allows to make the process most efficient.
Drop-down inputs are cumbersome when there are many options, such as when 20 cords is the max.

I recommend using a text input instead of a drop-down, validating that the person enters a number between the min and the max, and changing the form text so it is:

**Number of cords** *
Cost: $5 per cord
You can get between 4 - 12 cords
[Input field, class: `usa-input-tiny`]
**Total cost for firewood permit**

with an error message: 'Number of cords must be between 4 and 12'

**Comment by aQuib** [comment]
@Dmac26  @jstrothman @csstarling - Julie's recommendation on using text input instead of a drop-down field sounds good to me. Inline validation based on the forest cord min/max would also be needed.

**Comment by carlsonem** [comment]
@briandavidson can this be moved to validation?

**Comment by jstrothman** [comment]
@mtlaney Is this available for review on stage? If so, could you share a link? And if not, would you (or whomever is working on implementation) mention @mgwalker and me when it's ready for review? Much appreciated!

**Comment by briandavidson** [comment]
> @briandavidson can this be moved to validation?

Hey @carlsonem, it's up on the dev environment and we're looking to get it onto staging for validation tonight or early tomorrow.

**Comment by jstrothman** [comment]
**Design Review Notes**
I'm reviewing this at: https://open-forest-staging.app.cloud.gov/firewood/forests/flathead/buy
@Rebekah-Hernandez or @aQuib Would you add mock-ups to this issue for page 1 and 2 of the buy permit? Also can you confirm if the content on page 2 is the correct width? Thank you!

@briandavidson Is there still an intention to change the number of cords drop-down to be a text input? (based on [comments above](https://github.com/USDAForestService/USFS-timber-permitting/issues/109#issuecomment-673081981))

In the usability reviews, people liked the page a lot and found it easy to use! 

**Adjustments needed**
There are some styling inconsistencies between the forest pages and the first step of the permit:
- [ ] Name of forest is an h3 on [Forest page](https://open-forest-staging.app.cloud.gov/firewood/forests/flathead#season-dates) and an h2 on the Permit page. For accessibility purposes we shouldn't go out of order, e.g. staring with an h3 instead of an h1, though it does make sense that the h1 be the more specific title, e.g. "Firewood permit information" or "Buy a firewood permit." Let's make the forest name a `<p>` instead of a heading, and use css to style it like the h3.
- [ ] The h1 is styled differently on the two pages (700 weight on permit info page; 500 weight on buy page). Let's make these consistent

**You are purchasing section**
- [ ] Change to an h3: "2019 Personal-use Firewood permit" as it is subordinate content to the h2 "You are purchasing..."
- [ ] Make "Personal" and "Firewood" lower case and update year: "2020 personal-use firewood permit"
- [ ] Remove 'the' from "For the xxx Forest" so it reads, e.g. "For Flathead National Forest"
- [ ] Add a hyphen in "non refundable" so it reads "non-refundable"

**Comment by Rebekah-Hernandez** [comment]
@jstrothman The design mockup was a low fi version from 18F that we'd used for testing at an earlier date. At the time, we didn't make many changes from the original mockups. Here is what it looked like:
![Order_Form](https://user-images.githubusercontent.com/56045852/91760303-bb690600-eb98-11ea-9a06-6140ccd8ab1b.png)
![Rules_Guidelines](https://user-images.githubusercontent.com/56045852/91760494-1569cb80-eb99-11ea-9f48-57408cf529f3.png)

**Comment by jstrothman** [comment]
Thank you @Rebekah-Hernandez for the mocks. Could you or @aQuib review whether you'd like any changes to the width of the content on pages 1 & 2 on staging? (e.g. the brown intro block is full-width and the form fields are the same width as the page 2 rules box--perhaps fine, but not a match for the wireframes so your direction would be helpful.)

cc @csstarling (copying you on issues with design review notes)

**Comment by tram** [comment]
@Dmac26 It's not reflected in the lo-fi mock, but just wanted to call out @aQuib 's [approval](https://github.com/USDAForestService/USFS-timber-permitting/issues/109#issuecomment-673081981) to switch from a drop-down to an input field that's validated.
> Julie's recommendation on using text input instead of a drop-down field sounds good to me. Inline validation based on the forest cord min/max would also be needed.

**Comment by Dmac26** [comment]
@tram - Thank you for that info! That makes things a lot easier. I'll adjust accordingly!

**Comment by jstrothman** [comment]
@Dmac26 Could you tag me when the changes from the Design Review above, and the switch of the input for the cords are on dev? Thank you.

**Comment by jstrothman** [comment]
@aQuib @Rebekah-Hernandez There's still a question here about the width of the content: 
Could you review whether you'd like any changes to the width of the content on pages 1 & 2 on staging? (e.g. the brown intro block is full-width and the form fields are the same width as the page 2 rules box--perhaps fine, but not a match for the wireframes so your direction would be helpful.)

**Comment by aQuib** [comment]
@Dmac26 - Please expand the width of the page column to utilize full page (like other pages). See mockup:
<img width="1530" alt="fix width" src="https://user-images.githubusercontent.com/2117062/93905494-07efbf00-fcc9-11ea-8d71-ac26b105d76d.png">

**Comment by jstrothman** [comment]
@Dmac26 It looked from today's demo like this width adjustment still needs to be made.
