### ISSUE TITLE
Establish firewood team access to Open Forest environments 

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#114]
**Background**
We'll want to make sure that 18F and Forest Management folks and forest SMEs can access the staging environment. Additionally, 18F will also want access to the dev environment. 

**Acceptance criteria** 
- [ ] 18F team can access staging
- [ ] Forest Management product folks can access staging 
- [ ] Forest SMEs can access staging
- [ ] Greg (18F) can access dev environment

**Tasks**
- [ ] Mel asks Open Forest team to provide access
- [ ] Access granted 
- [ ] each individual confirms they can successfully access the needed environment(s)

**Definition of done**
- [ ]  Meets acceptance criteria

**Comment by carlsonem** [comment]
Access is likely completed, but need to confirm and ensure team knows where the appropriate URLs and such are located

**Comment by abdul-fs** [comment]
Team, here are the urls for dev and staging. It has to login via eauth credentials. If team doesn't have linc pass they still can access it by their eauth username and password. let me know if team has any issues in getting in site.
https://open-forest-dev.app.cloud.gov/christmas-trees/admin/reports
https://open-forest-staging.app.cloud.gov/christmas-trees/admin/reports

**Comment by MelissaBraxton** [comment]
Thanks, @abdul-fs  - I seem to be getting stuck in a log in loop when I try and access the Christmas tree admin reports page. Any thoughts? It just keeps logging me in and taking me back here: https://open-forest-dev.app.cloud.gov/logged-in

**Comment by abdul-fs** [comment]
@MelissaBraxton I will take look on your screen after today's meeting. @mwreiss can you please re-check if the team is in icams.

**Comment by mwreiss** [comment]
Reference https://code.fs.usda.gov/forest-service/Open-Forest-Program/issues/256

**Comment by carlsonem** [comment]
Matt will do a quick overview after stand-up tomorrow 6/10 to review the various environments.
