### ISSUE TITLE
Onboard Chris (new product owner)

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#115]
**Background**
Justin will be leaving the project at the end of June. Chris will be taking his place

**Acceptance criteria** 
- [ ] Forest Management has identified the person and confirmed that they'll be able to work with us (supervisor approval, MOU if needed)
- [ ] FS product folks have the required background and access to tools that they need to begin working with the team

**Tasks**
- [x] Schedule 1:1 w/ Mel and Chris
- [ ] Review PM/PO role descriptions
- [ ] Review project documentation, path analysis report
- [ ] Oriented to GitHub
- [ ] Invited to MS Teams
- [ ] Review any research reports to date
- [ ] Add them to team calendar events/meetings

**Definition of done**
- [ ]  Acceptance criteria met

**Comment by carlsonem** [comment]
@MelissaBraxton Was the reason this was blocked a result of not having access to GitHub? If so, Chris now has access and I'll be glad to orient on the platform.

**Comment by MelissaBraxton** [comment]
Yep, that was the only reason. If he has access, we can move this to done. We've had an initial GitHub orientation.
