### ISSUE TITLE
Onboard Michelle

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#116]
**Background**
Justin will be leaving the project at the end of June. Chris will be taking Justin's place, and Michelle will be available to support Chris and fill in for him as needed. 

**Acceptance criteria** 
- [ ] Forest Management has identified the person and confirmed that they'll be able to work with us (supervisor approval, MOU if needed)
- [ ] FS product folks have the required background and access to tools that they need to begin working with the team

**Tasks**
- [x] Schedule 1:1 w/ Mel and Michelle
- [x] Review PM/PO role descriptions
- [ ] Review project documentation, path analysis report
- [ ] Oriented to GitHub
- [ ] Invited to MS Teams and added to Open Forest General channel
- [ ] Added to Open Forest environment
- [ ] Review any research reports to date
- [ ] Add them to team calendar events/meetings

**Definition of done**
- [ ]  Acceptance criteria met

**Comment by carlsonem** [comment]
Add to teams
