### ISSUE TITLE
Onboard participating forests

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#118]
**Background**
_What should we consider when addressing this issue?_

**Acceptance criteria** 
- [x] Participating forests have a clear sense of what participation will entail and are onboard with the approach
- [x] Our team has what we need from each forest and can move forward with development

**Tasks**
- [x] Conduct background research on each pilot forest's firewood program 
- [X] Draft agenda forest onboarding mtg
- [x] Draft deck for forest onbboarding mtg
- [x] Circulate material for review
- [x] Finalize material
- [x] Complete onboarding meetings

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
On-boarding mtg scheduled for 6/15.

**Comment by MelissaBraxton** [comment]
Sheet for pilot planning/background research is [here](**https://docs.google.com/spreadsheets/d/1LdM8-_CiSSteyzNRm2gF0Hy5SaZVtyRaeRlVj_Lqezw/edit#gid=1812755299**)

**Comment by MelissaBraxton** [comment]
Draft deck is[ here.](https://docs.google.com/presentation/d/1wF925epztibZs-0vDY1Hrd394AAYfhHQWmmMFIFPbZ0/edit?usp=sharing)

**Comment by MelissaBraxton** [comment]
[Uploading Firewood permitting phase 2 - Forest onboarding .pptx…]()

Adding draft in ppt. for folks who want to review (some formatting may have shifted). Add feedback by midday Friday, 6/12, and I'll incorporate it!

**Comment by carlsonem** [comment]
Looks great, thanks for all the work on pulling this together @MelissaBraxton . A few small suggestions on the slides:

- Slide 3: Typically we don't use the word vendor, but instead "Enterprise Application Development Team" (EAD). EAD really is one team between multiple companies and the FS.
- Slide 13: Instead of the success criteria only being for "first time" firewood gatherers, I suggests the success criteria include anyone, including past gatherers, who can now get a permit online.
- Slides 18-20: Make bullets, hard to read
- Slide 45: Not to say we can't change it, but in the past we have had a goal of a "ship" every 2 weeks, not weekly

**Comment by MelissaBraxton** [comment]
Thanks for this feedback @carlsonem! 

Slide 3: Done
Slide 13: I'd like to keep this one as is. The rationale is that we want to focus on ease of learning at the start, and that the design must serve novice users and won't assume/rely on folks having prior knowledge of the process. 
Slides 18-20: Done
Slide 45: Clarified that I was referring to our weekly ship emails/reports. We have "push to prod" on there every other week.
