### ISSUE TITLE
As a permit purchaser, I need to choose the pilot Forest I'd like to visit from the landing page, so that I can quickly get to fores-specific firewood information.  

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#120]
**Background**
Since we paused the project, the open forest team has designed and mocked up a landing page that allows people to choose from different permit types and choose a location. So we'll need review their design and ours against the needs we identified in our research and refine as needed. 

We'll need to ensure that firewood is front and center so that folks understand what the site is for and whether they can get what they need. 

The ability of users to understand whether they can cut in a given area on a specific day is dependent on FS admin folks being able to keep content re: changing conditions up to date. This is related to #117. 

**Acceptance criteria** 
- [ ] User can choose from a list of forests participating in the pilot
- [ ] User can choose from available products on a particular forest
- [ ] User can understand whether an area within their chosen forest is allowed for firewood harvesting on the day they intend to get wood. 
 
**Tasks**
- [ ] Review OF landing page
- [ ] Review 18F mocks and task flow
- [ ] Review user needs statements from firewood permitting research
- [ ] Mock up refinements as needed
- [ ] Build page based on mocks
- [ ] Validation of acceptance criteria completed
- [ ] Product Owner Approved

**Definition of done**
- [ ]   e2e tests are updated for application routing changes.
- [ ]  e2e tests are functioning.
- [ ]  Child routes for existing pages are working.
- [ ] Pull requests meet technical definition of done.
- [ ] Usability tested

**Comment by MelissaBraxton** [comment]
**MVP pilot forests**

Region 1		
 - Idaho Panhandle 
 - Flathead National Forest

Region 8
 - George-Washington Jefferson
 - Chattahoochee-Oconee

Region 9
 - Hiawatha

**Release 2 pilot forests**

Region 2		
 - Shoshone
 - Grand Mesa, Uncompahgre and Gunnison (GMUG)

**Comment by carlsonem** [comment]
@aQuib Did you and Mark have a chance to discuss this issue? It would be good if we could get a design put together for this while Mark is out this week. I would imagine we could make it very similar to the Christmas tree landing page. https://open-forest-staging.app.cloud.gov/christmas-trees/forests

**Comment by MelissaBraxton** [comment]
The mocks we left off with after usability test 1 before we had to pause work back in Jan. are a great starting point and a well reasoned hypothesis: https://gsa.invisionapp.com/share/R3VA86RNPWK#/screens/397192438

**Comment by aQuib** [comment]
@carlsonem - Mark and I were not able to discuss prior to his absence this week. But the goal is the formulate a design by this week along with an accompanying research plan.

**Comment by MelissaBraxton** [comment]
I added a task for PO @csstarling to review mocks before any dev work begins to make it explicit, since he may not yet be in the flow of responding to GitHub notifications as folks add comments.

**Comment by Rebekah-Hernandez** [comment]
@csstarling @tram Here are the hi fi mockups of the timber landing page to review:

https://usfs.app.box.com/file/681029607933

**Comment by carlsonem** [comment]
@aQuib I believe you have a site map put together for firewood. If so, would you be able to upload it to this issue.

**Comment by aQuib** [comment]
@csstarling @tram Here is initial site for proposed firewood lading page
![Firewood (MVP 1)](https://user-images.githubusercontent.com/2117062/85187567-7bb7a100-b26e-11ea-9e45-1d7cefcf3997.png)

**Comment by MelissaBraxton** [comment]
Tagging @timoballard for code review as needed.

**Comment by Rebekah-Hernandez** [comment]
@briandavidson Here is the hifi mockup of the timber landing page: https://usfs.app.box.com/file/681029607933

The hero image is located here: https://usfs.app.box.com/file/626637737090

**Comment by carlsonem** [comment]
@aQuib @briandavidson do either of you happen to have an update on this issue?

**Comment by aQuib** [comment]
@carlsonem - This should be in development now based on my understanding since the design aspects are completed. I will unassign myself, add 'engineering label' and assign to @briandavidson.

@briandavidson - If I am mistaken, let me know.

**Comment by mtlaney** [comment]
@csstarling for this story we're looking to make sure the landing page looks similar to the design here [https://usfs.app.box.com/file/681029607933](https://usfs.app.box.com/file/681029607933). You may need to scroll down to the 3rd design to see the matching design.

**Comment by csstarling** [comment]
@mtlaney  are you co-owner of the box folder? If so could you give me permission to view? or know who is?

https://usfs.app.box.com/file/681029607933

**Comment by csstarling** [comment]
I noticed Hiawathia N F. is not on the drop-down list and I will approve when it is added.

**Comment by csstarling** [comment]
BTW the landing page has some text that needs cleaned up. for example the page has  [object Object],[object Object],[object Object],[object Object.

**Comment by mtlaney** [comment]
@csstarling merging Hiawathia into dev now, and looking into the Object display. Will let you know when it's ready for re-testing. Thanks for all your help!

**Comment by mtlaney** [comment]
> @csstarling merging Hiawathia into dev now, and looking into the Object display. Will let you know when it's ready for re-testing. Thanks for all your help!

Should be good now

**Comment by MelissaBraxton** [comment]
Added design and code review tasks.

**Comment by csstarling** [comment]
Hiawatha is now available.

**Comment by jstrothman** [comment]
@Rebekah-Hernandez Could I ask you to upload the hifi mockup to this issue? (I don't have Box access/USFS email address, but having mocks here also helps people looking back at related issues to see evolution.) Thank you in advance!

**Comment by Rebekah-Hernandez** [comment]
@jstrothman Here are screenshots of the mock up that I posted above. The footer is the normal Open Forest footer.
![landingpage1](https://user-images.githubusercontent.com/56045852/91082499-5cdadf80-e60e-11ea-8752-3c11d58fff32.PNG)
![landingpage2](https://user-images.githubusercontent.com/56045852/91082494-5ba9b280-e60e-11ea-8552-e4191b85cb7e.PNG)

**Comment by jstrothman** [comment]
### Design review 
@Rebekah-Hernandez @aQuib @mtlaney Looks great

**Adjustment request**
- [ ] Change "Firewood" to use a lowercase "f" in the two instances in: "Buy a Firewood permit with Open Forest
The U.S. Forest Service invites you to purchase permits to harvest Firewood in some national forests, following certain rules and guidelines."

**Comment by jstrothman** [comment]
cc @csstarling

**Comment by csstarling** [comment]
@aQuib , @Rebekah-Hernandez , @mtlaney Please consider @jstrothman above comments. these changes will be helpful and once implemented we can move this Story to Ready for Master.

**Comment by jstrothman** [comment]
@mtlaney On Dev, it looks like "Firewood" still needs to change to lowercase "f" as described above.

**Comment by mtlaney** [comment]
@jstrothman thanks I somehow missed this one, will ping you once it's back up on dev

**Comment by mtlaney** [comment]
@jstrothman should be ready for a re-review

**Comment by jstrothman** [comment]
@csstarling This looks good: ready to move forward.

**Comment by MelissaBraxton** [comment]
@abdul-fs  - Can you please take a look and check whether this meets the technical def of done?

**Comment by abdul-fs** [comment]
@Rebekah-Hernandez @Dmac26 @mwreiss Can you validate this and marked as completed?

**Comment by Rebekah-Hernandez** [comment]
Not sure if I can mark off on all of the definitions of done but it looks correct up on staging. @abdul-fs @mwreiss @Dmac26

**Comment by MelissaBraxton** [comment]
LGTM! @bboddiger - moving this to ready for main.
