### ISSUE TITLE
As a permit purchaser, I can get general information on harvesting firewood from a particular pilot forest before I decide to buy a permit, so that I can know whether a firewood permit is right for me. 

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#121]
**Background**

**Acceptance criteria** 
- [ ] User can get from landing page to forest-specific page of their choice
- [ ] User can get information about firewood permitting specific to the forest they've selected

**Tasks**
- [ ] Review OF landing page
- [ ] Review 18F mocks and task flow
- [ ] Review user needs statements from firewood permitting research
- [ ] Mock up refinements as needed
- [ ] Build page based on mocks
- [ ] Validation of acceptance criteria completed
- [ ] Product Owner Approved

**Definition of done**
- [ ]   e2e tests are updated for application routing changes.
- [ ]  e2e tests are functioning.
- [ ]  Child routes for existing pages are working.
- [ ] Pull requests meet technical definition of done.
- [ ] Usability tested

**Comment by MelissaBraxton** [comment]
Here's the mock of the forest info page: https://gsa.invisionapp.com/share/R3VA86RNPWK#/screens/397192438

**Comment by carlsonem** [comment]
@MelissaBraxton is that mock-up ready to start the development? I don't see all the boxes checked, but appears to be a design that is ready to start with.

**Comment by MelissaBraxton** [comment]
I'll defer to @aQuib re: whether he and Mark are able to check off any of the initial tasks and/or wether this is now blocked with Mark out. 

We had documented some suggested refinements based on the last round of usability testing before we paused the product: https://github.com/USDAForestService/USFS-timber-permitting/wiki/Usability-Test-1:-Online-permit-buying-flow-and-printable-load-tags but much of it is guidance around forest-specific content, once we start adding it.

**Comment by aQuib** [comment]
@MelissaBraxton, @carlsonem - that sounds like a good approach.

**Comment by MelissaBraxton** [comment]
Adding @timoballard for code review as needed.

**Comment by briandavidson** [comment]
@MelissaBraxton @carlsonem -- per the acceptance criteria:
`User can get from landing page to forest-specific page of their choice`

If I understand correctly from our conversation the other day with @aQuib, the plan is to move the forest finder to the main landing page and that will allow them to get to the specific forest they choose.

And regarding `User can get information about firewood permitting specific to the forest they've selected` -- my understanding was that the scope of this issue was just setting up the template page. We won't be able to see forest-specific information until the corresponding issues for adding each forest's data have been completed.

Do we want to put this into blocked until those two things are taken care of?

**Comment by MelissaBraxton** [comment]
Tagging in @csstarling to weigh in here as well. 

It looks like there are some tasks that have yet to be checked off here. I would leave this in in-progress, since I don't believe design is blocked. @aQuib and @Rebekah-Hernandez can maybe provide an update?

This is not ready for validation until the landing page matches the mocks that have been reviewed and approved by the PO, which I believe is the version you mentioned w/ the forest finder at the top of the current landing page. 

From my perspective, the work to set up the template page should be sufficient, as long as each pilot forest is available in the forest finder and we can get from the landing page to forest template pages. Having forest specific content in the template is covered in the forest-specific issues. 

I'd suggest revising the acceptance criteria to "User can get `to` information about firewood permitting specific to the forest they've selected"

**Comment by aQuib** [comment]
@MelissaBraxton @briandavidson  - There isn't any design aspect that is blocking this ticket and I support changing the acceptance criteria to Melissa's recommendations.

**Comment by briandavidson** [comment]
> @MelissaBraxton @briandavidson - There isn't any design aspect that is blocking this ticket and I support changing the acceptance criteria to Melissa's recommendations.

@aQuib the only mock that I'm aware of for this issue is [this one](https://gsa.invisionapp.com/share/R3VA86RNPWK#/screens/397192438) that just shows the forest info page. I think we still need one for how the forest picker will look on the landing page.

@MelissaBraxton @carlsonem -- would it be alright if we broke out the task for moving the forest picker to the landing page into it's own issue? I feel like the work required to build the forest info page, and the work required to move the forest picker to the landing page, are substantial and distinct enough to warrant each having their own issue.

**Comment by MelissaBraxton** [comment]
@briandavidson - That's a great suggestion. It's fine by me! 

(cc @csstarling)

**Comment by aQuib** [comment]
@briandavidson - [There is a hifi mockup of the land page](https://usfs.app.box.com/file/681029607933). Is this what you are asking about? [The hero image for that page is located here](https://usfs.app.box.com/file/626637737090).

**Comment by briandavidson** [comment]
> @briandavidson - [There is a hifi mockup of the land page](https://usfs.app.box.com/file/681029607933). Is this what you are asking about? [The hero image for that page is located here](https://usfs.app.box.com/file/626637737090).

Yes, thanks @aQuib

**Comment by csstarling** [comment]
Hey, can someone give me permission to view the Box documents listed in the above comments.   Thanks!

**Comment by briandavidson** [comment]
@MelissaBraxton @carlsonem since we're splitting out the task for moving the forest-picker into [it's own issue](https://github.com/USDAForestService/USFS-timber-permitting/issues/147) do we want to move this to validation, or should we have this depend on the new one?

**Comment by MelissaBraxton** [comment]
Yes, I think this can move to validation, @briandavidson. Let's move the acceptance criteria on "being able to choose a forest from the landing page" to #147.

**Comment by briandavidson** [comment]
> Yes, I think this can move to validation, @briandavidson. Let's move the acceptance criteria on "being able to choose a forest from the landing page" to #147. cc @csstarling

Great, thanks for the confirmation Melissa. I'll go ahead and flesh out #147 to capture the work involved but please feel free to make adjustments to it. cc @carlsonem

**Comment by csstarling** [comment]
The general design and content looks good. Some more refinement will be needed later.

**Comment by MelissaBraxton** [comment]
Added design and code review tasks.

**Comment by MelissaBraxton** [comment]
@mtlaney  - Can you add a link to the PR so that @mgwalker can review, please?

**Comment by jstrothman** [comment]
### Design Review notes (some notes may apply only to Flathead):

@aQuib @Rebekah-Hernandez @mtlaney Generally looks great!

**Adjustment Suggestions**
* Links in the [Open Forest Design System](https://nciinc.github.io/fs-fork-uswds-site/components/typography/#links) are underlined so that we don't rely on color alone to convey information. This ensures that people who have color-related vision deficiencies and/or are in poor lighting conditions can still distinguish the content
* In Where to Find section, "Standing dead trees may be cut unless are" -- perhaps remove "are" from this phrase, as it's awkward when reading
* Under [Cutting Instructions](https://open-forest-dev.app.cloud.gov/firewood/forests/flathead#cutting-instructions), there's a space missing in "yourfalling equipment and skills"
* The [How to Cut Your Firewood](https://open-forest-dev.app.cloud.gov/firewood/forests/flathead#cutting-instructions) section has some repeated content: "Using your firewood" is there 3 times (though the 2nd time has different text than the 1st & 3rd times; "Equipment you'll need" and "What to expect" are repeated.
* The "Contact us" section would be easier to copy-and-paste from (and take up less space) if line breaks were used between address lines instead of paragraph tags for each line.

**Wood Burning Rate Table**
The wood burning rate table could use a few adjustments for design and accessibility purposes:
* The text above the wood burning rate table doesn't explicitly state that higher BTU means higher efficiency / heat -- it would be helpful to explicitly explain this
* Add a title to the table inside a `<caption>` tag, e.g. "Wood-burning heat rates"
* Move the header row inside a `<thead>` tag so that it gets the gray background header style of the [Open Forest Design System tables](https://nciinc.github.io/fs-fork-uswds-site/components/tables/)
* In support of screen reader users, signify that the headers are for the column, i.e. `<th scope="col">`

**Comment by jstrothman** [comment]
cc @csstarling (copying you on issues where I added design review notes last week)

**Comment by csstarling** [comment]
@aQuib , @Rebekah-Hernandez , @mtlaney  Please consider @jstrothman  above comments. these changes will be helpful.

**Comment by jstrothman** [comment]
@csstarling Looks good! Ready to move forward.

**Comment by csstarling** [comment]
@aQuib  i can the usability box be checked?

**Comment by aQuib** [comment]
@csstarling - This has been usability tested (and I just checked checkbox)
