### ISSUE TITLE
As a user, I can understand whether an area within my chosen forest is allowed for firewood harvesting.

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#122]
**Background**
This story covers whether users have the info need about where to cut on a specific forest, and will likely include the addition of any cutting area maps that pilot forests provide. We may consider breaking this up into a story for each forest. We may also consider whether and how this information might be viewable from the landing page using the interactive map.

**Acceptance criteria** 
- [ ] User can determine where on a given forest they are legally allowed to get firewood. 

 
**Tasks**
- [ ] Review user needs statements from firewood permitting research
- [ ] Get firewood cutting maps from pilot forest if available
- [ ] Mock up where to cut info section on forest
- [ ] Build page based on mocks
- [ ] Validation of acceptance criteria completed
- [ ] Product Owner Approved

**Definition of done**
- [ ]   e2e tests are updated for application routing changes.
- [ ]  e2e tests are functioning.
- [ ]  Child routes for existing pages are working.
- [ ] Pull requests meet technical definition of done.
- [ ] Usability tested
