### ISSUE TITLE
As a user, I need to understand current conditions that impact the areas in which I can legally get firewood so that I can plan a safe trip to get wood legally.

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#123]
**Background**
Forest conditions that change day to day (weather, fire, etc.) impact the areas in which users can legally get firewood. The ability of users to understand whether they can cut in a given area on a specific day is dependent on FS admin folks being able to keep content re: changing conditions up to date. This is related to #117. 

**Acceptance criteria** 
- [ ] User can quickly access up-to-date information on weather restrictions for a particular forest
- [ ] User can quickly access up-to-date information on fire restrictions for a particular forest

 
**Tasks**
- [ ] Identify sources of current fire and weather information 
- [ ] Mock up way for users to get current info from forest info page
- [ ] Build page based on mocks
- [ ] Validation of acceptance criteria completed
- [ ] Product Owner Approved

**Definition of done**
- [ ]   e2e tests are updated for application routing changes.
- [ ]  e2e tests are functioning.
- [ ]  Child routes for existing pages are working.
- [ ] Pull requests meet technical definition of done.
- [ ] Usability tested
