### ISSUE TITLE
Schedule remaining recurring meetings 

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#124]
**Background**

**Acceptance criteria** 
- [ ] We have scheduled weekly and sprintly meetings at time that work for all who need to be involved. 

**Tasks**
- [ ] Mark schedules weekly design sync w/ Aquib and others as needed
- [ ] Greg schedules weekly dev sync w/ Matt, Brian, Mike, and others as needed
- [ ] Melissa schedules sprintly review mtg
- [ ] Melissa scheduled weekly speedback times

**Definition of done**
- [ ]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
Since we all have additional meetings during this period where we're getting off the ground, I scheduled this to being every other week. We can assess whether it will be productive to increase the frequency to every week in a month or so.
