### ISSUE TITLE
As a pilot forest POC, I need my Forest’s firewood permitting information available on the Staging site so that I can verify that users will be able to get the information they need to safely and legally harvest firewood on my forest. 

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#126]
**Background**
This epic covers creating initial forest information pages for each of the pilot forests

**Acceptance criteria** 
[ ] All stories under this epic are complete 

**Tasks**
- [ ] Populate forest information page template with available content for each of the pilot forests.

**Definition of done**
- [ ]   e2e tests are updated for application routing changes.
- [ ]  e2e tests are functioning.
- [ ]  Child routes for existing pages are working.
- [ ] Pull requests meet technical definition of done.
- [ ] Usability tested

**Comment by MelissaBraxton** [comment]
Forest-specific content is [here](https://usfs.box.com/s/k4x3s9zg4jk186yi4j716j5o2tnb80zf)

Pilot planning sheet [here](https://docs.google.com/spreadsheets/d/1LdM8-_CiSSteyzNRm2gF0Hy5SaZVtyRaeRlVj_Lqezw/edit?usp=sharing)

**Comment by csstarling** [comment]
@bboddiger  @mwreiss  Beth Boddiger suggested that Matt Reis double check that his team has the final list of pilot forests correct. Beth also suggested that maybe someone make a note on the planning.xlsx spreadsheet noting that the R2 forests may not be used.

**Comment by csstarling** [comment]
> Forest-specific content is [here](https://usfs.box.com/s/k4x3s9zg4jk186yi4j716j5o2tnb80zf)
> 
> Pilot planning sheet [here](https://docs.google.com/spreadsheets/d/1LdM8-_CiSSteyzNRm2gF0Hy5SaZVtyRaeRlVj_Lqezw/edit?usp=sharing) and attached: [Pilot planning.xlsx](https://github.com/USDAForestService/USFS-timber-permitting/files/4814536/Pilot.planning.xlsx)

@MelissaBraxton @bboddiger   I don't have access to Google Docs to make edits to the Pilot planning.xlsx could I get access or can someone change the following POC information?:                     

New POC for Flathead NF will be  Eric Trimble, the Swan Lake RD TMA. 


Thanks

**Comment by MelissaBraxton** [comment]
You should now have access!


Melissa Braxton
Experience Design, 18F
Cell: 425-770-2349
https://18f.gsa.gov/

**Comment by csstarling** [comment]
> > Forest-specific content is [here](https://usfs.box.com/s/k4x3s9zg4jk186yi4j716j5o2tnb80zf)
> > Pilot planning sheet [here](https://docs.google.com/spreadsheets/d/1LdM8-_CiSSteyzNRm2gF0Hy5SaZVtyRaeRlVj_Lqezw/edit?usp=sharing) and attached: [Pilot planning.xlsx](https://github.com/USDAForestService/USFS-timber-permitting/files/4814536/Pilot.planning.xlsx)
> 
> @MelissaBraxton @bboddiger I don't have access to Google Docs to make edits to the Pilot planning.xlsx could I get access or can someone change the following POC information?:
> 
> New POC for Flathead NF will be Eric Trimble, the Swan Lake RD TMA.
> 
> Thanks

@bboddiger  POC has now been added.
