### ISSUE TITLE
As the Idaho Panhandle NF POC, I need my Forest’s firewood permitting information available on the Staging site so that I can verify that users will be able to get the information they need to safely and legally harvest firewood on my forest. 

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#127]
**Background**
This issue is to take whatever content is currently available for firewood permitting and begin to populate the forest specific info page in Open Forest and identify information gaps.

**Acceptance criteria**
[ ] A forest-specific page for firewood permitting exists in Open Forest staging
[ ] Available content on forest-specific information page is viewable in staging
[ ] forest POC has can view their forest's content in staging
	
**Tasks**
[ ] Get available content online 
[ ] Get available content from Forest POC
[ ] Populate template info page with available content
[ ] Document content gaps and create new stories as needed
[ ] Ensure that forest POC has access to staging site

**Definition of done**
- [ ]   e2e tests are updated for application routing changes.
- [ ]  e2e tests are functioning.
- [ ]  Child routes for existing pages are working.
- [ ] Pull requests meet technical definition of done.

**Comment by mtlaney** [comment]
dropping here for future easy ref
[https://usfs.app.box.com/s/k4x3s9zg4jk186yi4j716j5o2tnb80zf/folder/114821518274](url)

**Comment by MelissaBraxton** [comment]
Clarified some of the tasks. If this looks good, we can apply the format to other similar tasks for the other forests.

**Comment by csstarling** [comment]
@aQuib @Rebekah-Hernandez  Hey as you schedule meetings with the pilot forests please loop me into the meetings.  Thanks!

**Comment by Rebekah-Hernandez** [comment]
Box note of the Forest Content:

https://usfs.app.box.com/notes/688416571963

**Comment by aQuib** [comment]
Here is the curated content thus far for this particular pilot forest: [https://usfs.app.box.com/notes/688416571963?s=i5hdeohe378p7p6am97fp94qemylgj8z](https://usfs.app.box.com/notes/688416571963?s=i5hdeohe378p7p6am97fp94qemylgj8z)

**Comment by aQuib** [comment]
Shared forest content via @csstarling for Pandhandle POC to review, provide missing content and validate.

**Comment by csstarling** [comment]
@aQuib POC, Juliet has reviewed the document and is looking to share the Box document with her regional folks, but is having issues sharing the Box document with others (due to permissions in box, I'm assuming).

**Comment by aQuib** [comment]
Here is the [content matrix with approved content for devs](https://usfs.app.box.com/file/691120582904) (see 'Firewood Page Content' sheet)

**Comment by mtlaney** [comment]
Done w/ one exception. 

Coeur d'Alene map is currently a 16 page pdf brochure. In order to properly display maps I have been converting them to png. I don't know how to convert a multi-page pdf document into a single png.
[Map Link](https://usfs.app.box.com/s/k4x3s9zg4jk186yi4j716j5o2tnb80zf/file/674409108259)

@aQuib @MelissaBraxton @tram any ideas?

I could potentially add a pdf viewer to the application but i'm not sure that's the best route.

**Comment by aQuib** [comment]
@mtlaney - we can convert those PDF to a PNG for you. Let me know if this is sufficient. 
[Coeur d'Alene maps.zip](https://github.com/USDAForestService/USFS-timber-permitting/files/4983459/Coeur.d.Alene.maps.zip)

**Comment by mtlaney** [comment]
@csstarling should be good to test at [https://open-forest-dev.app.cloud.gov/](https://open-forest-dev.app.cloud.gov/) than select ipnf. 

IPNF page should be similar to [https://usfs.app.box.com/notes/688416571963](https://usfs.app.box.com/notes/688416571963) for approval

**Comment by csstarling** [comment]
@mtlaney are you a co-owner of the box folder? If so could you give me permission to view? or know who is?

https://usfs.app.box.com/notes/688416571963

**Comment by mtlaney** [comment]
@aQuib @Rebekah-Hernandez @carlsonem Can one of you make sure Chris has access to this box folder, I'm unable to add new members.

**Comment by mtlaney** [comment]
@csstarling Should be ready now

**Comment by MelissaBraxton** [comment]
Added design and code review tasks.

**Comment by csstarling** [comment]
.

**Comment by jstrothman** [comment]
### Design Review
@aQuib @Rebekah-Hernandez @mtlaney Generally looks good
**Adjustment Notes**
* The side nav has "How to plan your trip" but the section doesn't exist in the content

As mentioned in #121 
* Text links should be underlined
* Contact Us addresses should use line breaks rather than full paragraph for each line in the addresses

**Comment by jstrothman** [comment]
cc @csstarling

**Comment by csstarling** [comment]
@aQuib , @Rebekah-Hernandez , @mtlaney Please consider @jstrothman above comments. these changes will be helpful and once implemented we can move this Story to Ready for Master.

**Comment by jstrothman** [comment]
@csstarling Looks good! Ready to move forward.

**Comment by csstarling** [comment]
@aQuib , @mtlaney , Forest POC commented to me that the following information should not be on forest information page:

- Firewood cutting or removal is prohibited in the Coram Experimental Forest, and on or adjacent to the following roads: 
  Westside Hungry Horse Reservoir Rd #895 from the intersection of Hwy 2 to Lid Creek Campground, Tally Lake Rd #913 
  (entire length), and Sheppard Creek Rd #113 from the junction of Rd #539 to the junction of Rd #5388.

**Comment by jstrothman** [comment]
@mtlaney Any update on this text change request? (This is in 'ready for main', and I'm getting no forest-pick-list in the landing page forest-picker on staging, and also getting 404s when I try to use a page in my browser history, e.g. https://open-forest-staging.app.cloud.gov/firewood/forests/shoshone so can't check there.
