### ISSUE TITLE
As the Flathead NF POC, I want my Forest’s firewood permitting information available on the Staging site so that I can verify that users will be able to get the information they need to safely and legally harvest firewood on my forest. 

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#128]
**Background**
This issue is to take whatever content is currently available for firewood permitting and begin to populate the forest specific info page in Open Forest and identify information gaps.

**Acceptance criteria**
[ ] A forest-specific page for firewood permitting exists in Open Forest staging
[ ] Available content on forest-specific information page is viewable in staging
[ ] forest POC has can view their forest's content in staging
	
**Tasks**
[ ] Get available content online 
[ ] Get available content from Forest POC
[ ] Populate template info page with available content
[ ] Document content gaps and create new stories as needed
[ ] Ensure that forest POC has access to staging site

**Definition of done**
- [ ]   e2e tests are updated for application routing changes.
- [ ]  e2e tests are functioning.
- [ ]  Child routes for existing pages are working.
- [ ] Pull requests meet technical definition of done.

**Comment by MelissaBraxton** [comment]
Box folder: https://usfs.app.box.com/s/k4x3s9zg4jk186yi4j716j5o2tnb80zf/folder/114821321054

**Comment by aQuib** [comment]
Curate content thus far for this particular pilot forest: [https://usfs.app.box.com/notes/688880706516](https://usfs.app.box.com/notes/688880706516)

**Comment by aQuib** [comment]
Here is the [content matrix with approved content for devs](https://usfs.app.box.com/file/691120582904) (see 'Firewood Page Content' sheet)

**Comment by mtlaney** [comment]
@csstarling This should be good to test. After you go to homeplage at [https://open-forest-dev.app.cloud.gov/](https://open-forest-dev.app.cloud.gov/) then select flathead. 

The Flathead page should look similar to [https://usfs.app.box.com/notes/688880706516](https://usfs.app.box.com/notes/688880706516) for approval

**Comment by csstarling** [comment]
@mtlaney are you a co-owner of the box folder? If so could you give me permission to view? or know who is?

 https://usfs.app.box.com/notes/688880706516

**Comment by mtlaney** [comment]
@carlsonem can you add chris to the box folder?

**Comment by mtlaney** [comment]
@csstarling should be ready to test now

**Comment by MelissaBraxton** [comment]
Added design and code review tasks.

**Comment by csstarling** [comment]
@mtlaney 

The following is redundant information that needs to be deleted:

Using your firewood
For home uses only. Firewood gathered using this permit is not for commercial resale.
Equipment you'll need during the Proclaimed Fire Season
Chainsaw operators must have a serviceable fire extinguisher (liquid 8 oz. or dry chemical 1 lb.) and shovel available at all times.
Chainsaws must be equipped with an approved spark arrester screen.
All vehicles must be equipped with a baffled muffler and serviceable tailpipe.
What to expect
Dead trees are dangerous to fall. Make sure you are experienced with yourfalling equipment and skills.
Drive safely and be alert for winter driving conditions. Your vehicle should be equipped with 4-wheel drive, snow tires, chains, and a shovel during the winter season.
Before you go check the weather forecast and always let someone know where you will be and when you are expected to return
Forest Service roads may have heavy logging traffic. Stay alert and give log truck and equipment plenty of space.
Park in areas so that traffic can get by safely and do not block gates.
Using your Firewood
Gathering of campwood is allowed without a permit as long as the wood is burned at your camp. A permit is required to transport any unused firewood home.

**Comment by jstrothman** [comment]
### Design Review

See notes in #121 https://github.com/USDAForestService/USFS-timber-permitting/issues/121

**Comment by jstrothman** [comment]
cc @csstarling

**Comment by csstarling** [comment]
@aQuib , @Rebekah-Hernandez , @mtlaney Please consider @jstrothman design review notes. these changes will be helpful and once implemented we can move this Story to Ready for Master.

**Comment by jstrothman** [comment]
@csstarling Looks good -- ready to move forward
