### ISSUE TITLE
As the George-Washington Jefferson NF POC, I want my Forest’s firewood permitting information available on the Staging site so that I can verify that users will be able to get the information they need to safely and legally harvest firewood on my forest. 

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#129]
**Background**
This issue is to take whatever content is currently available for firewood permitting and begin to populate the forest specific info page in Open Forest and identify information gaps.

**Acceptance criteria**
[ ] A forest-specific page for firewood permitting exists in Open Forest staging
[ ] Available content on forest-specific information page is viewable in staging
[ ] forest POC has can view their forest's content in staging
	
**Tasks**
[ ] Get available content online 
[ ] Get available content from Forest POC
[ ] Populate template info page with available content
[ ] Document content gaps and create new stories as needed
[ ] Ensure that forest POC has access to staging site

**Definition of done**
- [ ]   e2e tests are updated for application routing changes.
- [ ]  e2e tests are functioning.
- [ ]  Child routes for existing pages are working.
- [ ] Pull requests meet technical definition of done.

**Comment by MelissaBraxton** [comment]
Box folder: https://usfs.app.box.com/s/k4x3s9zg4jk186yi4j716j5o2tnb80zf/folder/114817620633

**Comment by Rebekah-Hernandez** [comment]
Here is the curated content for this particular pilot forest:
https://usfs.app.box.com/notes/689746453761

**Comment by aQuib** [comment]
Here is the [content matrix with approved content for devs](https://usfs.app.box.com/file/691120582904) (see 'Firewood Page Content' sheet)

**Comment by mtlaney** [comment]
@csstarling you would test this the same as IPNF / Flathead etc. Content should match similarly to [https://usfs.app.box.com/notes/688973145592](https://usfs.app.box.com/notes/688973145592)

**Comment by csstarling** [comment]
@mtlaney are you co-owner of the box folder? If so could you give me permission to view? or know who is?

https://usfs.app.box.com/notes/688973145592

**Comment by csstarling** [comment]
@mtlaney  General info looks good.

**Comment by jstrothman** [comment]
@aQuib @Rebekah-Hernandez @mtlaney Similar to a few other forests, the side nav has "How to plan your trip" but the section doesn't exist in the content

**Comment by jstrothman** [comment]
cc @csstarling

**Comment by csstarling** [comment]
@aQuib , @Rebekah-Hernandez , @mtlaney Please consider @jstrothman above comments. these changes will be helpful and once implemented we can move this Story to Ready for Master.

**Comment by jstrothman** [comment]
@csstarling Looks good--ready to move forward
