### ISSUE TITLE
Schedule field work

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#13]
**Background**
_What should we consider when addressing this issue?_

**Acceptance criteria** 
- [x] We have visits scheduled at districts where we have a high chance of seeing many customer // frontliner interactions
- [x] We have a documented itinerary w/ . a min. of 5 contacts/interviews identified

**Tasks**
- [ ] ~Connect with Regional forest leadership~
- [x] Reach out to individual front liners to schedule
- [x] Reach out to LEOs to schedule
- [x] Document itinerary and travel details

**Definition of done**
- [x]  Team approved
