### ISSUE TITLE
As the Chattahoochee-Oconee POC, I want my Forest’s firewood permitting information available on the Staging site so that I can verify that users will be able to get the information they need to safely and legally harvest firewood on my forest. 

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#130]
**Background**
This issue is to take whatever content is currently available for firewood permitting and begin to populate the forest specific info page in Open Forest and identify information gaps.

**Acceptance criteria**
- [ ] A forest-specific page for firewood permitting exists in Open Forest staging
- [ ] Available content on forest-specific information page is viewable in staging
- [ ] forest POC has can view their forest's content in staging
	
**Tasks**
- [ ] Get available content online 
- [ ] Get available content from Forest POC
- [ ] Populate template info page with available content
- [ ] Document content gaps and create new stories as needed
- [ ] Ensure that forest POC has access to staging site

**Definition of done**
- [ ]   e2e tests are updated for application routing changes.
- [ ]  e2e tests are functioning.
- [ ]  Child routes for existing pages are working.
- [ ] Pull requests meet technical definition of done.

**Comment by MelissaBraxton** [comment]
Box folder: https://usfs.app.box.com/s/k4x3s9zg4jk186yi4j716j5o2tnb80zf/folder/114817099460

**Comment by Rebekah-Hernandez** [comment]
Here is the curated content for this particular pilot forest:
https://usfs.app.box.com/notes/690664045162

**Comment by aQuib** [comment]
Here is the [content matrix with approved content for devs](https://usfs.app.box.com/file/691120582904)

**Comment by MelissaBraxton** [comment]
Added design and code review tasks.

**Comment by jstrothman** [comment]
### Design review notes

@aQuib @Rebekah-Hernandez @mtlaney Generally looks good
**Adjustment Notes**
* Under 'Where to find firewood',  'Where you can gather', 'How to gather', and 'Prohibited areas and restrictions' are repeated

As mentioned in #121

* Text links should be underlined
* Contact Us addresses should use line breaks rather than full paragraph for each line in the addresses

**Comment by jstrothman** [comment]
@csstarling Looks good! Ready to move forward.

**Comment by MelissaBraxton** [comment]
The only task that needs to be checked is confirming that forest POC has access to staging. I think this can move to "Ready for Master," @csstarling and @mmnilius.
