### ISSUE TITLE
As the Hiawatha NF POC, I want my Forest’s firewood permitting information available on the Staging site so that I can verify that users will be able to get the information they need to safely and legally harvest firewood on my forest. 

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#131]
**Background**
This issue is to take whatever content is currently available for firewood permitting and begin to populate the forest specific info page in Open Forest and identify information gaps.

**Acceptance criteria**
- [ ] A forest-specific page for firewood permitting exists in Open Forest staging
- [ ] Available content on forest-specific information page is viewable in staging
- [ ] forest POC has can view their forest's content in staging
	
**Tasks**
- [ ] Get available content online 
- [ ] Get available content from Forest POC
- [ ] Populate template info page with available content
- [ ] Document content gaps and create new stories as needed
- [ ] Ensure that forest POC has access to staging site

**Definition of done**
- [ ]   e2e tests are updated for application routing changes.
- [ ]  e2e tests are functioning.
- [ ]  Child routes for existing pages are working.
- [ ] Pull requests meet technical definition of done.

**Comment by MelissaBraxton** [comment]
Box folder: https://usfs.app.box.com/s/k4x3s9zg4jk186yi4j716j5o2tnb80zf/folder/114820806309

**Comment by Rebekah-Hernandez** [comment]
Here is the curated content thus far for this particular pilot forest:
https://usfs.app.box.com/notes/689746453761

**Comment by aQuib** [comment]
POC aiming to provide content verification by mid-week.

**Comment by csstarling** [comment]
@bboddiger  @aQuib  Aquib, I will be gone on A/L this week 7/21 to 7/27 and Beth has offered to help this Forest move information gathering along if you need help.  Looks like you're possibly getting the needed info from the POC mid week by your last commit. Feel free to let Beth know if you need help getting the info needed.

**Comment by carlsonem** [comment]
@Dmac26 has this been completed?

**Comment by mtlaney** [comment]
@csstarling should be g2test now

**Comment by MelissaBraxton** [comment]
Added design and code review tasks.

**Comment by csstarling** [comment]
The general layout looks good. Looks like a couple more maps need to be loaded for the East Side Map and the West Zone Maps.

**Comment by mgwalker** [comment]
[code reviewed](/USDAForestService/fs-open-forest-platform/#1412)

**Comment by jstrothman** [comment]
### Design Review
@aQuib @Rebekah-Hernandez @mtlaney Generally looks good
**Adjustment Notes**
* For highlighted text, what do you think about using the color from the left border of the [Open Forest Design System warning alert](https://nciinc.github.io/fs-fork-uswds-site/components/alerts/): `#FDB81E`?
* The side nav has "How to plan your trip" but the section doesn't exist in the content
* Under 'Where you can cut', East Side Map and West Zone Map text is repeated
* Under 'Equipment you'll need', "prohibited" is capitalized in one sentence but not the other: make consistent

As mentioned in #121 
* Text links should be underlined
* Contact Us addresses should use line breaks rather than full paragraph for each line in the addresses

**Comment by jstrothman** [comment]
cc @csstarling

**Comment by csstarling** [comment]
@aQuib , @Rebekah-Hernandez , @mtlaney Please consider @jstrothman above comments. these changes will be helpful and once implemented we can move this Story to Ready for Master.

**Comment by csstarling** [comment]
@aQuib , @Rebekah-Hernandez , @mtlaney Please consider @jstrothman above comments. these changes will be helpful and once implemented we can move this Story to Ready for Master.

**Comment by jstrothman** [comment]
@mtlaney It looks like there are 2 issues still on Hiawatha NF:
- [x] Under 'Where you can cut', East Side Map and West Zone Map text is repeated
- [x] Under 'Equipment you'll need', "prohibited" is capitalized in one sentence but not the other: make consistent

**Comment by mtlaney** [comment]
@jstrothman hiawatha is building right now on dev so those changes aren't up yet, i'll ping you when done

**Comment by mtlaney** [comment]
@jstrothman should be ready to review

**Comment by jstrothman** [comment]
@csstarling Looks good: ready to move forward.
