### ISSUE TITLE
Conduct annual gap analysis 

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#132]
**Background**
As part of ensuring that product practices remain sustainable long term, we want to conduct a gap analysis so that the team can prioritize opportunities for improvement over the next few months. We'll begin by following the annual gap analysis process documented [here](https://github.com/USDAForestService/fs-open-forest/wiki/Annual-gap-analysis-process), but we'll also want to assess how well this process is working and refine it as needed. 

**Acceptance criteria** 
- [ ] We have team consensus on prioritized success scenarios 
- [ ] We have team consensus on tasks needed to facilitate success scenarios
- [ ] Tasks needed to facilitate success scenarios are documented as issues on the board and labeled "sustainability"

**Tasks**
- [ ] Draft initial success scenarios
- [ ] Develop facilitation script and any supporting material (e.g., Mural board)
- [ ] Schedule facilitated discussion for the team to review and score scenarios
- [ ] Facilitate team review
- [ ] Draft initial tasks required to achieve priority success scenarios
- [ ] Team reviews tasks
- [ ] Document tasks as new issues on the board

**Definition of done**
- [ ]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
Hi folks: draft success scenarios are [here](https://usfs.box.com/s/9j3kv9fdsd2uq114ftma8m5nw1hxxxs9)

Please comment, edit, add as you see fit. Aiming to have everyone take a look in the next week so that we can move on to drafting success criteria and tasks. 

cc @carlsonem, @aQuib, @mtlaney, @csstarling, @mwreiss, and @bboddiger to represent the various team functions :)

**Comment by carlsonem** [comment]
@MelissaBraxton are the success stories in a proposed priority? i.e. 1 is the most important?

**Comment by MelissaBraxton** [comment]
Great question! They are not sorted in any priority order yet. As you're
going through though, if some stand out as being high or low priority, feel
free to add a note to that effect!


Melissa Braxton
Experience Design, 18F
Cell: 425-770-2349
https://18f.gsa.gov/

**Comment by MelissaBraxton** [comment]
Th activity wont be scheduled until the next sprint so I revised this issue a bit. New card for running the activity and finalizing the transition plan is #150

**Comment by MelissaBraxton** [comment]
Draft facilitation Mural is [here.](https://app.mural.co/invitation/mural/gsa6/1594918162328?sender=melissabraxton2796&key=bf55028a-5023-470e-a6a4-2ae3180333eb)
