### ISSUE TITLE
Onboard 18F content strategist (Anne Petersen)

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#133]
**Background**
We are bringing on a part time content strategist to help develop messaging for the online firewood permitting program and draft a communication and engagement plan. Anne (18F) will collaborate with Anna Fargo at USFS. 

**Acceptance criteria** 
- [x] Anne is oriented to the project
- [x] Anne is clear on their role and the scope of their work over the next few weeks

**Tasks**
- [x] Schedule 1:1 w/ Mel and Anne
- [x] Anne review project documentation
- [x] Anne added to GitHub team
- [x] Anne added to #FS-Timber channel in Slack
- [x] Intro meet with Anne and Anna is scheduled
- [x] Create new issues describing Anne's work as needed

**Definition of done**
- [ ]  Acceptance criteria met

**Comment by carlsonem** [comment]
@MelissaBraxton does Anne have a FS email? If so, I will add her to the various tools.

**Comment by MelissaBraxton** [comment]
I don't believe Anne has an FS email. As Anne will be pretty part time with a specific focus, I'm not sure they'll need access to anything beyond the firewood permitting repo.

**Comment by annepetersen** [comment]
Fully onboarded! New issues incoming for next steps.
