### ISSUE TITLE
 As a special forest products manager, I need to ensure that funds from online sales can be collected and distributed to the right place, so that I can make sure my forest does not lose revenue

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#134]
### **Background**
This story covers how we'll integrate with various financial systems 

### **Acceptance criteria** 
- [ ] We have established how we will accept electronic payments online through pay.gov
- [ ] We have validated a path for funds from online payments to be routed correctly

### **Tasks**
- [ ] Complete research spike into administrators information needs (#145) 

**Data flow from Firewood (open forest platform) to FPFS.**  
- [ ] Need to understand the types of data for interfacing, frequency on data look up or usage, one way or bi-directional, and if existing web service exist in FPFS or need to be built?
- [ ] Need to identify if a CFO gateway service needs to be in place for Open forest  to consume FPFS service.

**Data flow from Firewood (Open Forest) to Pay.gov.**  
 - [ ] Coordinate via POSS to identify firewood related transaction setup in pay.gov and leveraging the same interface that exists for Open Forest.
- [ ] Validate if additional updates are needed on the ISA with Treasury (Pay.gov).

**Data flow from Pay.gov to POSS.** 
- [ ] Need to coordinate with POSS that they will be receiving firewood transactional data from pay.gov to POSS.

**Data flow from POSS to FMMI.** 
- [ ] Need to coordinate with POSS that firewood related transactional data will be posted in appropriated posting in FMMI. 
- [ ] Validate that no additional actions or coordination required from Open Forest on firewood transactions for FMMI.

- [ ] Validation of acceptance criteria completed
- [ ] PO approved

**Definition of done**
- [ ]  Pull requests meet technical definition of done
- [ ]  Compare finished design with mockup
- [ ]  Usability tested

**Comment by MelissaBraxton** [comment]
@bboddiger, @smahmudFS, and @mwreiss   - This issue ties actions that we've talked about in our tech integration meetings to admin user needs we're aiming to meet in the MVP. Take a look and let me know what I missed!

**Comment by MelissaBraxton** [comment]
@mwreiss and @smahmudFS - I think this issue is redundant with #264 and #265 on the program board. Take a look and let me know.

**Comment by carlsonem** [comment]
Split into separate issues
