### ISSUE TITLE
As a special forest products manager, I need to know how I can get information on species, product, unit of measure, and volume sold online so that I'm sure I'll have the information I need for complete official upward reporting 

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#135]
## **Background**
This story covers understanding how we'll integrate various systems to meet forest service admin and special forest product manager reporting needs. This story does not cover the design and development of a reporting UI. We're intending that basic ability to query data re: online permit sales be included in the MVP and a reporting interface is currently slated for the next major release. Related to #86 and #83. 

## **Acceptance criteria** 
- [ ]  We have the integrations necessary to enable forest admins to easily retrieve the information they need re: online permit sales
- [ ] We understand the design constraints for how admins will get reporting information as part of the MVP release and have documented design and development work needed to meet admins need for this info in new issues as needed.  

## **Tasks**
- [ ] Complete research spike into admin needs is completed #145 

**Data flow from FPFS to TIM (NRM).** 
- [x] Need to ensure that FPFS includes Firewood data to TIM. 
- [x] Validate that no additional interface required from Open Forest to NRM for TIM.
- [x] Need validation from TIM that they will include FPFS data via TIM reporting for end users, and data feed to CDW/EDW will include Firewood data. 
- [x] Validate that no additional interface required from Open Forest to CDW/EDW.
- [x] Set up FPFS API (or revive it w/ help from Nick and Percy)
- [ ] Write test plan
- [ ] Test connectivity/validate permit data push

**Definition of done**
- [ ] Meets acceptance criteria 
- [ ] Product Manager approved

**Comment by MelissaBraxton** [comment]
@bboddiger, @smahmudFS, and @mwreiss   - This issue ties actions that we've talked about in our tech integration meetings to admin user needs we're aiming to meet in the MVP. Take a look and let me know what I missed!

**Comment by MelissaBraxton** [comment]
@smahmudFS and @mwreiss -See the 2 remaining tasks here.  We also have "test connectivity" as a task under [#264 ](https://code.fs.usda.gov/forest-service/Open-Forest-Program/issues/264) on the program board, but I'm not sure whether the 2 tasks are equivalent. Is the task on 264 testing the path of permit data end to end, or is it a smaller scope?

**Comment by mwreiss** [comment]
@MelissaBraxton "test connectivity" on #264 on the program board is to test the handshake for certs passing at the infrastructure level/back-end between Open Forest and FPFS.  From that perspective we will not be testing a data push, that should be addressed on the platform side.

**Comment by carlsonem** [comment]
@mtlaney @briandavidson @mgwalker please refine this issue

**Comment by MelissaBraxton** [comment]
@mtlaney, @briandavidson, and @mgwalker - We'd created issue [#1161 ](https://github.com/USDAForestService/fs-open-forest-platform/issues/1161) back in January to cover this work. We may be able to replace #135 with the old 1161 in the backlog, and then archive #135.

**Comment by MelissaBraxton** [comment]
We now have #151 that covers the final steps on this from a front end perspective. The other work is accounted for on the program board, so we can archive this.
