### ISSUE TITLE
As a permit purchaser on the Idaho Panhandle national forest, I need to understand to firewood harvesting rules so that I can get a valid permit and get wood safely and legally.

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#138]
**Background**
This story is to ensure that the Idaho Panhandle NF page has accurate, complete, understandable information that provides permit purchasers what they need to safely, legally, head out to this specific forest and harvest firewood. 

**Acceptance criteria** 
- [ ] Permit purchaser can understand general rules specific to this forest
- [ ] Permit purchaser can understand safety tips
- [ ]Permit purchaser can understand how current conditions may impact harvesting
- [ ] Permit purchaser can understand where they can/can't get wood on this forest
- [ ] Permit purchaser can understand what wood is allowed/prohibited for harvesting
- [ ] Permit purchaser can understand where to go for more information

**Tasks**
- [ ] 
- [ ] 

**Definition of done**
- [ ]  
- [ ]

**Comment by MelissaBraxton** [comment]
Typically FS permits are good from the time they're purchased for one year. Although some forests/districts put in the conditions of the permit that there is no cutting after a particular date.

**Comment by carlsonem** [comment]
@aQuib make it focused on testing, not gathering the information as this is already done on the individual forest pages
