### ISSUE TITLE
Define comms process / approvals / best practices at each relevant level

### ISSUE THREAD

**Issue by annepetersen** [USDAForestService/USFS-timber-permitting#142]
**Background**
Goal: The Forest Management provides timely, targeted communication about the new firewood permitting program that keeps stakeholders informed, engaged, and aligned with the program’s direction. 
Complicating factor: Internal change management, historical, and organizational considerations are at play here.

**Acceptance criteria** 
- [ ] We have team consensus and support of a comms plan and messaging framework
- [ ]  Tasks needed to facilitate rollout are documented as issues on the board and labeled "Firewood program"

**Tasks**
- [ ]  Find out who is leading comms on Forest Products modernization and learn about any possible approval blockers 
- [ ] Review prior Open Forest comms and identify advocates 
- [ ] Schedule sessions with Firewood permitting product folks: e.g., communication and engagement planning, co-designing a messaging framework
- [ ] Plan sessions with Firewood permitting product folks: e.g., communication and engagement planning, co-designing a messaging framework
- [ ] Determine best path forward for establishment of the comms plan and messaging framework
- [ ] Document the comms plan and messaging framework
- [ ] Socialize the comms plan and messaging framework

**Definition of done**
- [ ]  Meets acceptance criteria

**Comment by annepetersen** [comment]
Note: this is probably too large an issue, but it'll help me as a placeholder for now.

**Comment by annepetersen** [comment]
Looked at the examples of tone from Open Forest: a range from formal to approachable.

**Idea**: prototype out the comms for one item. 

For example: what to expect with the pilot. 
Audiences: public who have access, public who are interested but don't have access, staff at forests that will be participating (managing expectations with TIM coordinators especially; regional foresters/TIM coordinators and points of contact), staff at forests who aren't 
What: When and how they get access. For example: no later than Nov 1 for initial pilot forests.
Re-emphasize: Initial pilot forests: simplest permit process. Second wave: more complex

**Comment by MelissaBraxton** [comment]
FYI, @annepetersen 

- Deck from [regional TIM coordinator intro](https://docs.google.com/presentation/d/1_yJRr4syNay3EYFStgYvx8whdF56jZR50LY2SHTjzLs/edit#slide=id.g46c8ba97d9_0_283) to E&I
- Firewood permitting, [phase 2 KO w/ exec sponsors](https://docs.google.com/presentation/d/1WVzqVk8K7E2sL6tAPMY7WwOtoCaeRCC1TfKgcNqwHzY/edit)
- Remote [vendor KO deck](https://docs.google.com/presentation/d/10S-zG-At-Umjgap7JNOzn5Cl_VyIvkPS1nE9fgWEKb4/edit#slide=id.g46c8ba97d9_0_283)
- [Pilot forest onboarding deck](https://docs.google.com/presentation/d/1wF925epztibZs-0vDY1Hrd394AAYfhHQWmmMFIFPbZ0/edit)

**Comment by MelissaBraxton** [comment]
Folks to include in trainings are Beth Boddiger and Chris Starling; @bboddiger and @csstarling

**Comment by annepetersen** [comment]
(note for self) Schedule the Stakeholder Engagement training with Beth.

**Comment by MelissaBraxton** [comment]
Training is scheduled for Wed. 8/12.

**Comment by MelissaBraxton** [comment]
@annepetersen  - Can you provide an update on this?

**Comment by MelissaBraxton** [comment]
@annepetersen - It looks like there are a few tasks remaining--should be a light lift. Can you close this out this week?

**Comment by MelissaBraxton** [comment]
@annepetersen - any update here?

**Comment by annepetersen** [comment]
I think we're blocked on "Find out who is leading comms on Forest Products modernization and learn about any possible approval blockers." We don't have a way to anticipate the right framing around pandemic impacts given that we don't know OC's current opinion on the topic.

As an update on the then-last remaining item, both comms plan and engagement plan have some changes that I need to get back to (or we should decide if it's time to change ownership on).

**Comment by annepetersen** [comment]
Delivered our final versions of both comms plan and stakeholder engagement plan today. (Not _final_ final, but the last we'll be involved with in the current effort.)
