### ISSUE TITLE
Update product roadmap using ZenHub roadmapping feature

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#144]
**Background**
We want to transfer the product roadmap that is currently in Mural in to Zenhub so that the team is better able to view the roadmap and the focus of the MVP scope and later releases. 

**Acceptance criteria** 
- [ ] The team can easily view the roadmap in Zenhub
- [ ] The roadmap in Zenhub accurately reflects the scope of the MVP

**Tasks**
- [ ] Align roadmap in Mural with epics in Zenhub
- [ ] Write shorthand titles for each epic to make it scanable (i.e., reporting epic, data entry form epic, etc.)
- [ ] Set timeline for each epic

**Definition of done**
- [ ] Meets acceptance criteria
- [ ] PM approved
- [ ] PO approved

**Comment by MelissaBraxton** [comment]
Beth and I postponed work on this until next week while her computer is re-imaged.

**Comment by MelissaBraxton** [comment]
@carlsonem - Let me know when you've reviewed the proposed timeline and if you have any proposed adjustments.

@bboddiger and @csstarling (cc @mmnilius)  - Take a look at the roadmap and check the PM/PO approved boxes when you're ready. Chris/Michelle: we can also look at this together at our weekly on 7/14.

**Comment by carlsonem** [comment]
@MelissaBraxton just finished reviewing the timelines and such. What you put together seems reasonable. When we present it to the rest of the team, I'll emphasize that this is to complete the entire EPIC, not simply design or development. :)

**Comment by MelissaBraxton** [comment]
Following up on what we chatted about in backlog grooming, if folks could take a look at the roadmap [here](https://github.com/USDAForestService/USFS-timber-permitting#workspaces/open-forest-58f8bbe105a35fad2d275a0c/roadmap?repos=88538878,88881186,214296595) please take a look by Friday, 7/17. Drop any comments or Qs in this issue. 

@aQuib, @mwreiss, @mtlaney, @briandavidson

**Comment by MelissaBraxton** [comment]
We're revisiting the decision on when and how to prioritize CDW/EDW integrations which may lead to some modifications. Moving this to blocked for now.

**Comment by MelissaBraxton** [comment]
@bboddiger Can we move this to done? Based on today's review, the roadmap in Zenhub aligns with what we're thinking. We'll still want to update the documentation in the wiki, but that can be done as part of a regular weekly sync roadmapping update.

**Comment by bboddiger** [comment]
I think so—yes.  Thank you!
