### ISSUE TITLE
As a firewood admin, I need to generate reports of firewood permitting from TIM data, so that I can get provide statistical information to relevant stakeholders. 

### ISSUE THREAD

**Issue by aQuib** [USDAForestService/USFS-timber-permitting#145]
**Background**
This story is about researching the user needs regarding report generation with TIM data. We want to understand who needs access to the data and for what user, what are the permit data necessities for downstream reporting, what data types for firewood permitting will be moved to FPFS,  what are the frequency and schedules of reports, and which admin users require access to data (and whether data calls will be one way or bi-directional). 

**Acceptance criteria** 
- [ ] We have documented relevant insights of TIM users reporting needs
- [ ] Documentation is findable in the wiki

**Tasks**
- [ ] Review service blueprint (TIM interactions) 
- [ ] Review proposed architecture diagram
- [ ] Review sample report from TIM
- [ ] Draft high-level research plan
- [ ] Identify 3-5 users and stakeholder to interview
- [ ] Write up interview Qs
- [ ] Interview TIM admin users/SME
- [ ] Write up topline 
- [ ] Circulate for team to review
- [ ] Post to wiki

**Definition of done**
- [ ] Acceptance criteria met

**Comment by csstarling** [comment]
Looks good, we might want to consult an auditor of Frontliner. Frontliners will need to meet auditor requirements with reporting features.

**Comment by MelissaBraxton** [comment]
In chatting with Michelle and Chris, frontliners are only audited on tags and dollars that are tied to in-office sales, so needing to meet frontliner's auditing requirements is not a concern for online sales.

**Comment by csstarling** [comment]
For MVP we are not designing a frontliner reporting interface.

**Comment by tram** [comment]
Changing the title in response to Chris’s comment.

Pulled notes from prior research that fulfills “Schedule interviews with 3-5 report generators and consumers” task. Will validate visualizations with SMEs.

Visualization to replace topline. Added as-is information flow to tasks.

**Comment by MelissaBraxton** [comment]
**Relevant assumptions:** 

- No permittee data will be stored as part of the MVP--it will be exported in csv format that USFS staff with a need to know at pilot forests can access
- We are aiming to ask for information that frontliners need up-front via #109, but that info will not be stored in Open Forest until we have a SORN. 
- To avoid potential security and privacy issues, we're aiming to have as minimal permittee info  as possible be emailed and printed on the permit (#140) . Current understanding is that the min. info could be name (+transaction data, like permit ID and date of purchase), but we've heard of a desire for name+address, and possibly permittee ID # as well. While ultimately what get's printed on the permit depends on LEO needs and what the USFS privacy and security folks approve, our GSA privacy officer has advised that emailing a permit that contains as much as name + address + unique identifier could be allowed, provided that we are transparent to permittees re: how their info will be used. 

@bboddiger - it would be good to reach out to Deb White to get her take on what permittee info would be allowable to email to permittees, in advance of us diving into the permit design (#140) 

cc @aQuib , @tram , and @Rebekah-Hernandez

**Comment by aQuib** [comment]
[Here is data flow digram](https://whimsical.com/Em3ENhBhJS8Eui8EaxvooA)
![To-be Process (MVP Permit Reporting)](https://user-images.githubusercontent.com/2117062/90679599-6212e580-e22e-11ea-9662-0b352520f102.png)

**Comment by tram** [comment]
Added permittee data for export.
![To-be Process (MVP Permit Reporting)](https://user-images.githubusercontent.com/43267/90906594-c34dcc80-e386-11ea-8426-2142b2b215f6.png)

**Comment by carlsonem** [comment]
@aQuib @tram Is this now complete?

**Comment by aQuib** [comment]
Yes
