### ISSUE TITLE
Create re-usable forest data-table

### ISSUE THREAD

**Issue by mtlaney** [USDAForestService/USFS-timber-permitting#146]
**Background**
Currently Open forest has a christmasTreesForests table which houses our forests. This table includes multiple columns and data points not used by fuelwood. To keep our code clean and performant, we are creating a new forests datatable that can house forest information and permit types.

**Acceptance criteria** 
- [ ] Forests table is created dynamically thru migrations and seeders
- [ ] Forests api endpoint is created and accessable within the application for CRUD functionality. 

**Tasks**
- [ ] Create forests seeder and associated migrations
- [ ] Create forests model / controller / route within the backend
- [ ] Tests availability of API on local / dev
- [ ] Remove un-needed chrismasTreeForests table
- [ ] Clean up migration files

**Definition of done**
- [ ]  New forests table is created and usable
- [ ] New forests table is fully tested by a user who is not the author of the code.

**Comment by mtlaney** [comment]
@csstarling to test this story, we want to make sure that when we hit the homepage at [https://open-forest-dev.app.cloud.gov/](https://open-forest-dev.app.cloud.gov/) and see a list of forests from the dropdown. If we can see the list of dropdowns we should be good on this story.

**Comment by csstarling** [comment]
The pilot forest dropdown works and has the most of the pilot forests available except for the Hiawatha NF .  

Hiawatha is now available on the dropdown tab

**Comment by MelissaBraxton** [comment]
Added code review task.

**Comment by csstarling** [comment]
General content looks good, map zoom will eventually need to be worked on. @mtlaney
