### ISSUE TITLE
As the GMUG NF POC, I want my Forest’s firewood permitting information available on the Staging site so that I can verify that users will be able to get the information they need to safely and legally harvest firewood on my forest. 

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#148]
**Background**
This issue is to take whatever content is currently available for firewood permitting and begin to populate the forest specific info page in Open Forest and identify information gaps.

**Acceptance criteria**
- [ ]  A forest-specific page for firewood permitting exists in Open Forest staging
- [ ]  Available content on forest-specific information page is viewable in staging
- [ ]  forest POC has can view their forest's content in staging

**Tasks**

- [ ]  Get available content online
- [ ]  Get available content from Forest POC
- [ ]  Format forest content (low-fi, in a Box note)
- [ ]  Share formatted forest content w/ POC for review
- [ ]  Populate content matrix with approved content for devs
- [ ]  Add forest to the seeder file
- [ ]  Devs populate template info page with content from matrix
- [ ]  Document content gaps and create new stories as needed
- [ ]  Ensure that forest POC has access to staging site

**Definition of done**
- [ ] e2e tests are updated for application routing changes.
- [ ]  e2e tests are functioning.
- [ ]  Child routes for existing pages are working.
- [ ]  Pull requests meet technical definition of done.

**Comment by aQuib** [comment]
Still awaiting response from POCs (of which one is on vacation til next week)

**Comment by aQuib** [comment]
We have received feedback on the content from POC, but need clarification on a few remaining issues.

**Comment by carlsonem** [comment]
@Rebekah-Hernandez  any update on this one?

**Comment by Rebekah-Hernandez** [comment]
My apologies, @carlsonem . I had completed the information last week but forgot to assign it to Dylan. He's aware of it now. Here is the content curated for GMUG: https://usfs.app.box.com/notes/693423559218

**Comment by carlsonem** [comment]
@Dmac26 where does this one stand?

**Comment by MelissaBraxton** [comment]
Added design and code review tasks.

**Comment by mgwalker** [comment]
[code reviewed](fs-open-forest-platform/pull/1415)

**Comment by jstrothman** [comment]
@aQuib @Rebekah-Hernandez @mtlaney Similar to a few other forests, the side nav has "How to plan your trip" but the section doesn't exist in the content

**Comment by jstrothman** [comment]
@csstarling The side nav link to "How to plan your trip" has been removed, so this can move forward. 
@mtlaney Is there any additional peer validation you need?

**Comment by mtlaney** [comment]
looks g2g

**Comment by MelissaBraxton** [comment]
Nvm, @abdul-fs!
