### ISSUE TITLE
As the Shoshone NF POC, I want my Forest’s firewood permitting information available on the Staging site so that I can verify that users will be able to get the information they need to safely and legally harvest firewood on my forest.

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#149]
**Background**
This issue is to take whatever content is currently available for firewood permitting and begin to populate the forest specific info page in Open Forest and identify information gaps.

**Acceptance criteria**
- [ ]  A forest-specific page for firewood permitting exists in Open Forest staging
- [ ]  Available content on forest-specific information page is viewable in staging
- [ ]  forest POC has can view their forest's content in staging

**Tasks**

- [ ]  Get available content online
- [ ]  Get available content from Forest POC
- [ ]  Format forest content (low-fi, in a Box note)
- [ ]  Share formatted forest content w/ POC for review
- [ ]  Populate content matrix with approved content for devs
- [ ]  Add forest to the seeder file
- [ ]  Devs populate template info page with content from matrix
- [ ]  Document content gaps and create new stories as needed
- [ ]  Ensure that forest POC has access to staging site

**Definition of done**
- [ ] e2e tests are updated for application routing changes.
- [ ]  e2e tests are functioning.
- [ ]  Child routes for existing pages are working.
- [ ]  Pull requests meet technical definition of done.

**Comment by Rebekah-Hernandez** [comment]
Curated content approved by Shoshone POC can be found here:
https://usfs.app.box.com/notes/691885902953?s=9qi2xkybnbbeydphu65m6qm9gzprzuqy

**Comment by carlsonem** [comment]
@Dmac26 where does this forest stand?

**Comment by Dmac26** [comment]
@carlsonem - It's g2g. Just awaiting approval of the PR.

**Comment by MelissaBraxton** [comment]
Added design and code review tasks.

**Comment by jstrothman** [comment]
### Design review notes
@aQuib @Rebekah-Hernandez @mtlaney  
A couple of adjustments are needed:
* Under 'What kind of wood you can collect', "Only dead trees, either down or standing may be cut. A dead tree is one with no green needles. Disease or beetle-killed trees must be all brown or red-needled to be considered dead." is repeated.
* Similar to a few other forests, the side nav has "How to plan your trip" but the section doesn't exist in the content
* Contact Us addresses should use line breaks between address lines

**Comment by jstrothman** [comment]
@csstarling Looks good! Ready to move forward.

**Comment by MelissaBraxton** [comment]
Looks like the acceptance criteria still need to be checked, @csstarling and @mmnilius?

**Comment by csstarling** [comment]
@aQuib, @mtlaney, Forest POC found an error. They responded to me in e-mail "This looks ok to me though they have our address wrong.  It’s : Washakie Ranger District, 333 E. Main Street, Lander WY  82520"

**Comment by jstrothman** [comment]
@Dmac26 This one is in 'Ready for master' but has a text change that still needs to be made, per @csstarling [feedback from Shoshone NF POC](https://github.com/USDAForestService/USFS-timber-permitting/issues/149#issuecomment-694541859). 

Would you prefer moving this back to 'Ready' or 'In progress' (or make a new issue)?

**Comment by Dmac26** [comment]
@jstrothman - I apologize about missing this comment. I'll make another card here today to circle back and take care of it.
