### ISSUE TITLE
Identify and prioritize technical issues to investigate

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#15]
**Background**
To help make sure Kelsey can hit the ground running when she rejoins the project in Nov. we want to begin to list some of the things she will want to investigate and initiate any bureaucratic process that might be necessary in order for her to get access to any systems.

**Acceptance criteria** 
- [x] We have a prioritized list of areas for deeper technical investigation
- [x] We've identified what might be needed to access info and/or systems to aid in that investigation

**Tasks**
- [x] List technical issues to investigate
- [x] Kelsey and Melissa meet to discuss
- [x] Kelsey prioritizes issues
- [x] Melissa looks into and adds notes on what might be needed

**Definition of done**
- [x]  PM and tech lead approved

**Comment by MelissaBraxton** [comment]
Created list [here.](https://docs.google.com/spreadsheets/d/13qqtNNTCvfBHyRrnvIFimkOdxka7i52wPYyFuCNDReI/edit#gid=0)
