### ISSUE TITLE
Run transition planning activity

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#150]
**Background**
This is a continuation of #132.

**Acceptance criteria** 
- [ ]  We have team consensus on prioritized success scenarios
- [ ]  We have team consensus on tasks needed to facilitate success scenarios
- [ ]  Tasks needed to facilitate success scenarios are documented as issues on the board and labeled "sustainability"

**Tasks**
- [ ] Run facilitated activity to prioritize scenarios and brainstorm success criteria and tasks
- [ ] Document tasks as new issues on the board

**Definition of done**

- [ ]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
@mgwalker and @tram - I tagged the two of you to write initial draft success criteria and tasks to help spark the larger group brainstorm scheduled for Wed.

**Comment by MelissaBraxton** [comment]
Draft transition plan was shared with USFS folks for feedback on Friday, 8/7. Moving this to blocked as I want to give folks a few days to provide feedback efore I move forward with creating new "transition" tasks. @bboddiger and @csstarling  - If you could provide feedback by Wed. 8/12, that will give me time to create any new issues by the end of the week. 

DRAFT plan is [here](https://docs.google.com/document/d/1K2eHmXZM1BhIPF48yMn6e-oDuJ2gcOs2v9eRmLHzryo/edit?usp=sharing)

**Comment by MelissaBraxton** [comment]
Blocked because I don't currently have Box access while I wait for my credential to be reinstated.

**Comment by MelissaBraxton** [comment]
Plan is [here](https://usfs.app.box.com/notes/710549658679) in Box.

**Comment by csstarling** [comment]
> Plan is [here](https://usfs.app.box.com/notes/710549658679) in Box.

@carlsonem  Could you please give me Box access?
