### ISSUE TITLE
As a special forest products manager, I need to get information on species, product, unit of measure, and volume sold online so that I'm sure I'll have the information I need for complete official upward reporting #135

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#151]
**Background**
This follows up on issue #135 to actually build out and test how special forest products managers will get data on species, product, unit of measure and volume from a front end perspective. We think this need will be via our integrations with FPFS and TIM, but we want to check and make sure. **If not, we'll need to design and develop a means for special forest products managers to get this information.**   We could

**Acceptance criteria** 
Special forest products managers I can can:

- [ ] get data on species, product, unit of measure and volume
- [ ] have funds from online sales distributed to the right place
- [ ] get information on species, product, unit of measure, and volume sold online for official upward reporting
- [ ] retrieve the number of permits that were issued online

**Tasks**
- [ ] Review data flow model to understand where and how in the process resource managers can get the info they need for firewood permits
- [ ] Validate that resource managers will be able to view data on species, product, unit of measure, and volume for online sales using FPFS and TIM and that no additional interface or report is needed
- [x]  Verify API accessibility between Open Forest and FPFS
- [x]  Write test plan
 - [x] Test connectivity/validate permit data push and exercise the API to send permit data through (could be manual in a terminal)
- [ ]  Validate that data required by FPFS is all accounted for

**Definition of done**
- [ ]  PO approved
- [ ]  Pull requests meet technical definition of done
- [ ]  Compare finished design with mockup

**Comment by MelissaBraxton** [comment]
@csstarling - You may have additional acceptance criteria to add. We can discuss at our regular mtg tomorrow.

**Comment by carlsonem** [comment]
Split into other issues

**Comment by MelissaBraxton** [comment]
Heads up @carlsonem - In chatting with @bboddiger, we think we may have archived this prematurely. We are reviving this story to make sure we have a way to meet resource managers reporting needs. The mapping issues cover back end data flow, but not the front end process for USFS staff accessing it.  @bboddiger and @csstarling  will prioritize this one.

**Comment by carlsonem** [comment]
This task is focused on user testing to confirm that the end users are able to find data/transactions as noted above. Will want to conduct user testing. Need to refine tasks to add items such as recruiting testers and such.
