### ISSUE TITLE
 As a permit purchaser, I need to agree to abide by the permit rules so that I can get an enforceable permit. 

### ISSUE THREAD

**Issue by bboddiger** [USDAForestService/USFS-timber-permitting#152]
**Background**
This is where we put permit conditions that includes checkbox for user to acknowledge and accept the conditions.  This should come before customer is sent to pay.gov.

**Acceptance criteria** 
- [x] Correct conditions should be displayed for customer's chosen district/forest
- [x] Checkbox can be checked or left blank by customer
- [x] If Checkbox is not checked, user cannot proceed with purchase/pay.gov

**Tasks**
- [x]  Design and test low fi mocks
- [x]  Design refines mocks based on research insights
- [x]  Devs build page from mocks
- [x]  Validation of acceptance criteria completed
- [x] Design review
- [x] Code review
- [ ]  PO Approved

**Definition of done**
- [x] e2e tests are updated for application routing changes.
- [x] e2e tests are functioning.
- [x] Child routes for existing pages are working.
- [x] Pull requests meet technical definition of done.
- [ ] Usability tested.

**Comment by MelissaBraxton** [comment]
Here’s a link to the [mock](https://github.com/USDAForestService/USFS-timber-permitting/blob/master/docs/design-deliverables/online-timber-permitting-ui/2019-12--mvp-usability-test/FS%20MVP1--7.0%20Accept%20terms.jpg)

**Comment by carlsonem** [comment]
@Dmac26 is this one complete?

**Comment by MelissaBraxton** [comment]
Added design and code review tasks.

**Comment by carlsonem** [comment]
@Dmac26 is this complete?

**Comment by carlsonem** [comment]
@Dmac26 please update this page to be Firewood....some stuff relates to Christmas Trees

**Comment by jstrothman** [comment]
@Dmac26 @mtlaney 
Thank you for removing the Christmas Trees language.

However, I'm no longer able to successfully submit the form. Should I create a separate issue for this?
1. Visit https://open-forest-dev.app.cloud.gov/firewood/forests/conf/buy
2. Complete step 1 form, including checking the box for terms and submit the form
3. On step 2, check the terms checkbox and click 'Continue to Checkout'
Result: Step 2 reloads with no indication of error message until I scroll down and see that the terms checkbox in required and now unchecked. 
Expected result: Move on to next step in the flow.

**Comment by jstrothman** [comment]
@aQuib Do we have an error message display at the top of the page when someone has an error in a submission, or do they need to scroll to discover if there's an error in their work?

**Comment by jstrothman** [comment]
@Dmac26 This looks good (Christmas Trees wording is removed)
