### ISSUE TITLE
Order confirmation page 

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#153]
**Background**

This story covers the design and development of the order confirmation page.  

I'd suggest adding a note that this story doesn't cover the printing functionality that's included in the mock.

**Acceptance criteria** 
- [x] Permit purchasers needs to know what they just bought (price, quantity, product, permit#, name, payment, transaction method.    
- [x] Permit purchasers needs to know where to go for more info..
- [x] Permit purchases needs to know what to do next in the process 

**Tasks**
- [X] Design and test low fi mocks
- [X] Design refines mocks based on research insights
- [x] Devs build page from mocks
- [ ] Validation of acceptance criteria completed
- [ ] Design review
- [ ] Code review
- [ ] PO Approved

**Definition of Done**
- [ ] e2e tests are updated for application routing changes.
- [ ] e2e tests are functioning.
- [ ] Child routes for existing pages are working.
- [ ] Pull requests meet technical definition of done.
- [ ]  Usability tested.

[Mock](https://github.com/USDAForestService/USFS-timber-permitting/blob/master/docs/design-deliverables/online-timber-permitting-ui/2019-12--mvp-usability-test/FS%20MVP1--9.0%20Confirm%20and%20next%20steps.jpg)

**Comment by carlsonem** [comment]
This story doesn't include the printing the permit or load tag

**Comment by carlsonem** [comment]
@briandavidson @mtlaney any movement on this issue?

**Comment by briandavidson** [comment]
Work should be complete on this soon @carlsonem. I need some clarification on the mockup though please. What do we want the wording here to be? (cc @MelissaBraxton and @aQuib)

![image](https://user-images.githubusercontent.com/5187168/91356720-1d52f580-e7be-11ea-8d5a-6d56c3f53401.png)

**Comment by MelissaBraxton** [comment]
I'll defer to @aQuib here, but I'm not sure I understand what you're asking and what you're highlighting @briandavidson.

**Comment by jstrothman** [comment]
@briandavidson Is there test payment information I can use, or another way I can view the confirmation page on staging?

**Comment by briandavidson** [comment]
Hi @jstrothman, you can use `4111 1111 1111 1111` for the credit card number. Other than that you can enter anything for the other parts of the form.

You won't see the confirmation page yet though, I'm working on that right now :)

**Comment by briandavidson** [comment]
> I'll defer to @aQuib here, but I'm not sure I understand what you're asking and what you're highlighting @briandavidson.

Hi @MelissaBraxton -- sorry for the lack of clarity in the comment. If you checkout the [mock](https://github.com/USDAForestService/USFS-timber-permitting/blob/master/docs/design-deliverables/online-timber-permitting-ui/2019-12--mvp-usability-test/FS%20MVP1--9.0%20Confirm%20and%20next%20steps.jpg) you can see that a bunch of words are cut off on the right side, which is what I was trying to highlight in the picture.

**Comment by MelissaBraxton** [comment]
Oh, I see! I think you may just need to scroll to the right after clicking that link :) @briandavidson

**Comment by briandavidson** [comment]
Oh wow.. I feel very silly now. Thanks @MelissaBraxton :)

**Comment by briandavidson** [comment]
Moving this over to blocked until we hear back from (qa.)pay.gov
