### ISSUE TITLE
Determine how to handle a rejection response from FPFS

### ISSUE THREAD

**Issue by mgwalker** [USDAForestService/USFS-timber-permitting#154]
**Background**

When Open Forest submits data to FPFS, FPFS can respond with a rejection. We need to determine how to respond in that case. We should also double-check the list of reasons why FPFS might reject a request so we cover all the bases, but as a starting point, I believe Nick has said before that we should only get a rejection if the permit ID is a duplicate.

**Acceptance criteria** 
- [x] We've identified all the situations that could cause FPFS to reject a permit
- [x] We understand the sequence and timing of events related to sending data to TIM an sending data to FPFS
- [x] We determine how to handle a rejection from FPFS

**Tasks**
- [x] Double-check with Nick from FPFS about why the FPFS permit API would reject
- [x] Discuss with TIM and FPFS to unravel the sequence of events so we know what happens in what order
- [x] Weigh pros and cons of alternate approaches, if multiple are identified

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by mgwalker** [comment]
cc: @smahmudFS @bboddiger I don't think we had an issue for this previously, but if we do, please just let me know and I'll close this one!

**Comment by carlsonem** [comment]
@mwreiss please update this card. If duplicate of another issue, please let me know.

**Comment by mwreiss** [comment]
@mtlaney Since we are addressing API standup in another issue, can we close this one out?

**Comment by mwreiss** [comment]
After review with @mtlaney this one can be closed.  We have identified how we will handle a rejected response.
