### ISSUE TITLE
As a state or county with a National forest or grasslands within my boundary, I need my jurisdiction's portion of timber sales money routed correctly in a timely fashion .

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#156]
**Background**
Some forests contain more than one proclaimed unit within the administrative boundaries. Depending on what units are within a specific boundary, funds from firewood permits sales need to be routed to different accounts based on in  job codes and proclaimed units within them. Job codes are the code that the ASR financial group gets; within the code, is info on where and how funds should be dispersed to states and counties. Not all counties get the money through this fund--this only applies to counties that have chosen this method. Another complication is the rolling average fund tends to run out, whereas the direct receipt approach gets counties the money they need faster and the finding may be more consistent. 

Some forests may not offer the firewood harvesting program in every district. This has design implications for the forest selection component and possibly the forest info page. Users may need to downselect to a specific district within the forest they choose. 

**Acceptance criteria** 
- [ ] Sales reporting data is accurate based on districting and proclaimed unit information
- [ ] Open Forest sends the right money to the right place
- [ ] When users buy a permit, it's tied to a specific job code that reflects the location within a forest where they plan to get their wood

**Tasks**
- [ ] Confirm which forests are impacted and what the relevant geo boundaries are
- [ ] Create wireframes to explore possible design approaches to allowing users to select a specific location within a forest
- [ ] Design and dev meet to discuss technical feasibility of options
- [ ] Decide on recommended approach to allowing users to select a specific location within a forest
- [ ] Understand which approach impacted pilot forests are currently using and what is feasible for their unit
- [ ] Decide on backend approach for dispersing funds
- [ ] Meet with FPFS to determine what work is needed and who will do it
- [ ] Create new Open Forest issues for back end development work as needed
- [ ] Determine on how we can get the correct and accurate job code from year to year
- [ ] Build design from mocks
- [ ] Update seeder file
- [ ] Ensure reporting data includes district information

**Definition of done**
- [ ]  
- [ ]

**Comment by MelissaBraxton** [comment]
@aQuib and @carlsonem  - Heads up that Beth and I revised this one quite a bit based on what she learned in a recent meeting with FPFS folks about proclaimed units.  This may need to be reestimated, and we may think about breaking it down since it may be more than can be done in one sprint.
