### ISSUE TITLE
Permit Design

### ISSUE THREAD

**Issue by bboddiger** [USDAForestService/USFS-timber-permitting#157]
**Background**  This could be as simple as ensuring permit looks exactly like FS2400-1.  As an LEO, I need a way to ensure that firewood harvesters are getting wood legally so that I can enforce compliance; As an LEO, I need to know where wood harvesters got their wood when I make a compliance stop so that I can know whether they got their wood from an allowable location and enforce compliance in the field; As an LEO, I need permittee information printed on the permit so that I can verify a person’s identity and enforce compliance in the field. 

**Acceptance criteria** 
- [x] The permittee can indicate the quantity they removed on a given date
- [x] The permit indicates where a user is allowed to get wood (forest and possibly district, if relevant)
- [x] Permit includes minimal required permittee data: permittee name, permit number, dates purchased/valid, and address (possibly Unique government ID number? Signature?)

**Tasks**
- [x] Find out how much flexibility we have w/ the permit design--are we mandated to use the same form FS2400-1? Do we have a contact at OMB who might be familiar with the project?
- [x] What is entailed in getting approval for a form we design, from USFS? from OMB?
- [x] Design and test low fi mocks
- [x] Design refines mocks based on research insights
- [x] PO Approved

**Definition of done**
- [ ] e2e tests are updated for application routing changes.
- [ ] e2e tests are functioning.
- [ ] Child routes for existing pages are working.
- [ ] Pull requests meet technical definition of done.

**Comment by MelissaBraxton** [comment]
[Firewood Permit 02_20_19_2.pdf](https://github.com/USDAForestService/USFS-timber-permitting/files/5030120/Firewood.Permit.02_20_19_2.pdf)
Here's an example FS2400-1 from Gifford Pinchot

**Comment by MelissaBraxton** [comment]
As part of sustainability planning, consider using this as an opportunity to try: 

- The team manually tests a pdf using a screen reader and can identify graphical elements that need to be converted to accessible text
- The team demonstrates that they can adjust the read order to ensure that a screen reader will move through information in a logical sequence

**Comment by aQuib** [comment]
For documentation purposes, here is a list of reasons as to why we decided to reuse FS-2400-1 for MVP permit:

- A redesigned form will require OMB approval (to be compliant with the Paperwork Reduction Act) which is an extensive process.
- Heavy use and references to the FS-2400-1 within Handbook and Manual guidance would require extensive modifications and time.
- There is a low probability that aspects of the compliancy and interdependencies associated with a permit redesign will change in the future.

**Comment by aQuib** [comment]
Here is a lofi mockup of the permit design 'General Conditions' section (base on LEO feedback):
![Firewood Permit mockup v1](https://user-images.githubusercontent.com/2117062/92500695-86c60180-f1cb-11ea-90f7-0f0e0410c020.jpg)

**Comment by carlsonem** [comment]
@aQuib can this be moved to awaiting acceptance? Don't think there is really design work needed since it needs to match the current permit

**Comment by aQuib** [comment]
@carlsonem - Yes, it can (I moved it).
