### ISSUE TITLE
Permit and transaction data auto-populated

### ISSUE THREAD

**Issue by bboddiger** [USDAForestService/USFS-timber-permitting#159]
**Background**
As a permittee, I need the relevant information on my permit purchase transaction to be autopopulated on the permit.

**Acceptance criteria** 
- [ ] Permit is auto populated with permit number
- [ ] Permit is auto populated with where the permit allows me to cut
- [ ] Permit is auto populated with transaction type (?)  Any other data that needs to be included?

**Tasks**
- [ ] Design and Dev tasks TBD
- [ ] Validation of acceptance criteria completed
- [ ] Manual accessibility testing complete
- [ ] Code review
- [ ] PO Approved

**Definition of done**
- [ ]  e2e tests are updated for application routing changes.
- [ ] e2e tests are functioning.
- [ ] Child routes for existing pages are working.
- [ ] Pull requests meet technical definition of done.

**Comment by carlsonem** [comment]
@bboddiger please confirm this can be closed, seems to be a duplciate of #158

**Comment by bboddiger** [comment]
closing, indeed a duplicate of #158
