### ISSUE TITLE
Conduct first field visit

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#16]
**Background**
This card is holding a place for the effort involved in field work, which will be the focus of our effort in sprint Birch. 

**Acceptance criteria** 
- [x] Research has been done, we've returned from the forest safely

**Tasks**
- [x] Interview and observe frontliners, LEOs, and members of the public. 

**Definition of done**
- [x]  Meets acceptance criteria
