### ISSUE TITLE
Permit conditions generation

### ISSUE THREAD

**Issue by bboddiger** [USDAForestService/USFS-timber-permitting#160]
**Background**
As an LEO, I need the specific conditions that the permittee agreed to abide by when they bought their permit to be included in the information they bring with them to get wood so that I can hold them accountable to the conditions of removing wood safely and legally.  
**Acceptance criteria** 
- [ ] Permit is auto populated with the same conditions that the permittee agreed to abide by as part of the purchase process

**Tasks**
- [ ] Design and Dev tasks TBD.
- [ ] Validation of acceptance criteria completed
- [ ] Manual accessibility testing complete
- [ ] Code review
- [ ] PO Approved

**Definition of done**
- [ ]  e2e tests are updated for application routing changes.
- [ ] e2e tests are functioning.
- [ ] Child routes for existing pages are working.
- [ ] Pull requests meet technical definition of done.

**Comment by briandavidson** [comment]
@carlsonem Can I get a confirmation that the gist behind this ticket is to include the "rules and conditions" page along with the other pages that get populated?

**Comment by carlsonem** [comment]
@briandavidson in short, all the rules, both "general" and ones specific to a particular forest need to appear on the permit.

**Comment by briandavidson** [comment]
@aQuib do we have a mockup or specific design for this, or am I just making it look like it does on the site?

**Comment by aQuib** [comment]
@briandavidson - This involves what will be generated on the PDF correct? 
[If so, it should like the current FS24001 second page.](https://github.com/USDAForestService/USFS-timber-permitting/files/5394009/Firewood.Permit.02_20_19_2.1.pdf)

**Comment by carlsonem** [comment]
@briandavidson has this one started? Looks like it's still in the ready column

**Comment by briandavidson** [comment]
@carlsonem this was already done in #158 which is blocked until the issue with puppeteer in the pipeline is resolved. I'll move this to blocked as well for now but perhaps it can just be closed out as a dupe?
