### ISSUE TITLE
As a Timber Permit Purchaser I would like the "Contact us" section to be more visually appealing and easy to read

### ISSUE THREAD

**Issue by Dmac26** [USDAForestService/USFS-timber-permitting#161]
**Background**
Currently, the "Contact Us" sections of each Firewood forest is rather visually unappealing. This issue addresses that with a new mock design and a build-out of the proposed changes

**Acceptance criteria**
- [ ] The "Contact Us" section for each Firewood forest has been updated to be more visually appealing on both desktop and mobile views
- [ ] The updated "Contact Us" sections can be viewed on staging

**Tasks**
- [ ] Evaluate current design for areas of enprovement (w/ competitors analysis).
- [ ] Develop mockups for "Contact Us" section for responsive screen (desktop, tablet, mobile sizes) 
- [ ] Annotate mockup with accessiblity guidlines
- [ ] Conduct design review of mokcup
- [ ] Update UI based on responsive design mockups (desktop, tablet, mobile sizes) 
- [ ] _Completed validation tasks:_
    - [ ] Conduct design review on UI
    - [ ] Conduct manuality accessiblity testing (as needed)

**Definition of done**
- [ ]   e2e tests are updated for application routing changes.
- [ ]  e2e tests are functioning.
- [ ]  Child routes for existing pages are working.
- [ ] Pull requests meet the technical definition of done.
