### ISSUE TITLE
Onboard Julie

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#162]
**Background**
Greg will be joining the team as the new engineering lead

**Acceptance criteria**
- [x] Julie has necessary background and access to tools to feel confident beginning to work with the team.

**Tasks**
Julie reviews relevant project material:
- [x]  Review design lead tasks doc
- [x] Transition plan
- [x]  Peruse Open Forest repos
- [x]  Peruse timber permitting repo 
- [x]  Skim timber permitting Path Analysis report
- [x] Julie has been added to regular UX meetings

- [X]  Julie and Melissa have initial onboarding 1:1
- [x]  Julie added to GitHub team
- [X]  Julie added to Slack channel

**Definition of done**
- [ ] Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
@aQuib or @Rebekah-Hernandez - Can one of you please check the task for adding Julie to UX mtgs once she's on the invite?
