### ISSUE TITLE
As Firewood Permit User I would like the landing page to be free of visible text errors

### ISSUE THREAD

**Issue by Dmac26** [USDAForestService/USFS-timber-permitting#163]
**Background**
Currently the Firewood landing page/forest picker has some textual errors that appear to be caused by some sort of logical error. The errors can be seen below:

![forestPicker_error.png](https://images.zenhubusercontent.com/5d93a896a615ef000109902d/e81c4da2-e9b4-4960-a92f-27d9d20eef16)

**Acceptance criteria**
- [x] The Firewood landing page/forest picker is free of any textual errors.
- [x] The corrected Firewood landing page/forest picker can be viewed on staging.

**Tasks**
- [x] Identify the logical error causing the displayed typo
- [x] Make any necessary changes to resolve the textual error on the forest picker component

**Definition of done**
- [ ]   e2e tests are updated for application routing changes.
- [ ]  e2e tests are functioning.
- [ ]  Child routes for existing pages are working.
- [ ] Pull requests meet technical definition of done.

**Comment by carlsonem** [comment]
@Dmac26 has this one been completed?

**Comment by mtlaney** [comment]
looks good on dev
