### ISSUE TITLE
Deliver accessibility testing training

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#165]
**Background**
As part of our weekly skill area deep dive and as part of long term sustainability planning, we'll offer the team guidance on the importance of accessibility, training on how to do manual accessibility testing, and what to look for to make sure that all new features are accessible.

**Acceptance criteria** 
- [x] Training has been delivered 

**Tasks**
- [X] Schedule time with Chris, Beth, and Julie
- [x] Develop training material

**Definition of done**
- [x]  Training has been delivered

**Comment by MelissaBraxton** [comment]
@bboddiger adding a quick reminder for you to pass on the invite to the NRM tech writer you mentioned!  This is scheduled for Tues. 8/18

**Comment by MelissaBraxton** [comment]
If we have time, Julie may also use this meeting to cover at least part of the design deep dive.
