### ISSUE TITLE
Create NRM test API endpoint

### ISSUE THREAD

**Issue by mtlaney** [USDAForestService/USFS-timber-permitting#166]
## Notes
* NRM needs an endpoint setup to test the data flow connecting to the application *

## Acceptance Criteria
- [x] New endpoint has been created
- [x] API endpoint can access a simple get request to return data
- [x] Has been tested on Swagger

## Tasks
- [x] Create endpoint
- [ ] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup
- [x] Usability tested

**Comment by MelissaBraxton** [comment]
@mtlaney - Should this be in awaiting acceptance?
