### ISSUE TITLE
Remove Code Artifact

### ISSUE THREAD

**Issue by mtlaney** [USDAForestService/USFS-timber-permitting#167]
**Background**
Code artifact in the When to Cut component needs to be removed, it was placed there for testing.

**Acceptance criteria** 
- [ ] Artifact is removed

**Tasks**
- [ ] Remove Code Artifact

**Definition of done**
- [ ]  Peer Reviewed
- [ ] Code Artifact has been removed
