### ISSUE TITLE
***NOTE: all of the work for this card was done on card 113 - As a Firewood Permitting Admin I'd like the number of cords a user can select to be restricted to the maximum allowable number

### ISSUE THREAD

**Issue by Dmac26** [USDAForestService/USFS-timber-permitting#169]
**Background**
The current dropdown selection for the number of cords a user can choose is  only showing the option "4". Ideally the dropdown would present a range from the minimum to the maximum permissible number of cords. Each forest has a different minimum and maximum and the dropdown should reflect each forest's standards with accompanying validation.

![Firewood_Dropdown.png](https://images.zenhubusercontent.com/5d93a896a615ef000109902d/f9caa88e-b390-45e5-a883-f784ce1af432)

**Acceptance criteria**

**Tasks**
- [x] Identify the logical error causing the displayed typo
- [x] Make any necessary changes to resolve the textual error on the forest picker component

**Definition of done**
- [x]   e2e tests are updated for application routing changes.
- [x]  e2e tests are functioning.
- [x]  Child routes for existing pages are working.
- [x] Pull requests meet technical definition of done.

**Comment by carlsonem** [comment]
Obtain the information for the limits on the[ content standardization page](https://usfs.app.box.com/file/709474700305)

**Comment by Rebekah-Hernandez** [comment]
@Dmac26 
Finally received confirmation from the last forest today so here are the maximum limits for the forests. Chattahoochee's is so high because they don't have a set limit so it is the national handbook's maximum.

Idaho Panhandle: 4 cord minimum purchase - 12 cord max limit
Flathead: 4 cord minimum purchase -  12 cord max limit
George Washington and Jefferson: 6 cord purchase only allowed
Chattahoochee-Oconee: 3 cord minimum purchase - 200 cord max limit
Hiawatha: 4 cord minimum purchase - 20 cord max limit
GMUG: 4 cord minimum purchase - 20 cord max limit
Shoshone: 3 cord minimum purchase - 10 cord max limit

**Comment by Dmac26** [comment]
@MelissaBraxton @aQuib @tram - Hey everybody, I was looking through the "ready" column and came across this one. I was under the impression we were moving away from a dropdown and using an input field instead. I've already made the change for that as I was working on card 113 and it works well, but I can definitely take this on if I was mistaken.

**Comment by MelissaBraxton** [comment]
@Dmac26 - You're correct that the text input is the path forward. I'm a little unclear as the history behind this issue, and it doesn't have any acceptance criteria. It mentions a bug/typo, but it looks like it's about restricting users to purchasing more than the max allowed per forest, which is covered under #113. @Dmac26 it looks like you created this issues--with the work covered under 113 can it be closed?

**Comment by mtlaney** [comment]
Calculations appear to be correct on the open forest side. We will need to verify we are sending the right amount to pay.gov
