### ISSUE TITLE
Synthesize field research

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#17]
**Background**
We'll aim to have identified high-level themes by the close of this sprint, with the understanding that we'll continue to dig deep into the data in sprint c. 

**Acceptance criteria** 
- [x] Synthesis includes relevant insights pulled from all interviews and observations
- [x] Synthesis is happening in a form/format that partners can view participate in

**Tasks**
- [x] Document interviews and observations from all participants
- [x] Pull quotes and insights from research documentation into collaborative analysis place (Mural, G sheets, etc.) and pre-sort
- [x] Schedule collaborative synthesis meeting including FS product folks
- [x] Identify key themes 

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by tram** [comment]
Synthesis board: https://app.mural.co/t/gsa6/m/gsa6/1573750999653/04ec926473b74566fa6d9716d0ee021562a5c127
