### ISSUE TITLE
18F delivers functional area heuristics to USFS folks

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#170]
**Background**
As part of our transition/sustainability planning, USFS folks will need an easy reference to help them review research and design artifacts and code. 

**Acceptance criteria** 
- [x] USFS has a concise and understandable list of heuristics
- [x] Heuristics live in an easily accessible place in Box 

**Tasks**
- [x] @MelissaBraxton documents product heuristics
- [x] @mgwalker documents code heuristics
- [x] @jstrothman and @tram document user research heuristics
- [x] @jstrothman and @tram document user design/usability heuristics
- [x] @annepetersen documents content heuristics
- [x] PM review
- [x] PO review

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
With @bboddiger and @csstarling for review, will move to a good easily accessible location once we have a thumbs up!
