### ISSUE TITLE
18F delivers dev deep dive training

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#171]
**Background**
As part of our weekly skill area deep dive and as part of long term sustainability planning, we'll offer the USFS folks guidance on code review including coaching on how to verify that PRs include new tests that capture bugs to prevent future regression.

**Acceptance criteria** 
- [ ]  Training has been delivered

**Tasks**
- [x] Schedule time w/ Chris, Beth, and Greg
- [x] @mgwalker preps training material

**Definition of done**
- [ ]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
Scheduled for 8/25
