### ISSUE TITLE
Audit design documentation for accuracy and completeness

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#174]
**Acceptance criteria** 
- [ ] We have confirmed that design documentation is accurate and up to date

**Tasks**
- [x] The team has documented and demonstrated their process for integrating design research into agile sprints #199  
- [ ] Establish and document a practice of auditing and updating project documentation on a quarterly basis
- [ ] The team documents and demonstrates a regular cadence for accessibility testing #201 
- [x] The team has documented content heuristics that are findable in the Open Forest wiki, style guide, or design system

**Definition of done**
- [ ]  Meets acceptance criteria

**Comment by jstrothman** [comment]
skill area heuristics are at: https://github.com/USDAForestService/fs-open-forest/wiki/Skill-area-heuristics
