### ISSUE TITLE
Ensure that the team is able to maintain and scale within Cloud.gov 

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#175]
**Background**
Tasks that will help ensure that team is able to upgrade the brokered service plan in Cloud.gov with minimal to no downtime if/when needed. 

**Acceptance criteria** 
- [ ] Someone new to the team can easily find understandable information on what is needed in order to maintain and scale within Cloud.gov 

**Tasks**
- [ ] Ensure that the team is able to maintain and scale within Cloud.gov 
- [ ] Add sharing of credentials to developer onboarding
- [ ] The team has appropriate permissions and credentials to configure Cloud.gov
- [ ] Create an automated task for updating environment variables in Cloud.gov
- [ ] The team has an understanding of any resource quotas in our contract with Cloud.gov

**Definition of done**
- [ ]  Meets acceptance criteria

**Comment by carlsonem** [comment]
@abdul-fs can you please document this process. Please check with Matt on the details
