### ISSUE TITLE
Revisit roadmap and refine success metrics

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#176]
**Background**
Work that help the team be rwady for this success scenario: Forest Management decides to add a new permit type to the application. The USFS crafts and aligns stakeholders on an evidence-based product vision and roadmap for the new permit type and can bring on a team to execute it. 

**Acceptance criteria** 
- [x] An up-to-date roadmap
- [x] most recent roadmap updates were made by USFS staff

**tasks**
- [x] 18F and USFS products folks collaboratively update the product roadmap and revisit/refine success metrics and document a regular cadence for revisiting it
- [x] Add the design and implementation of a customer feedback intercept to the product roadmap including a backend process for ingesting and responding to customer feedback

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
@bboddiger - To close this out, let's go over these things at our regular mtg on 9/15:
 - document your cadence for revisiting the roadmap going forward int he wiki
 - NEW ISSUE for customer feedback intercept
 - In the roadmap, adding the self service on-boarding experience as a key success metric for phase 2 scale up

Moving this to blocked until we have that mtg!

**Comment by bboddiger** [comment]
Sounds good.  Thanks!
