### ISSUE TITLE
As an Open Forest team member, I would like to have access to all the documentation, processes, and (when applicable) emails associated with Firewood Customer Support, so that I can successfully resolve any customer issues that might arise.

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#177]
**Background**
In preparation for the pilot of Firewood, we want the Customer Support team to have all of the potential issues spotted and solutions found as well as access available for anyone in the team who is helping with firewood customer service.

**Acceptance criteria** 
<s>- [ ] Wiki is prepared and accessible for Firewood Customer Support</s>
- [x] Customer support inbox is prepared for Firewood
- [x] ServiceNow is prepared and accessible for Firewood Customer Support
- [x] Customer Support spreadsheet is prepared and accessible for Firewood Customer Support

**Tasks**
- [x] Go through old Christmas Trees material to find out what is recyclable
- [x] Spot potential different issues in firewood and draft solutions for these
<s>- [ ] Make sure all information is readily accessible on the wiki: https://github.com/USDAForestService/fs-open-forest/wiki/Intro</s>
- [x] Make sure all service reps have access to ServiceNow
- [x] Set up ServiceNow pipeline
- [x] Set up Customer Support spreadsheet and make accessible for tracking purposes
- [x] Set up Customer Support inbox with folders to prepare for incoming traffic
- [x] Create Zenhub template for Customer Support issues
- [x] Identify and document the best practices for issue escalation
- [x] If needed, set up another card for wiki follow up

**Definition of done**
- [ ]  PO Approved
- [ ] Any and all created material has been viewed and approved by a third party

**Comment by Dmac26** [comment]
I'm currently unable to access serviceNow. However, I've reached out to Jeffrey Lanham and have started the process of getting access again.

**Comment by MelissaBraxton** [comment]
This looks good, @Dmac26 and @Rebekah-Hernandez!   Do we need a separate issue to make sure that firewood permitting users know how they can get help? (e.g., do we include the help email address in the footer, where else in the process are people likely need help and are we giving them the right link in context)

**Comment by Rebekah-Hernandez** [comment]
@MelissaBraxton I had just assumed the CS email would be in the same places as it was on Christmas trees. I just checked and the address is already in the footer. If you'd like to talk about including it elsewhere, we can certainly create a new issue to discuss where else this would be needed.

**Comment by Rebekah-Hernandez** [comment]
@Dmac26 please check the documents at this link when you have a chance https://usfs.app.box.com/folder/122061423039

**Comment by Dmac26** [comment]
@Rebekah-Hernandez - https://usfs.app.box.com/folder/122674592862

**Comment by Rebekah-Hernandez** [comment]
Issue Escalation:
- Create issue card based on correct template for the issue
- Assign the correct members to the issue based on what type of issue and @ in a comment
- Reach out to the assignees in Teams so they know what is expected
- For front end issues, reach out to Dylan first, then Brian or Mike
- For back end/server issues, reach out to Abdul first, then Jon, Matt or Shadat
- If a high level issue, CC Shadat/Matt or Mike depending on the issue
- If high priority, alert PO
- Continue to track issue progress on card

**Comment by Rebekah-Hernandez** [comment]
[Issue card 1461](https://github.com/USDAForestService/fs-open-forest-platform/issues/1461) has been created for the wiki follow up to this issue

**Comment by Rebekah-Hernandez** [comment]
@bboddiger This one is ready to be validated. If you click on these two links and check all of the content there, we should be good to go! Thanks!
- https://usfs.app.box.com/folder/122674592862
- https://usfs.app.box.com/folder/122061423039

**Comment by bboddiger** [comment]
@Rebekah-Hernandez  I do not seem to have access to the box folder/documents:
https://usfs.app.box.com/folder/122674592862
https://usfs.app.box.com/folder/122061423039

Do you know who has owner access and can check to see if I've been given access in Pinyon/Box?
Sorry for the extra work.
Thanks!

**Comment by Dmac26** [comment]
@bboddiger - Hey Beth, Rebekah asked me to take a look at this. It seems we can't even give you access. I'm thinking we're going to have to talk to @carlsonem 

Eric - Beth is needing access to our customer service documentation on Pinyon so she can review. Can you help with that?

https://usfs.app.box.com/folder/122674592862
https://usfs.app.box.com/folder/122061423039

**Comment by Rebekah-Hernandez** [comment]
Thanks @Dmac26 for tagging for me
@bboddiger I apologize, I was unable to access Chrome this morning to help you myself. Once you check over, you can ping me and I'll start getting everything moved to the wiki. Thanks!

**Comment by carlsonem** [comment]
@Rebekah-Hernandez can this be moved over to the approval column

**Comment by Rebekah-Hernandez** [comment]
@carlsonem Yes it can. I moved it to ready for main, not sure if it can go straight to done
