### ISSUE TITLE
Drft governance plan and plan for prioritizing among various permit efforts

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#179]
**Background**
Re: sucess scenario: Forest Management decides to add a new permit type to the application. The USFS crafts and aligns stakeholders on an evidence-based product vision and roadmap for the new permit type and can bring on a team to execute it. 

**Acceptance criteria** 
- [ ] The prioritization process for Open Forest products within the USFS is well known by the team as well as internal and external stakeholders

**Tasks**
- [ ] Review prior work on Open Forest governance plan
- [ ] Forest service product folks work with USFS leadership to drive toward a governance plan for work on different Open Forest products

**Definition of done**
- [ ]  Meets acceptance criteria
