### ISSUE TITLE
Present at TIM coordinator meeting to orient stakeholders to this phase of work

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#18]
**Background**
We'll be inviting a group of Regional TIM coordinators to observe sprint reviews, and we'll want to provide background on the project and process and guidelines for observing sprint reviews prior to that meeting. 

**Acceptance criteria** 
- [x] Orientation has been delivered

**Tasks**
- [x] Collaborate with Beth to schedule meeting 
- [x] Prepare deck and other materials

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
Draft agenda [here](https://docs.google.com/document/d/1ktPjoL4qwG01q2aFEOtoojcTTAWER0-Yo-QugrIoGpk/edit#heading=h.tul62dhv7ot1).

Draft deck [here.](https://docs.google.com/presentation/d/1_yJRr4syNay3EYFStgYvx8whdF56jZR50LY2SHTjzLs/edit#slide=id.g46c8ba97d9_0_283)

**Comment by MelissaBraxton** [comment]
Beth and I talked about this possible agenda/things to cover:

1. Background re: beginning with permitting
2. Who we talked to in PA and what we learned
5. The scope of the immediate project
4. Who we've talked to re: permitting and what we’ve learned/heard 
6. Timing, next steps, and involvement
7. High-level schedule / sprint cadence / sprint ceremonies
8. What to expect at sprint review
9. Why we prototype???
