### ISSUE TITLE
Create communication and engagement plan

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#180]
**Background**
_What should we consider when addressing this issue?_

**Acceptance criteria** 
- [x] The USFS product folks have a stakeholder engagement plan that specifies key stakeholder groups, key messages, goals for their engagement and when, how, and how often the product staff should engage.  

**Tasks**
- [x] Schedule co-working session inclusing Anne, Beth, Chris, and possibly Anna Fargo
- [x] Plan co-working facilitation @annepetersen 
- [x] Draft stakeholder engagement plan
- [x] circulate for review
- [x] Document refined plan in findable place. 

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
@mgwalker  - Since I'm without Teams and Outlook access right now, can you please take on the task to get this scheduled for the week of 8/24 or the week after?

**Comment by annepetersen** [comment]
Initial coworking on draft comms plan happened with @AnnaFargo today

**Comment by MelissaBraxton** [comment]
Revising since the acceptance criteria were redundant with #142.

**Comment by bboddiger** [comment]
@annepetersen  @MelissaBraxton @AnnaFargo   Draft communication plan approved, sent back to Anne with one comment.

**Comment by annepetersen** [comment]
@bboddiger Revised version back to you, and the document is now yours to own and operate!
