### ISSUE TITLE
Load tag design 

### ISSUE THREAD

**Issue by csstarling** [USDAForestService/USFS-timber-permitting#181]
**Background**
As an LEO, I need load tags to contain basic information that I need in order to ensure compliance: Quantity removed, date removed, permit number that matches the permit issued. 

We’ll also want the tag to be visible from a distance and to include instructions on how to tag the load, and how to distinguish this year’s permit from last year’s, but we’re planning to break those into separate stories. 

This story covers the basic permit design. 

**Acceptance criteria** 

- [x] LEOs can match the tag to the corresponding permit
- [x] Load tag allows permit holder to indicate quantity removed 
- [x] Load tag allows permit holder to indicate date product removed

**Tasks**

- [x] Design and test low fi mocks
- [x] Design refines mocks based on research insights
- [x] Validation of acceptance criteria completed
- [x] Design review
~~- [ ] Manual accessibility testing complete~~
- [ ] PO Approved

**Definition of done**

- [ ] e2e tests are updated for application routing changes.
- [ ]  e2e tests are functioning.
- [ ]  Child routes for existing pages are working.
- [ ]  Pull requests meet technical definition of done.
- [x] Usability tested.

**Comment by csstarling** [comment]
Link to [design debt](https://github.com/USDAForestService/USFS-timber-permitting/wiki/Known-Design-debt) in wiki and [initial (very rough) tag design](https://github.com/USDAForestService/USFS-timber-permitting/blob/master/docs/design-deliverables/printable-load-tags/2019-12--mvp-usability-test/FS%20MVP1--11.0--Printable-load-tag.png)

**Comment by carlsonem** [comment]
@aQuib where do this issue stand? Looks like we weren't able to start it this sprint as planned

**Comment by aQuib** [comment]
@MelissaBraxton - Can I get access to this [document](https://docs.google.com/document/d/1vz6A0pETZShtSnbMCgWyILFdJZVkYlZb5caZFQ45gHE/edit?folder=1OlKHs8CMYMtryyLuij2pFpcm1fu1aqaD#heading=h.h4gb2cawjsha)?

**Comment by aQuib** [comment]
Removed 'Manual accessibility testing' since it should be performed on the PDF generated by the system which is apart of the development/engineering requirements for #184

**Comment by Rebekah-Hernandez** [comment]
Here is the updated load tags. I am currently looking into which forests will need different ones based on location.
[Load Tag v3.pdf](https://github.com/USDAForestService/USFS-timber-permitting/files/5269024/Load.Tag.v3.pdf)

**Comment by Rebekah-Hernandez** [comment]
@aQuib I moved this into validation, but I'm not sure about marking off the Definitions of Done

**Comment by aQuib** [comment]
We intend to use only pattern for the MVP, and three patterns for phase two of the application.

**Comment by MelissaBraxton** [comment]
@aQuib - Are there any new issues to address feedback from last week's testing? The first iteration story is complete, but I think you may be working on refinements?  Once we have new issues documenting any refinements, we can move this card to ready for main.

**Comment by aQuib** [comment]
@MelissaBraxton - Yes, there are refinements based on usability testing results. [I have created an issue for the load tag enhancement](https://github.com/USDAForestService/USFS-timber-permitting/issues/214) which can we refine during our backlog grooming. Moving this issue to 'Ready for Main'
