### ISSUE TITLE
As a permit purchaser, I would like the standardization of firewood content on the website so that I can intuitively identify relevant information for each pilot forest.

### ISSUE THREAD

**Issue by Rebekah-Hernandez** [USDAForestService/USFS-timber-permitting#182]
**Background**
Now that the Open Forest pilot forests content for firewood has been standardized, we need to update it in the code.

**Acceptance criteria** 
- [x] All content standardization has been updated in the box notes and color coordinated for the developers to know what needs to be updated
- [x] Content from each forest has been updated in the code

**Tasks**
- [x] Idaho Panhandle firewood content is updated in the code
- [x] Flathead firewood content is updated in the code
- [x] George Washington & Jefferson firewood content is updated in the code
- [x] Chattahoochee-Oconee firewood content is updated in the code
- [x] Hiawatha firewood content is updated in the code
- [x] GMUG firewood content is updated in the code
- [x] Shoshone firewood content is updated in the code

**Definition of done**
- [x]  Validation of acceptance criteria completed
- [ ]  PO approved

**Comment by Rebekah-Hernandez** [comment]
All of the box notes with updated information can be found here:
Idaho Panhandle: https://usfs.app.box.com/notes/688416571963
Flathead: https://usfs.app.box.com/notes/688880706516
GWJ: https://usfs.app.box.com/notes/688973145592
Chattahoochee-Oconee: https://usfs.app.box.com/notes/690664045162
Hiawatha: https://usfs.app.box.com/notes/689746453761
GMUG: https://usfs.app.box.com/notes/693423559218
Shoshone: https://usfs.app.box.com/notes/691885902953

Content that differed from the first round of content upload is marked in green text. The headings on Idaho Panhandle are the correct headings throughout all forests. All info should be matched exactly to the box notes. All info about load tags needs to be removed.

**Comment by mtlaney** [comment]
@Dmac26 can you verify this one and check the boxes. My quick check on DEV didn't match up w/ the BOX notes.

Below is IPNF dev vs IPNF box

![Screen Shot 2020-10-19 at 9 08 19 PM](https://user-images.githubusercontent.com/18233188/96528234-24dbcb80-1250-11eb-81f9-5654a027d63f.png)
<img width="615" alt="Screen Shot 2020-10-19 at 9 08 25 PM" src="https://user-images.githubusercontent.com/18233188/96528240-29a07f80-1250-11eb-8ec6-0e2e2adde045.png">

**Comment by Dmac26** [comment]
@mtlaney - I will go through and verify today

**Comment by Dmac26** [comment]
@mlaney - I double-checked these updates per your request and have made some changes. @Rebekah-Hernandez - If you have a chance would you mind taking a look as well? Should be on Dev
