### ISSUE TITLE
As a keyboard navigator or screen reader user, I'd like to skip to the main content

### ISSUE THREAD

**Issue by jstrothman** [USDAForestService/USFS-timber-permitting#183]
**Background**
The site has a skip-nav link, which is very useful to both screen reader users and keyboard navigators, so they don’t have to move through each link in the navigation before getting to the actual content. Currently, it’s not made visible when it receives focus, so keyboard navigators don’t know that it is there.

**Acceptance criteria**
- [ ] When the url bar has focus and you press your tab key, the 'Skip to main content' link should appear like on the [USFS Web Design Standards site](https://nciinc.github.io/fs-fork-uswds-site/)

**Tasks**
- [ ] Code in the skip navigation link
- [ ] Code in the focus link
- [ ] Screen Reader Testing
- [ ] User testing

**Definition of done**
- [ ] Validation of acceptance criteria completed
- [ ] PO approved

**Comment by Dmac26** [comment]
@jstrothman - Hi Julie, I'm still learning here and I'm guessing Mike and Brian would know what you're referencing here, but would you mind taking a screen-shot just to make sure we fully understand.

**Comment by jstrothman** [comment]
Hi @Dmac26 Sure thing!
Here's the `Skip to main content` link when it has focus on the USFS Design Standards site (see top left of screenshot)
![Screen Shot 2020-09-08 at 12 59 48 PM](https://user-images.githubusercontent.com/1080991/92506357-54b89d80-f1d3-11ea-9484-cf8193e6556d.png)

Here's the Firewood dev site with the `.usa-skipnav` link highlighted in the code
![Screen Shot 2020-09-08 at 1 02 32 PM](https://user-images.githubusercontent.com/1080991/92506644-c0026f80-f1d3-11ea-996a-2c948ff05d94.png)

**Comment by jstrothman** [comment]
@Dmac26 This appears to be fixed on dev!

**Comment by Dmac26** [comment]
@jstrothman - Awesome! We'll check it off then.
