### ISSUE TITLE
Load Tag-Dev

### ISSUE THREAD

**Issue by bboddiger** [USDAForestService/USFS-timber-permitting#184]
**Background**
This issue covers development of use-at-home load tag.
I need the relevant information I entered into the permit order form to be automatically populated on my load tags, so I can legally get wood.  

Currently, load tags are designed to be printed by customer.
This is for emailed print-at-home load tag.  How the load tag is displayed in OF/URL will be designed under separate issue.

**Acceptance criteria** 
- [x] File size is small enough to email.
- [x] Load tag is fully accessible as pdf, including reading order of content.

**Tasks**
- [x] Dev builds page from mocks (#181)
- [x] Validation of acceptance criteria 
- [x] Design review
- [x] Code review
- [ ] Manual accessibility testing complete
- [ ] PO Approved

**Definition of done**
- [x] e2e tests are functioning
- [x] Child routes for existing pages are 
- [x] Pull requests meet technical definition of done.
- [ ] Usability tested.

**Comment by bboddiger** [comment]
@carlsonem and @mtlaney  We created the load tag dev issue today so you don't have to.

**Comment by Rebekah-Hernandez** [comment]
Assets for the instruction page of the load tag:
[Load Tag Assets.zip](https://github.com/USDAForestService/USFS-timber-permitting/files/5342102/Load.Tag.Assets.zip)

**Comment by briandavidson** [comment]
Remaining development on this is blocked until the issues with puppeteer in the pipeline are resolved.
