### ISSUE TITLE
Map data from Open Forest to NRM-TIM

### ISSUE THREAD

**Issue by mgwalker** [USDAForestService/USFS-timber-permitting#185]
**Background**

This should follow on from the data flow modeling work in #145. We need to now map the data being collected by Open Forest into the data needed by NRM-TIM and FPFS. All of the relevant information appears to be in the comments on #145, so that seems like a good place to start from!

**Acceptance criteria** 
- [x] We know which Open Forest fields go to NRM-TIM and what they are called on the NRM-TIM side
- [x] We know about any fields required by NRM-TIM that are not included in Open Forest

**Tasks**
- [x] Map the data collected by Open Forest (identified in #145) to the fields required by NRM-TIM
- [x] Record any NRM-TIM fields that are not captured by Open Forest

**Definition of done**
- [x] We have maps of data from Open Forest to external systems!
- [x] We have a list of missing data so that we can decide what to do about them.
- [ ] PO Approved

**Comment by mwreiss** [comment]
Data mapping for NRM-TIM is in good shape.  FPFS will still need attention.  Since this is a pretty big issue and will take some time to go through the FPFS mapping, do you want to split the NRM-TIM and FPFS efforts up into 2 bite size issues @mgwalker .  Both will need to go through the same process.  Just a thought, thanks!

**Comment by bboddiger** [comment]
That is probably a good idea, I would support that.

**Comment by mwreiss** [comment]
@smahmudFS when we have the final draft for TIM data mapping, lets post and close this issue out.  TY!

**Comment by bboddiger** [comment]
Thank you!  Is it possible to also rename this issue so it reflects just the NRM/TIM side in the title?

**Comment by mwreiss** [comment]
@bboddiger it should be updated now.  Thank you!

**Comment by carlsonem** [comment]
@mtlaney Please create a separate issue(s) for the web services that need to be created

**Comment by mwreiss** [comment]
@carlsonem data mapping is complete, this can be move to awaiting acceptance.
