### ISSUE TITLE
Create DB Migration and add state fips code to seeder

### ISSUE THREAD

**Issue by mtlaney** [USDAForestService/USFS-timber-permitting#186]
## Notes
* We need to create a database migration file to add the state_fips column and data to the forests.js seeder file. This will allow Open Forest to send FIPS information to FPFS and NRM*

## Acceptance Criteria
- [x] Migration is created
- [x] Seeder has been updated
- [x] Forests columns in model and controller have been updated
- [x] We are able to see state_fips on curl or swagger

## Tasks
- [x] create migration
- [x] update seeder file
- [x] update forest controller
- [x] update fs-forests model
- [x] update forest services
- [x] test locally and on swagger
- [ ] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup
- [x] Usability tested
