### ISSUE TITLE
As a FS staffer, I would like to manage feedback submitted on Open Forest so that can engage with customers.

### ISSUE THREAD

**Issue by bboddiger** [USDAForestService/USFS-timber-permitting#187]
**Background**
There is a need for customers to submit feedback to Open Forest/Forest Service outside of the help process. 

**Acceptance criteria** 
- [ ] A member of the public is able to provide feedback within the Open Forest platform
- [ ] Appropriate FS staff is able to easily review feedback provided by the public
- [ ] Appropriate FS staff is able to track feedback provided by the public

**Tasks**
- [x] Interview appropriate FS staff to understand feedback current process and needs
- [x] Analyze and diagram the current feedback system and workflow 
- [x] Conduct competitive analysis of interaction design
- [x] Develop wireframe of enhanced interaction design
- [x] Conduct usability testing
- [x] Refine design hypothesis (wireframe with annotations)
- [x] Analyze technical feasibility with development 
- [ ] Code and update feedback component of the platform 
- [ ] PO Approved
- [ ] Design review and approved
- [ ] Code Reviewed

**Definition of done**
- [ ] 2e tests are updated for application routing changes.
- [ ] e2e tests are functioning.
- [ ] Child routes for existing pages are working.
- [ ] Pull requests meet the technical definition of done.
- [ ] Usability tested.

**Comment by bboddiger** [comment]
@carlsonem @MelissaBraxton @tram This is placeholder for now.  All details still need to be filled in.

**Comment by aQuib** [comment]
[Wireframe to be usability tested](https://usfs.app.box.com/file/782492395065)

**Comment by aQuib** [comment]
Here are wireframe to guide development:
[https://app.zenhub.com/files/214296595/824364da-c8ea-4d78-9a98-3dd458bc86dc/download](https://app.zenhub.com/files/214296595/824364da-c8ea-4d78-9a98-3dd458bc86dc/download)
