### ISSUE TITLE
MVP pilot plan - detailed

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#188]
**Background**
Now that we are closer to the pilot release date, we need a detailed pilot plan.
**Acceptance criteria** 
- [ ] The team understands what the pilot will entail including when it run, for how long, major milestones, and how we will measure success
- [x] The pilot plan accounts for rolling out the MVP in R1 and R2 forests
- [x] Pilot plan is updated in the wiki

**Tasks**
- [X] Run pilot planning session
- [x] Draft detailed pilot plan
- [ ] PM approved
- [ ] PO approved
- [ ] Socialize plan with the team

**Definition of done**
- [ ]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
@bboddiger  - This is ready for you to approve! https://github.com/USDAForestService/USFS-timber-permitting/wiki/MVP-pilot-plan

Once you approve, we can socialize with the team and check the remaining boxes.
