### ISSUE TITLE
Add Region Name and Forest Code to Firewood Forests DB

### ISSUE THREAD

**Issue by mtlaney** [USDAForestService/USFS-timber-permitting#190]
## Notes
* We need to add region name and forest code to firewood forests db in order to work with NRM / FPFS, FS-2400 Forms*

## Acceptance Criteria
- [x] Region Name is added
- [x] Forest Code is added
- [x] Both can be seen locally on swagger

## Tasks
- [x] Add Forest Code and Region Name migration
- [x] Add Forest Code and Region Name to seeder file
- [x] Add Forest Code and Region Name to Get Requests

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup
- [x] Usability tested
