### ISSUE TITLE
Create forest districts and district code in firewood database

### ISSUE THREAD

**Issue by mtlaney** [USDAForestService/USFS-timber-permitting#191]
## Notes
* We will need to utilize forest districts and district codes within open forest to transmit data to NRM and FS-2400*

## Acceptance Criteria
- [x] Forest Districts have been added
- [x] District codes have been added

## Tasks
- [x] Add District and District Codes to migration 
- [x] Add District and District Codes to seeder file 
- [x] Add District and District Codes to controller 
- [x] Add District and District Codes to model
- [x] Add District and District Codes to service  
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup
- [x] Usability tested

**Comment by mtlaney** [comment]
[active_district_proclaimed_units_in_TIM.xlsx](https://github.com/USDAForestService/USFS-timber-permitting/files/5268937/active_district_proclaimed_units_in_TIM.xlsx)

**Comment by mtlaney** [comment]
[active_districts_in_TIM.xlsx](https://github.com/USDAForestService/USFS-timber-permitting/files/5268941/active_districts_in_TIM.xlsx)
