### ISSUE TITLE
Angular Upgrade

### ISSUE THREAD

**Issue by mtlaney** [USDAForestService/USFS-timber-permitting#192]
## Notes
* Angular security for this version ends on November 8th 2020. Prior to MVP release we should upgrade to Angular Version 9 or even 10 if it's released in LTS *

## Acceptance Criteria
- [ ] Angular is upgraded to Version 9 or 10 with LTS
- [ ] All core functions of the application continue to work

## Tasks
- [ ] Upgrade Angular sequentially to version 9 or even 10 depending on LTS release date
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
