### ISSUE TITLE
Investigate and solve pay.gov error

### ISSUE THREAD

**Issue by mtlaney** [USDAForestService/USFS-timber-permitting#193]
## Notes
* Currently pay.gov on staging and production is error'ing out. The cause of the error is mostly unknown. Pay.gov team did give us one line output of **Caused by: java.lang.IllegalArgumentException: Header:Location Cannot contain CRLF Charcters** *

## Acceptance Criteria
- [x] pay.gov error is found
- [x] error is corrected and work is logged
- [x] test fix on staging and qa.pay.gov

## Tasks
- [x] find pay.gov CLRF error and correct
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup
- [x] Usability tested

**Comment by mtlaney** [comment]
appears to be working in staging

**Comment by mwreiss** [comment]
@carlsonem did you get word from the POSS team that it showed up on their side?
