### ISSUE TITLE
As a forests Admin I'd like the "Tagging your load" section of each forest's page correctly updated to reflect current standards

### ISSUE THREAD

**Issue by Dmac26** [USDAForestService/USFS-timber-permitting#194]
## Notes

New language needs to be added to the "Tagging your load" section of each forest's page in order to ensure that each permittee complies with the load tagging standards and displays their tag properly.

## Tasks
- [x] Add the updated language for load tagging to each forest
- [x] Update Hiawatha's price per cord info
- [x] Update side-bar to say "How to Gather"
- [ ] PO approved

**Definition of done**
- [x]  e2e tests are updated for application routing changes.
- [x]  e2e tests are functioning.
- [x]  Child routes for existing pages are working.
- [x]  Pull requests meet technical definition of done.

**Comment by mtlaney** [comment]
tested and looks good on dev

**Comment by MelissaBraxton** [comment]
Hi @aQuib and @Rebekah-Hernandez (cc @Dmac26):  I have some questions about the load tagging section. 

Every forest's load tagging section looks the same. Each forest has a **tagging your load** section that states "Before hauling wood out of the forest, you will need to fill out a load tag and attach it to the back of your vehicle." Then there's a section for **Filling out tags for online permits** and one for **Filling out tags for in-person permits.**

It's my understanding that all but the R2 Forests (the GMUG and the Shoshone) do not sell load tags in the office and there is no process for filling out tags for in-person permits, because tags are not currently required for in-person permits. Is this still the case?   

If so, then for the R1, R8, and R9 forests, the "tagging your load" section will need to be significantly revised to make it clear that there is a load tagging requirement for permits purchased online only, but not for in-office purchases. The **filling out tags for in-person permits** section will also need to be removed from these forest's pages. I can work with you on revising the content, but I first wanted to double check my understanding that the **Filling out tags for in-person permits** section is irrelevant for all but the GMUG and Shoshone forests, since you've had more recent contact with the forests.

**Comment by Rebekah-Hernandez** [comment]
Thank you for pointing that out @MelissaBraxton . I will change the info on the forest info pages and ask @Dmac26 to update it on the site from there.

**Comment by MelissaBraxton** [comment]
Thanks @Rebekah-Hernandez and @Dmac26  - Hold off making changes just yet! I have some other content recommendations on that section. I'll upload suggested revisions to this issue by COB today.

**Comment by MelissaBraxton** [comment]
@Rebekah-Hernandez and @Dmac26 - Here are suggested edits to the tagging sections: 
[Load tagging content edits_MB_10.22.20.docx](https://github.com/USDAForestService/USFS-timber-permitting/files/5426395/Load.tagging.content.edits_MB_10.22.20.docx)

**Comment by MelissaBraxton** [comment]
@Dmac26  - Moving this back to ready (but feel free to put it "in progress" if your'e already working on it).
