### ISSUE TITLE
Map data from Open Forest to FPFS

### ISSUE THREAD

**Issue by mwreiss** [USDAForestService/USFS-timber-permitting#195]
**Background**

This should follow on from the data flow modeling work in #145. We need to now map the data being collected by Open Forest into the data needed by NRM-TIM and FPFS. All of the relevant information appears to be in the comments on #145, so that seems like a good place to start from!  Reference #185 for the TIM mapping

**Acceptance criteria** 
- [x] We know which Open Forest fields go to FPFS and what they are called on the FPFS side
- [x] We know about any fields required by FPFS that are not included in Open Forest

**Tasks**
- [x] Map the data collected by Open Forest to the fields required by FPFS
- [x] Record any FPFS fields that are not captured by Open Forest

**Definition of done**
- [x] We have maps of data from Open Forest to external systems!
- [x] We have a list of missing data so that we can decide what to do about them.
- [ ] PO Approval

**Comment by mwreiss** [comment]
@mgwalker @bboddiger I created a new issue to split out FPFS mapping.  #185 is the TIM mapping.
