### ISSUE TITLE
MVP Data Storage

### ISSUE THREAD

**Issue by csstarling** [USDAForestService/USFS-timber-permitting#197]
**Background**

While SORN is being developed, research storage location for PII related to MVP. 

**Acceptance criteria** 
- [x] Know where we can store PII
- [x] Trade off's are documented and understood 
- [x] Make a determination of where the data will be stored
- [x] Ensure users requiring access to data is able to access the data

**Tasks**
- [x] Document trade off's for data storage options
- [x] Make a recommendation on where to store data
- [ ] Gain PO approval of recommendation
- [ ] Gain Security authorization

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by mwreiss** [comment]
Document drafted to address:

[MVP Data Storage.docx](https://github.com/USDAForestService/USFS-timber-permitting/files/5561105/MVP.Data.Storage.docx)

@carlsonem  started a doc to address this issue.

**Comment by mwreiss** [comment]
Need PO approval, move to blocked
