### ISSUE TITLE
As a team member, I can learn about how design research is integrated into agile sprints

### ISSUE THREAD

**Issue by jstrothman** [USDAForestService/USFS-timber-permitting#199]
**Tasks**
In the [Open Forest wiki How we Work](https://github.com/USDAForestService/fs-open-forest/wiki/How-we-work) section, briefly describe how the team integrates design research into agile sprints, including information like:
- [x] Design hypothesis work sessions: what they are, who participates
- [x] Cadence of research (how frequently? once/sprint? semi-monthly?)
- [x] How we source participants
- [x] Timing for sourcing and inviting participants
- [x] Who from the team generally participates in sessions & research synthesis (including goals re inclusion of developers and FS team members)
- [x] How findings are shared
This could be similar to: How We Work > [2019 Open Forest Special Uses Sprint Research Process](https://github.com/USDAForestService/fs-open-forest/wiki/2019-Open-Forest-Special-Uses-Sprint-Research-Process)

In the Open Forest wiki user research section, start adding documentation of research, such as: https://github.com/USDAForestService/fs-open-forest/wiki/Usability-Research-Plan-%E2%80%93-Manage-User-Access-to-the-Admin-Feature

**Comment by aQuib** [comment]
Updated on wiki
