### ISSUE TITLE
Permit purchaser task flow

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#2]
**Background**
We've done enough initial research to sketch out a possible flow for permit purchasers to inform some mocks we want to bring with us to the field on our first research trip. 

**Acceptance criteria** 
- [x] Draws on existing research
- [x] Flexible format (like Mural)

**Tasks**
- [x] Sketch out as-is flow
- [x] Sketch out to-be flow

**Definition of done**
- [x]  Meets acceptance criteria.

**Comment by MelissaBraxton** [comment]
[User Screen Flows_Draft.pdf](https://github.com/18F/USFS-timber-permitting/files/3731041/User.Screen.Flows_Draft.pdf)

Here's a nice example!

**Comment by MelissaBraxton** [comment]
Christmas tree module service blueprint (created by FS contractor)
https://app.mural.co/t/gsa6/m/gsa6/1556304246045/9078126a0403e523b60577ef1a3da304df563a83

Rough sketch from early xmas tree development: https://app.mural.co/t/gsa6/m/gsa6/1513030891953/777098c6c7ca20de528e68f3dc78256732e677f9

It's blank, but we did create a framework for permitting flow here: 
https://app.mural.co/t/gsa6/m/gsa6/1561135937859/c5bc56efbc767d9dc04de2aa8142a8b6a3205d41

**Comment by cmajel** [comment]
@MelissaBraxton adding a link to the mural we created on the current task flow for permit purchasers and frontliners:

https://app.mural.co/t/gsa6/m/gsa6/1561135937859/c5bc56efbc767d9dc04de2aa8142a8b6a3205d41

**Comment by cmajel** [comment]
We have a proposed task flow for our initial prototypes 🎉  Can be viewed at the bottom of this mural. 

https://app.mural.co/t/gsa6/m/gsa6/1571674517069/a0143a1bc7c4481453a6eacd5f8dc037523b7e56

@MelissaBraxton can we mark this as done?

**Comment by MelissaBraxton** [comment]
Yep, LGTM!
