### ISSUE TITLE
Determine whether existing vendor contracts could cover next phase of work

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#20]
**Background**
While we scoped this E&I assuming a new vendor acquisition would be required to build out the first piece of a fuelwood permitting system, it's possible that FS might be able to pull together a team under existing vendor contracts, Maybe even using some of the same contractors who are working on Open Forest. We want to understand this possibility as soon as possible, since it has implications for what this team will deliver in this E&I. I.e., if they're not onboarding a new vendor contract, then they won't need an RFQ. 

**Acceptance criteria** 
- [x] We have a definitive Y/N answer on whether existing vendor contracts can be used for a next phase of work. 

**Tasks**
- [x] Melissa send email introducing Miatta and Zahid
- [x] Miatta gets and reviews existing contracts

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by Miatta18F** [comment]
Received the GSA GWAC (contract) that was used to award the existing FS award but not the actual FS award. Will follow-up with Zahid on 11/7/19 for FS award.

**Comment by Miatta18F** [comment]
Followed up with Zahid on 11/5 but received no response. Sent an email to the STARS GWAC team (the vehicle Forest Service used to issue their awards) to see if they could provide a copy of the award(s). Without a contract number, it may not be possible but it's worth an ask.

**Comment by MelissaBraxton** [comment]
Talked with Zahid on 11/19. He feels confident that we could help them hire additional resources to work on this under the existing awards. We will confirm during a follow up call on Friday, 11/22. We still have not seen the contracts though.

**Comment by MelissaBraxton** [comment]
Miatta and Mel met with the COR on 12/2. While we can use the existing contract, it's up close to its budget limit, so we may decide to work with the new tower model. Miatta to follow up with Zahid.
