### ISSUE TITLE
As a frontliner, I need a way to check how much wood a customer may have already purchased online, so that they don't go over their household limit. 

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#200]
**Background**
This is for frontliners in an office to be able to check if someone has reached their limit (in office and online sales) before they decide to sell them more. 

This is a stretch goal for the MVP. Initially prioritized as part of the second major release, but with what we've heard from seom frontliners re: the importance + the work we're already doing to create an MVP permittee data storage solution we'd like to be able to include it in the MVP if we can. 

**Acceptance criteria** 
- [ ] Frontliner is able to check combined purchases (online and in office) for a specific customer/or address? 
- [ ]  Frontliner is able to check combined purchases (online and in office) within a specified date range

**Tasks**
- [ ] Needs to be refined. 
- [ ] 

**Definition of done**
- [ ]  
- [ ]

**Comment by MelissaBraxton** [comment]
@csstarling  - A Q for you, We have this acceptance criteria: _Frontliner is able to check combined purchases (online and in office) for a specific customer/or address?_

Can you conform whether its important to look up by customer or address?

**Comment by csstarling** [comment]
@MelissaBraxton , Currently in TIM you can do both. It's dependent on why the information is being searched. Typically a frontliner searches using customer name or ID# for the purpose of issuing a permit. If the frontliner is checking household limits they might search the address to see how many permits have been issued to that address (household).
