### ISSUE TITLE
Write up topline on pilot learnings to date

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#203]
**Background**
We want to write up a topline report summarizing what we've learned through the pilot so far, to the end of informing additional modernization efforts.  

**Acceptance criteria** 
- [x] We've externalized our learnings to date
- [x] Topline is understandable in an easily shareable format

**Tasks**
- [x] Draft topline
- [x] Share with Beth for review
- [x] Address any feedback 
- [x] Share with sponsor team

**Definition of done**
- [ ]  PM approval

**Comment by MelissaBraxton** [comment]
@bboddiger  - When you can, take a look at the topline and share any feedback.

**Comment by bboddiger** [comment]
@MelissaBraxton --Emailed back, with some suggestions/comments.

**Comment by MelissaBraxton** [comment]
Great! I'll address your comments and send a revised version today.

**Comment by MelissaBraxton** [comment]
Awaiting PM approval on revised draft.
