### ISSUE TITLE
Development: Implement Login.gov

### ISSUE THREAD

**Issue by carlsonem** [USDAForestService/USFS-timber-permitting#205]
**Background**
_What should we consider when addressing this issue?_

**Acceptance criteria** 
- [ ] A member of the public can login to the Open Forest system via. login.gov
- [ ] After a member pf the public login to login.gov, the user is redirect back to Open Forest

**Tasks**
- [ ] Develop code to connect the button from the Open Forest platform directs a user to login.gov
- [ ] Integrate login.gov setup that was developed for Special Use
- [ ] Setup correct return URL to match for firewood, as opposed to special use

**Definition of done**
- [ ] Design Review
- [ ] User Tested
- [ ] Code Review
- [ ] PO Approved

**Comment by carlsonem** [comment]
Review acceptance criteria from #110

**Comment by carlsonem** [comment]
@mtlaney Can this be closed out?

**Comment by mtlaney** [comment]
yep, moved it over to ready for main
