### ISSUE TITLE
As a frontliner, I need documentation on how to use the system and how to troubleshoot issues so that I can help the public with their Qs. 

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#206]
**Background**
This issue covers user documentation for frontliners to help them help members of the public. Frontliners anticipate getting calls from users seeking help and want to have troubleshooting tips handy.

**Acceptance criteria** 
- [x] Documentation addresses FAQs about the public's experience
- [x] Documentation is printer friendly and scanable in a printed format
~~- [ ] Pilot forest POCs have documentation that they understand~~

**Tasks**
- [x] Adapt user documentation to frontliner audience (#177)
- [x] Create documentation in a print friendly format
~~- [ ] Share with pilot forest POCs for review~~
~~- [ ] Refine based on POC feedback~~
- [ ] PO approved
~~- [ ] Share with pilot forest POCs for printing and distribution~~

**Definition of done**
- [ ]  Meets acceptance criteria

**Comment by Rebekah-Hernandez** [comment]
Here is the frontline staff documentation: https://usfs.app.box.com/file/751994881980

**Comment by Dmac26** [comment]
@Rebekah-Hernandez - Looks good to me! I'd just say we need to remember to check the links once the site is live on Prod.

**Comment by Dmac26** [comment]
@bboddiger @carlsonem - Hey Beth and Eric, if would be one of you two who would need to approve Rebekah's Front-line Guide for Firewood Permits correct? I have reviewed it for any grammatical and/spelling errors and it looks good to me.
