### ISSUE TITLE
As a frontliner, I need documentation on how to use Open Forest admin features // access online permit sales data so that I can troubleshoot issues I run into

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#207]
**Background**
This issue covers user documentation for frontliners to help them understand how to access the admin features and/ sales data, how to use the features, and how to trouble shoot issues. This is separate from #206, which is focused on helping frontliners help the public who call or come in w/ Qs. 

**Acceptance criteria**
- [ ] Documentation explains how to access and use the system
- [ ] Documentation addresses FAQs about frontliners' experience
- [ ] Documentation tells frontliners where they can go for more help
- [ ] Documentation is printer friendly and scanable in a printed format
- [ ] Pilot forest POCs have documentation that they understand

**Tasks**
- [ ]  Review any frontliner documentation from Open Forest Christmas trees and special uses and see what can be repurposed
- [ ]  Create new documentation in a print friendly format
- [ ]  Share with pilot forest POCs for review
- [ ]  Refine based on POC feedback
- [ ]  PO approved
- [ ]  Share with pilot forest POCs for printing and distribution

**Definition of done**
- [ ]  Meets acceptance criteria
