### ISSUE TITLE
As an LEO, I need documentation on how to understand the online permit and tags and how to get online permit sales information so that I can enforce permits sold online. 

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#208]
**Background**
This issue covers user documentation for LEOs. There are two key types of documentation that LEOs will need: (1) How to read the load tags and permits sold online, and (2) how to access and use any admin features. 

**Acceptance criteria**
- [ ] Documentation explains how to access and use the system
- [ ] Documentation addresses FAQs about LEO experience, including how to recognize a valid load tag
- [ ] Documentation includes images of the load tag specific to their forest in the current year 
- [ ] Documentation tells LEO where they can go for more help
- [ ] Documentation is printer friendly and scanable in a printed format
- [ ] Pilot forest POCs and LEOs have documentation that they understand

**Tasks**
- [ ]  Review documentation from #206 and see what can be repurposed
- [ ]  Create new documentation in a print friendly format
- [ ]  Share with pilot forest POCs for review
- [ ]  Refine based on POC feedback
- [ ]  PO approved
- [ ]  Share with pilot forest POCs for printing and distribution

**Definition of done**
- [ ]  Meets acceptance criteria
