### ISSUE TITLE
Minimum/maximum cord display and error message change: As a permit purchaser, I need to have the minim and maximum number for cords I'm allowed to purchase clearly displayed so that I know my limitations before beginning the purchasing process.

### ISSUE THREAD

**Issue by Dmac26** [USDAForestService/USFS-timber-permitting#209]
**Background**
Users should see a message on the "buy a permit" page that informs them of the range of cords they are allowed to purchase. Additionally, if the use inputs a cord amount that is above or below the set range, they should see an error message that properly informs them of the violation.

Below is an example of the desired language per @jstrothman 

![image.png](https://images.zenhubusercontent.com/5d93a896a615ef000109902d/45a898f0-a1fa-41cb-8eef-22bcd2597392)

**Acceptance criteria** 
- [x] Users can see a hint message that clearly delineates the range of cord amounts they are allowed to purchase
- [x] Users need to see an error message that clearly informs them of the proper range if they have violated it with their input

**Tasks**
- [x] Update hint language to match the requested change
- [x] Update the error message to match the requested change
- [ ] Validation of acceptance criteria completed
- [x] Code review
- [x] Design review
- [ ] PO Approved

**Definition of done**
- [x] Pull requests meet technical definition of done.

**Comment by Dmac26** [comment]
@MelissaBraxton and @jstrothman - I just wanted to give both of you an update before I head out for the day. I completed the language updates you requested and opened a Pull Request on this issue. It was pretty straightforward so I imagine I should be able to push this up tomorrow morning once one of the other Devs give the PR a thumbs up.

I'm posting the PR below here:

https://github.com/USDAForestService/fs-open-forest-platform/pull/1493

**Comment by Dmac26** [comment]
@MelissaBraxton and @jstrothman - Alrighty, this has now been merged up to the dev branch. It should be viewable within the next 20-30 min (current time: 9:00AM CST).

**Comment by jstrothman** [comment]
Looks great. Thank you @Dmac26

**Comment by jstrothman** [comment]
@Dmac26 Once this is on staging, could you move it to Awaiting Acceptance and assign it to @bboddiger ?

**Comment by Dmac26** [comment]
@jstrothman - Will do! Thanks for taking a look at it.
