### ISSUE TITLE
Bug: Forest landing pages display extra words to the right of the 'Buy permit' button: "Print PDFEmail PDF"

### ISSUE THREAD

**Issue by jstrothman** [USDAForestService/USFS-timber-permitting#213]
**Background**
On forest landing pages, e.g. https://open-forest-staging.app.cloud.gov/firewood/forests/flathead#season-dates
the page displays extra words to the right of the 'Buy permit' button: "Print PDFEmail PDF"

![Screen Shot 2020-10-13 at 5.14.29 PM.png](https://images.zenhubusercontent.com/5f330d1ed55eab42a58f1ec7/72777620-8144-4f5d-8500-64f542cd8e7f)

**Acceptance criteria** 
- [ ] The words "Print PDFEmail PDF" no longer display on the forest landing pages

**Tasks**
- [ ] Stop words from displaying
- [ ] Code review
- [ ] Design review
- [ ] PO Approved

**Definition of done**
- [ ]  The words "Print PDFEmail PDF" no longer display on the forest landing pages

**Comment by Dmac26** [comment]
@mtlaney or @jstrothman This seems to have been fixed somewhere along the way. Can we move this to awaiting acceptance or delete the card.

![image.png](https://images.zenhubusercontent.com/5d93a896a615ef000109902d/ede956a6-6c0f-4d0f-ac5c-bc7fe855a4b4)
