### ISSUE TITLE
Fix swagger to read correct https requests

### ISSUE THREAD

**Issue by mtlaney** [USDAForestService/USFS-timber-permitting#216]
**Background**
Currently swagger is hitting http with a failed to fetch response, these need to be updated to HTTPS in order to successfully retrieve DB data

**Acceptance criteria** 
- [x] http is changed to https
- [x] swagger can successfully display data

**Tasks**
- [x] change swagger scheme to https

**Definition of done**
- [x]  swagger is working in dev and staging
- [ ] PO approved
- [x] Code reviewed by someone other than the original author

**Comment by mtlaney** [comment]
@Dmac26 @briandavidson can you guys test this when you get a chance.

You can hit [https://fs-intake-api-staging.app.cloud.gov/docs/api/#/forests/get_fsforests](url) and execute, you should see the curl as HTTPS and get date back
