### ISSUE TITLE
NRM Complete GET 200 Response

### ISSUE THREAD

**Issue by mtlaney** [USDAForestService/USFS-timber-permitting#217]
## Notes
* Create an NRM get request at /nrm-service that will allow NRM to retrieve permit data. Once NRM retrieves the data successfully, we need to clear this table so they don't receive duplicative records. NRM Data will also need to be stored in a permanent table separately as to not lose any data. *

## Acceptance Criteria
- [x] NRM is able to successfully retrieve permits from /nrm-service
- [x] Service loads permit data upon successful permit transaction
- [x] All data mapping matches NRM schema
- [ ] Service will feed into a table that will be cleared after successful 200 transaction
- [ ] Service will also feed into a database that will not be cleared after successful 200 transaction
- [x] The load portion of the service will NOT fire off on an unsuccessful permit transaction, and will store no data

## Tasks
- [x] Build out Angular Service to utilize FormBuilder importing forest, nrm, and permit data
- [x] Wire up backend Model and Controller to new Angular Form Builder
- [ ] Create Table to house created but not yet retrieved permits
- [ ] Create function to clear above table once successful 200 transaction has taken place
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
