### ISSUE TITLE
As a permit buyer, I need to quickly learn the process for purchasing a permit and gathering wood

### ISSUE THREAD

**Issue by jstrothman** [USDAForestService/USFS-timber-permitting#219]
**Background**
The forest landing pages and the 2nd page of the permit purchase workflow have content from each forest, based on starter text. There were some readability improvements to be made, using plain language, and adjusting phrasing based on prior usability reviews, e.g. 'collecting' and 'gathering' instead of 'harvesting'. The attached Word docs have track changes turned on to make suggested edits recognizable 
[forest-buy-pages-edits.docx](https://github.com/USDAForestService/USFS-timber-permitting/files/5484266/forest-buy-pages-edits.docx)
[forest-landing-pages-edits.docx](https://github.com/USDAForestService/USFS-timber-permitting/files/5484267/forest-landing-pages-edits.docx)

**Acceptance criteria** 
- [ ] Changes in attached Word docs have been made

**Tasks**
- [ ] Make changes based on attached Word documents
- [ ] Send staging links to forest contacts for review of content

**Definition of done**
- [ ] Design review
- [ ] PO approval
