### ISSUE TITLE
Make a Determination if GP wants to integrate huckleberry/mushroom free permit into Open Forest platform

### ISSUE THREAD

**Issue by carlsonem** [USDAForestService/USFS-timber-permitting#220]
**Background**

Contact the GP forest and make a determination if they would like to incorporate huckleberry/mushroom free permit into Open Forest platform

**Acceptance criteria** 
- [ ] A yes/no decision is made on if GP huckleberry/mushroom permits should be added to OF platform

**Tasks**
- [ ] Contact GP and make a determination if GP should be integrated into GP
- [ ] Identify a PO from GP for the integration process.
- [ ] Get approval from Brian to integrate GP into Open Forest, if desire of forest

**Comment by carlsonem** [comment]
@smahmudFS would you be able to reach out and see if they are interested in migrating the platform to Open Forest
