### ISSUE TITLE
Make a discovery plan to determine what permit types are good candidates for the Open Forest platform

### ISSUE THREAD

**Issue by carlsonem** [USDAForestService/USFS-timber-permitting#221]
**Background**

To help support executives in the long-term vision of the Open Forest platform, a discovery plan is needed to help evaluate which permit types by the National Forest would be good candidates for the Open Forest platform.

**Acceptance criteria** 
- [x] A discovery plan is developed for identifying permits that would be good candidates for the Open Forest platform

**Tasks**
- [x] Identify the scope of the project (with PO, PM, UX)
- [x] Formulate research plan (discovery plan)
- [x]  Develop matrix evaluating user needs with platform capabilities
- [x] Polish and refine matrix platform evaluation matrix based on feedback.
- [x] Schedule meeting to review discovery research plan.
- [x] Obtain approval from Brian

**Definition of done**
- [x]   Presentation of Research Plan

**Comment by mwreiss** [comment]
Completed 12-14
