### ISSUE TITLE
Upgrade OF Platform to latest version of Angular

### ISSUE THREAD

**Issue by carlsonem** [USDAForestService/USFS-timber-permitting#222]
**Background**
Upgrade OF Platform to latest version of Angular

**Acceptance criteria** 
- [ ] OF platform is upgraded to latest version of Angular

**Tasks**
- [ ] Upgrade OF platform to latest version of Angular
- [ ] Conduct testing to ensure upgrade didn't break any of the existing code

**Definition of done**
- [ ]  
- [ ]
