### ISSUE TITLE
As Firewood  Permit Purchaser, I would like a the "proceed to checkout" button to be disabled and/or grayed out after I have already purchased a permit

### ISSUE THREAD

**Issue by Dmac26** [USDAForestService/USFS-timber-permitting#223]
## Notes
When a user submits payment for a firewood permit, there is a time lag while their permit is being processed. Currently, users can inadvertently purchase a duplicate permit during that time. In order to prevent duplicates and confusion in general, we should disable the "proceed to checkout" button while permits are being processed. Perhaps the button should be grayed out and a loading spinner displayed.

## Tasks
- [ ] Determine tasks necessary to complete this card
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
