### ISSUE TITLE
As a Firewood Permit Purchaser, I would like the total_cost of my permit to be accurately logged and displayed so that I can prove my purchase if necessary 

### ISSUE THREAD

**Issue by Dmac26** [USDAForestService/USFS-timber-permitting#224]
## Notes
Currently, the total_cost column of the database is being populated with the number of cords a user selects instead of the cost. This bug needs to be fixed so that pay the proper amount, while at the same time have sufficient proof that they are being permitted to gather X number of cords.

## Tasks
- [x] Determine tasks necessary to complete this card
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup
- [ ] Usability tested

**Comment by briandavidson** [comment]
Now that we have all the required data fields and staging is up and running again this got taken care of as it was part of the follow up work I'd been waiting to do.

@carlsonem I'm not sure if we still want to run this through the zenhub phases or just close it out.

cc @Dmac26
