### ISSUE TITLE
Add the `'forestCode'` attribute back into the forests.es6 page

### ISSUE THREAD

**Issue by Dmac26** [USDAForestService/USFS-timber-permitting#225]
## Notes
At some point the `'forestCode'` attribute was inadvertently removed from `forests.es6`. It needs to be added back in.

## Tasks
- [ ] Add `'foresCode'` attribute back into `forest.es6` on line 20
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
