### ISSUE TITLE
Write up topline summary report from field research

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#23]
**Background**
We want to externalize all that we learned in over our three days in the field last week in a shareable format that we can refer back to. 

**Acceptance criteria** 
- [x] We have an understandable shareable document that captures what we learned at a high level

**Tasks**
- [x] Review field notes
- [x] Identify high-level buckets
- [x] Summarize observations 

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
This may be a useful example
https://docs.google.com/document/d/1OhNnN5AkU3ToB4911vpa4RIp64H8mQFcHyDz7qihGL0/edit

**Comment by MelissaBraxton** [comment]
Draft is [here. ](https://docs.google.com/document/d/10vRxdRZ47lHz-XDguwygWlwZKQ0l9LP3lMt9b2zdoZ8/edit#heading=h.wrajb8kr9r53)
