### ISSUE TITLE
Archive field trip documentation

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#24]
**Background**
We want to make sure we can easily find and refer back to documentation of our field visit 10/30-11/2/19. 

**Acceptance criteria** 
- [X] Everyone on the team knows where to find documentation 
- [X] All documentation is in shared drive

**Tasks**
- [x] Mark uploads photos
- [x] Mel uploads photos
- [X] Christine uploads photos
- [X] All observation notes logged
- [X] All hand written notes are digitized (transcribed or photographed) and in drive

**Definition of done**
- [X]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
Field trip 1 folder is [here](https://drive.google.com/drive/folders/1ZYdvCaa3X8umsR5AHGRZdmYO20MSWYcO):
