### ISSUE TITLE
Plan LEO field research to observe xmas tree enforcement

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#27]
**Background**
In our first round of field research we explored the potential impact of moving away from tagging the load. We want to better understand  issues for LEOs enforcing that approach. We have window of opportunity to research how this is working for the Open Forest Christmas tree pilot program in Region 6. Results of this research will further inform our understanding of a firewood permit solution that is easily enforceable, as well as provide learnings for the Open Forest Christmas tree pilot. 

**Christmas tree season is short, so we are targeting the weekend of 12/6-12/8.**

**Acceptance criteria** 
- [x] Research plan is complete
- [x] Research is scheduled

**Tasks**
- [ ] Revisit design hypotheses
- [x] Reach out to LEO contacts to schedule
- [x] Determine who on the team will go
- [x] Articulate research questions
- [x] Draft research plan
- [ ] Share plan with team for their review (including Lisa M.)

**Definition of done**
- [x]  Meets acceptance criteria
