### ISSUE TITLE
Create high-level user stories - Field visit 1

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#30]
**Background**
We want to translate what we learned in our first field visit into user stories that the team can then prioritize for further research and to inform stories that will be prioritized as part of the vendor solicitation. 

**Acceptance criteria** 
- [x] User stories are written in this format: As a (user type), I need to (business need) so that (value to the user)

**Tasks**
- [x] Review research synthesis
- [x] Schedule story writing co-working session
- [x] Meet to review/refine stories

**Definition of done**
- [x]  PO approved

**Comment by MelissaBraxton** [comment]
Drafted stories here and started putting them on the board: https://docs.google.com/document/d/12Vwp7FloYI_xucsaWZYmLJRA7ahEybrVqewxxrtPlbk/edit
Will schedule a groomking mtg to refine them the week of 11/25.

**Comment by MelissaBraxton** [comment]
Stories were reviewed by Roxie and Beth on 12/4. Mtg to review with Kris scheduled for 12/9.

**Comment by MelissaBraxton** [comment]
MVP scoping Mural here: https://app.mural.co/invitation/mural/gsa6/1576007263706?sender=melissabraxton2796&key=9e630b62-39bc-4d17-8b37-118da9d67cd9
