### ISSUE TITLE
Draft product vision specific to fuelwood permitting

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#32]
**Background**
Now that we've learned a great deal more about permitting, we need to revisit our broad product vision (from the Path Analysis) and craft a new vision statement to bring focus to our work going forward. It will be important to have a fuelwood-specific vision statement before we prioritize user stories for the vendor. 

**Acceptance criteria** 
- [x] Vision statement is jargon free // plain language // understandable to a broad audience
- [x] Vision concisely tells who we are helping, why they need help, and how we are helping

**Tasks**
- [x] Everyone on the team reviews research to date
- [X] User needs statements from field visit 1 have been drafted
- [X] Schedule remote product visioning workshop for product team and FS product staff
- [x] Create Mural board or place to conduct visioning workshop
- [x] Conduct visioning workshop
- [x] Refine vision

**Definition of done**
- [x] PO approved
- [x] PM approved

**Comment by MelissaBraxton** [comment]
Awaiting approval from PM and PO. Will discuss next week.

**Comment by rebert25** [comment]
Hey Beth & Kris.  This looks good to me.  Can you take a look?

**Comment by MelissaBraxton** [comment]
**Firewood permitting vision:**
We are building a convenient, interactive online service to give the public the information they need to plan safe trips to harvest firewood and get enforceable firewood permits without having to travel to a district office.
