### ISSUE TITLE
Investigate the experience of tagging / e-tags for hunting 

### ISSUE THREAD

**Issue by cmajel** [USDAForestService/USFS-timber-permitting#34]
We learned during our field visit that hunters have a similar tag experience when hunting and also face the same technical and environmental limitations. From initial conversations and searching, we know that that:
* Hunters are often required to to tag their animal after hunting
* Some states provide physical tags, and others allow hunters to "create their own" out of common materials.
* Many states have "harvest reporting" where hunters must report back what they hunted / collected from public lands.
* When creating their own tag, states often require a confirmation number be included to validate the tag. This confirmation number can sometimes be delivered online or via an app (like the ODFW example).

This issue is to scope initial research to learn more about how hunting agencies have approached this problem.

**Acceptance criteria**
- [ ] Initial research questions are defined
- [x] A home is created where learnings can be shared
  Inspiration mural is here: https://app.mural.co/t/gsa6/m/gsa6/1574092854840/980b5325497ea7d055e4d489bcea35d0f07be90e

**Tasks**
- [ ] Explore our options for talking with hunters or wildlife agencies directly about their tagging process

**Definition of done**
- [ ] PO approved
- [ ] Meets acceptance criteria

**Comment by cmajel** [comment]
@MelissaBraxton @tram are you thinking of talking with hunters on your next field trip? If so, maybe there's some crossover and we should move this up.
