### ISSUE TITLE
Meet with Zahid to explore technical issues

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#37]
**Background**
We have a number of questions for Zahid and others in the CIO shop before we can begin some of the targeted engineering experiments we'll need to do to de-risk technical barriers to implementation. 

**Acceptance criteria** 
- [x] We've met with Zahid
- [x] We've documented any follow up actions/next steps

**Tasks**
- [x] Kelsey and Melissa revisit tech issue sheet
- [X] Schedule mtg with Zahid
- [x] Draft Qs for Zahid
- [x] Conduct mtg

**Definition of done**
- [x]  Acceptance criteria met

**Comment by MelissaBraxton** [comment]
Meeting with Zahid scheduled for 11/19.

**Comment by MelissaBraxton** [comment]
Follow up actions needed:

- [ ] Email Zahid to connect with person working on TIM API
- [ ] Find out from cloud.gov whether there is room under existing licensing agreement to spin up test environment
 - [ ] Schedule demo with John Lerner and Shadat to see current CI/CD pipeline.
