### ISSUE TITLE
Revisit design hypotheses

### ISSUE THREAD

**Issue by tram** [USDAForestService/USFS-timber-permitting#38]
**Background**
After research synthesis, we'll want to take another look at our design hypotheses.

**Acceptance criteria** 
- [x] Design hypotheses accurately reflect our ideas to improve the experience

**Tasks**
- [x] Complete research synthesis
- [x] Examine each design hypothesis and edit or remove to match our current thinking
- [x] Add any new hypotheses

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by tram** [comment]
Hypothesis doc: https://docs.google.com/document/d/1EkWTwVXKEfnu3Ohwh47c9qKDkgZ-0yRJDPQkI3JWOME
