### ISSUE TITLE
Ideate on task flows

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#39]
**Background**
We want to make sure we evolve our to-be task flow ideas while field visit 1 learnings are still fresh. 

**Acceptance criteria** 
- [x] We've had our task flow co-working session

**Tasks**
- [x] Schedule task flow co-working session
- [x] Meet
- [x] Document ideas in shared doc or Mural
https://app.mural.co/t/gsa6/m/gsa6/1573568432047/e025f623964695b564f93e6e29575fa7c2583a15

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by cmajel** [comment]
Set a time for us to do a brain dump on Thursday. Mural here:

https://app.mural.co/t/gsa6/m/gsa6/1573568432047/e025f623964695b564f93e6e29575fa7c2583a15

**Comment by cmajel** [comment]
@MelissaBraxton I think this is good to close. We had an initial taskflow meeting to get ideas down which was our first goal. I suspect we'll return to this next sprint to flesh out further.

https://app.mural.co/t/gsa6/m/gsa6/1573568432047/e025f623964695b564f93e6e29575fa7c2583a15
