### ISSUE TITLE
Finish setting up GitHub repo

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#4]
**Background**
_What should we consider when addressing this issue?_

**Acceptance criteria** 
- [x] All links are working

**Tasks**
- [x] Upload deliverables from Path Analysis
- [x] Link to ai. assets from Christmas tree module
- [x] Christine reviews
- [x] Mark reviews

**Definition of done**
- [x]  The repo meets the team's needs

**Comment by MelissaBraxton** [comment]
@tram and @cmajel - When you get a chance, take a tour of the repo and let me know if there's anything else you think we need to get going!
