### ISSUE TITLE
Determine how we can spin up a test environment. 

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#40]
**Background**
We want to spin up a test environment. On a call with Aaron Burk, he believes there may be room on their existing cloud.gov agreement to host this, but we need to check. If this is not possible, then we need to come up with an alternative. 

**Acceptance criteria** 
- [x] We have a feasible plan for setting up and hosting our test environment that will enable us to try out the code pipeline.

**Tasks**
- [x] Check with cloud.gov on whether there is room to spin up duplicate environment under OF agreement.
- [x] If not, identify alternative solution 

**Definition of done**
- [x]  Acceptance criteria have been met.

**Comment by MelissaBraxton** [comment]
Still waiting on confirmation re: how much room there is on cloud.gov agreement, but in the meantime we can begin spinning up a Sandbox with the help of the FS org manager. @kfoley-18F  - anything to add here?

**Comment by kfoley-18F** [comment]
Only that the Sandbox needs to be able to allow for integration with data warehouse and TIM eventually. That might require ATT or other security/approvals, so having it run within FS administrative footprint will make it easier to get there.

**Comment by MelissaBraxton** [comment]
We have confirmation from Jessyka at cloud.gov that we can use the existing agreement. I've created issue #45 to create the environment. 
@kfoley-18F Is there anything else we need to do to move this to done?
