### ISSUE TITLE
See demo of OF CI/CD tools

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#41]
**Background**
We want to be familiar with the changes that have been made to the CI/CD tooling since 18F last worked on the Open Forest platform. 

**Acceptance criteria** 
- [ ] We have received the demo
- [ ] We have documented any follow up actions

**Tasks**
- [ ] Schedule demo from John Lerner and Shadat
- [ ] Attend demo

**Definition of done**
- [ ]  Acceptance criteria met

**Comment by mgwalker** [comment]
I got this demo a while back.
