### ISSUE TITLE
 Understand data TIM/CDW workflow/migration 

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#44]
**Background**
Integration points and what specific pieces of data have to migrate (e.g. FPFS)?

**Acceptance criteria** 
- [ ] We've identified follow up actions and documented them as new issues. 

**Tasks**
- [x] Email Beth to find out who can help us understand data in TIM that may need to migrate and what the path might look like. (Melissa)
- [x] Schedule meeting w/ Beth, Ming, Clint, and Mellisa
 - [x] 18F creates agenda and Qs doc to share w/ FS
- [x] Investigate APIs that connect with the CDW/EDW and/or current CDW/TIM integration
- [ ] Evaluate the suitability of the CDW/EDW as a long term home for permitting data and identify an alternative if need be
~- [ ] Determine whether an SLA will be needed to integrate with the CDW~

**Definition of done**
- [ ]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
Draft agenda for tech call: https://docs.google.com/document/d/1oVfpTRA-2IogCjTAi_OMQYixoxfDFYXxxuVecCfacs4/edit#

**Comment by MelissaBraxton** [comment]
Follow up actions:
- [ ] understand the data flows and map out what data needs to go where so that we can understand what aspects of a system of record need to be tracked
 - [ ] Get interface control doc from Teresa
- [ ] Email Markus to ask about getting access to CDW test environment and EDW development environment (Melissa)
 - [ ] Ask Marcus about scheduling a call/demo with someone who is building services off of EDW
- [ ] Talk with Open Forest team about OF becoming a system of record for permitting data. Find out who in cybersecurity we need to partner with.

**Comment by MelissaBraxton** [comment]
Draft diagram: https://docs.google.com/drawings/d/1J37DjKdiM7-zDESnxV8SQNeCIaUmu0BaQjp6DvawRC8/edit

**Comment by ctro** [comment]
Meeting 12/17 with TIM and OF folks to talk lower-level about approach.
Notes: https://docs.google.com/document/d/1fueeDUH632L4subvSWQrTF8rdPyoUL6d5UfJyoEAvHU/edit

High level:
1) We choose to work with FPFS and its APIs first
2) The team prefers more of a direct “dive into the deep end of the pool” strategy to doing the encapsulation work
