### ISSUE TITLE
Create cloud.gov sandbox

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#45]
**Background**
_What should we consider when addressing this issue?_

**Acceptance criteria** 
- [ ] We have a test environment within the FS footprint. 
- [ ] We have a plan for how 18F folks can access it (whether directly or with help from FS SRE or others). 

**Tasks**
- [ ] Spin up cloud.gov sandbox
- [ ] Ensure that someone on the 18F side has admin access to the USDA GitHub
- [ ] Ensure Beth has admin access to USDA GitHub 
- [ ] Decide when and how to move task tracking to USDA repo
- [ ] Ensure 18F folks have access to USDA repo in time to not block work
- [ ] Check w/ Dave Corwin

**Definition of done**
- [ ]  Meets acceptance criteria
