### ISSUE TITLE
Conduct field research to observe xmas tree enforcement

### ISSUE THREAD

**Issue by tram** [USDAForestService/USFS-timber-permitting#46]
**Background**
Field focusing on LEO fuelwood and Xmas tree experience in R6 during Xmas tree season.

**Acceptance criteria** 
- [x] Research has been done, we've returned from the forest safely

**Tasks**
- [x] Interview and observe frontliners, LEOs, and members of the public.

**Definition of done**
- [x] Meets acceptance criteria
