### ISSUE TITLE
Write topline from second field visit

### ISSUE THREAD

**Issue by tram** [USDAForestService/USFS-timber-permitting#47]
**Background**
We want to quickly externalize what we observe during our second field visit in a shareable format that we can refer back to.

**Acceptance criteria** 
- [x] We have an understandable shareable document that captures what we learned at a high level

**Tasks**
- [x] Review field notes
- [x] Identify high-level buckets
- [x] Mark summarizes observations
- [X] Mel summarizes observations

**Definition of done**
- [x] Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
Draft is here: https://docs.google.com/document/d/1bZmQOczExXEJYbe75os-mpe-xY93a6U6gZphzSjKkZU/edit#
