### ISSUE TITLE
Make a list of which forests do/don't require load tags

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#49]
**Background**
We know some states/forests etc. require tagging the load. We need to determine how big of an impact this might have on the design of the system and how it informs our prioritization for features that'll be included in the MVP (minimum viable product).

**Acceptance criteria** 
- [x] We have an inventory of the places that do/don't require load tags that has been validated/verified with FS staff

**Tasks**
- [x] Kris to reach out to regional resource specialists for copies of theft prevention plans
~- [ ] Review Forest theft prevention plans~
- [X] Create inventory in excel/sheets
~- [ ] For forests that don't have a theft prevention plan, reach out to state forestry to get the info.~
- [x] Look for comprehensive internal FS resource
~- [ ] Review prior identified FS webpages~

**Definition of done**
- [x]  Acceptance criteria met

**Comment by MelissaBraxton** [comment]
Does the region require a load tag?

- R1 - NO
- R2 - Yes
- R3 - Yes
- R4 - Yes
- R5 - Yes
- R6 - Yes
- R8 - No
- R9 - No
- R10 - No

**Comment by MelissaBraxton** [comment]
Sheet is here: https://docs.google.com/spreadsheets/d/1LdM8-_CiSSteyzNRm2gF0Hy5SaZVtyRaeRlVj_Lqezw/edit#gid=0
