### ISSUE TITLE
Summarize insights on permitting 

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#5]
**Background**
We should dive back into the research we did on the path analysis and pull out all insights on permitting to inform a user flow for initial prototypes. 

**Acceptance criteria** 
- [x] Summary of permitting insights is digestible and findable to folks who weren't directly involved in the research. 

**Tasks**
- [x] Review interview notes
- [x] Review workshop notes/photos
- [x] Jot down findings/insights relevant to permitting

**Definition of done**
- [x]  Acceptance criteria met

**Comment by MelissaBraxton** [comment]
[Here's the draft summary](https://docs.google.com/document/d/1vbqhSAVBTWfAUDGkDVd9Dsuz5Y_hrQOeS_brG6oCquU/edit#)
