### ISSUE TITLE
Draft strategy for how and where to pilot the product

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#50]
**Background**
_What should we consider when addressing this issue?_

**Acceptance criteria** 
- [x] Anyone on the team can find and access the strategy doc. 
- [x] We have a plan that lays out considerations for piloting the MVP 

**Tasks**
- [x] Mel and Beth to draft summary of what will change for them--what this will mean for frontliners, duration, etc. How much of their time it will take.
- [x] Inventory forests in these regions looking at these criteria (Christine to help)
- [X] Beth to reach out to Regions 1, 8 & 9 TIM coordinators.
- [x] Write pilot plan 
- [X] Circulate for the team to review
- [x] Publish to the GitHub wiki

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
Criteria for selecting pilot region/forests
- No load tags required
- Limited sale activity 
- No or high seasonal limit 
- Enthusiasm and buy-in from regional TIM coordinator and resource specialists, and regional forester, and forest supervisor, and regional Special Agent in Charge.

Beth to reach out to Regions 1, 8 & 9 TIM coordinators.

Mel and Beth to draft summary of what will change for them--what this will mean for frontliners, duration, etc. How much of their time it will take.

**Comment by MelissaBraxton** [comment]
Planning scratch pad: https://docs.google.com/document/d/1pRtkBPy6WSJELTI50QQg7G2YkykK3rVaLJXXj1IVjog/edit?usp=sharing

**Comment by MelissaBraxton** [comment]
@cmajel  - Here is the draft inventory sheet that you can help out with if/when you have time! https://docs.google.com/spreadsheets/d/1LdM8-_CiSSteyzNRm2gF0Hy5SaZVtyRaeRlVj_Lqezw/edit#gid=860697858

**Comment by MelissaBraxton** [comment]
Updated final task so that Beth and I can do it together to go through making updates to the wiki.
