### ISSUE TITLE
Refine transition plan/strategy

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#51]
**Background**
We need to make the work required to sustain the product and way of working after we're gone more explicit by defining what the work entails and reflecting it on the board.

**Acceptance criteria** 
- [x] Sustainment tasks/issues are on the product roadmap as needed
- [x] Sustainment tasks/issues are on the product board

**Tasks**
- [x] Conduct initial sustainment strategy brain dump
- [x] Write success scenarios
- [x] Write tasks that will help the team succeed those scenarios
- [x] Have team review
- [x] Create needed cards on the board and add "sustainment" label

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
Sustainment plan draft here: https://docs.google.com/document/d/1q8G_PR2DpOVP5uSSEa1rFKc-Z2I-hpJm720CiuFkdgk/edit
