### ISSUE TITLE
Onboard Clint Troxel to the project

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#52]
**Background**
Clint will be joining the team as the new engineering lead

**Acceptance criteria** 
- [x] Clint has necessary background and access to tools to feel confident beginning to work with the team. 

**Tasks**
- [x] Clint reviews relevant project material
- [x] Clint and Melissa have initial onboarding mtg
- [x] Clint added to GitHub team
- [x] Clint added to relevant Slack channels
- [x] Clint and Kelsey meet and do handoff

**Definition of done**
- [x]  Meets acceptance criteria
