### ISSUE TITLE
Recap our field visit in the project wiki

### ISSUE THREAD

**Issue by cmajel** [USDAForestService/USFS-timber-permitting#53]
**Background**
As a future team member, I want to be able to easily find what the team worked on so that I can access past research and don't waste time looking through slack/email. 

**Acceptance criteria** 
- [x] We have a page on the wiki that recaps our first field trip and includes links to relevant documents.
  - https://github.com/USDAForestService/USFS-timber-permitting/wiki/Field-trip-1:-Observing-frontliners-and-fuelwood-permit-purchasers-at-Mount-Hood

**Tasks**
- [x] Determine what documents we should link to
- [x] Write a draft, and share with the team for feedback

**Definition of done**
- [x]  Meets definition of done

**Comment by cmajel** [comment]
Starting this here. Will do a first pass then will ask the team for review:
https://github.com/18F/USFS-timber-permitting/wiki/Field-trip-1:-Observing-frontliners-and-fuelwood-permit-purchasers-at-Mount-Hood

**Comment by MelissaBraxton** [comment]
Looks great to me!
