### ISSUE TITLE
Prepare for client kick-off

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#6]
**Background**
We had a soft kick off on 10/15, but we'll want to formalize it next week. 

**Acceptance criteria** 
- [x] We're all aligned on what we want to get out of the KO 
- [x] We have a plan for how to get there

**Tasks**
- [x] Draft KO goals and agenda
- [x] Draft Deck
- [x] Mark reviews
- [x] Christine reviews

**Definition of done**
- [x] We have an agenda and deck for the KO that will get us the outcomes we desire that everyone has reviewed/approved.
