### ISSUE TITLE
Draft firewood permitting roadmap 

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#60]
**Background**
_What should we consider when addressing this issue?_

**Acceptance criteria** 
- [x] Roadmap maps epics to strategic vision 
- [x] Roadmap is accessible in an easily shareable/editable format

**Tasks**
- [x] Schedule roadmapping mtg
- [x]  Prep roadmapping canvas and activities
- [x] Conduct collaborative roadmapping session w/ FS product folks
- [x] Document outcomes

**Definition of done**
- [x]  PO/PM approved

**Comment by MelissaBraxton** [comment]
Draft is here: https://app.mural.co/t/gsa6/m/gsa6/1574795838733/88a9a64a16c1c75595f59c2227cbcc6534caf34a

**Comment by MelissaBraxton** [comment]
Will use co-working time on Thursday, 12/19

**Comment by MelissaBraxton** [comment]
High level roadmap in [wiki](https://github.com/USDAForestService/USFS-timber-permitting/wiki/Product-roadmap)
