### ISSUE TITLE
Draft future-state task flow for MVP

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#61]
**Background**
We want to capture our thinking on what the MVP service will look like in an easily readable format. 

**Acceptance criteria** 
- [x] Task flow is in an easily accessible format 
- [x] Captures the current thinking on what the MVP experience will entail. 

**Tasks**
- [x] Create to-be task flow for MVP
  - [Task flow mural](https://app.mural.co/t/gsa6/m/gsa6/1575559419757/0dd336821e3f9ef0a2f604e725b157ce30d777ce)
  - [Key research questions for MVP](https://docs.google.com/document/d/1FCSKKF9GBlWx7-SVowEHt-5T_FLA012Ng1T5PVjiySo/edit#)
  - [MVP Invision prototype](https://gsa.invisionapp.com/share/R3VA86RNPWK#/397192435_FS_MVP1--1-_Find_A_Forest) (comments disabled)
- [x] Share with team for review
  - Reviewed at Tues 12/10 and Thurs 12/12 coworking sessions

**Definition of done**
- [x]  PO approved

**Comment by cmajel** [comment]
Here is the task flow we developed based on the top voted user stories:
[Task flow mural](https://app.mural.co/t/gsa6/m/gsa6/1575559419757/0dd336821e3f9ef0a2f604e725b157ce30d777ce)

We discussed this at our 12/10 coworking session, and started translating this into a clickable prototype this week. 

@MelissaBraxton since we've gotten feedback the FS team on this in our coworking sessions, I'm going to count this as approved. Feel free to reopen if needed.
