### ISSUE TITLE
Recruit participants for usability testing

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#62]
**Background**
We want to usability test prototypes before the end of the year, targetting the week of 12/16. 

**Acceptance criteria** 
- [ ] We have recruited 5-10 test participants who meet our inclusion criteria

**Tasks**
- [x] Define inclusion criteria
- [x] Draft Google form for frontliners to use
- [x] Send form to Roxie to share w/ other frontliners 
- [x] Meet with Ryan Wold and Lauren Ancona in GSA's Office of Customer Experience to see about setting up online intercept
- [x] Draft online intercept content
- [x] Send code snippet to Rob at FS
- [X] Add our name to user testing.com queue
- [x] Find out whether we can run our test in the needed timeframe  
- [x] Schedule participants
- [x] Reach out to 18F folks via Slack to schedule interviews

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
Archived #12 since it's now included here.

**Comment by MelissaBraxton** [comment]
Meeting with customer exp folks scheduled for 12/4.

**Comment by MelissaBraxton** [comment]
We recruited 7 people. 3 were no shows, so we were only able to include 4 people in the research this round.
