### ISSUE TITLE
Transfer project repo to USDA GitHub

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#63]
**Background**
In order for Forest service to sustain the project on their own, they'll need to be able to keep code and track project work in their own instance of GitHub. 

**Acceptance criteria** 
- [ ] All content from 18F repo is accessible to everyone on the project team in USDA's GitHub

**Tasks**
- [x] Meet with Dave Corwin to re: lessons learned from doing this in the OF transition
- [x] Set up 18F team with USDA GH access
- [x] Create new repo in USDA environment
- [x] Transfer repo
- [x] Add team members to the new USDA GH repo team

**Definition of done**
- [x]  Meets acceptance criteria
