### ISSUE TITLE
Write usability test plan

### ISSUE THREAD

**Issue by rebert25** [USDAForestService/USFS-timber-permitting#64]
**Background**
We are scheduling usability test for the end of next week to test early concepts.

**Acceptance criteria** 
- [x] We have a research plan that addresses us our research questions

**Tasks**
- [x] Review prototypes
- [x] Revisit design hypotheses
- [x] Write research plan
- [x] Share with team review

**Definition of done**
- [ ]  At least one other team member has reviewed and approved plan
