### ISSUE TITLE
Write up usability test results

### ISSUE THREAD

**Issue by bboddiger** [USDAForestService/USFS-timber-permitting#65]
**Background**
Ensure we've documented results of usability testing for all team members to access and read.

**Acceptance criteria** 
- [x] Anyone on team can easily access/read results.

**Tasks**
- [x] Write up research summaries.
- [x] Circulate for team to review.
- [x] Document findings as new user needs as needed
- [x] Publish on the project wiki.

**Definition of done**
- [ ]  Meets acceptance criteria.

**Comment by bboddiger** [comment]
@tram  Hi, if you could take a look at this before sprint planning and add any thoughts.

**Comment by cmajel** [comment]
I created a placeholder wiki page for this recap:
https://github.com/USDAForestService/USFS-timber-permitting/wiki/Usability-Test-1:-Online-permit-buying-flow-and-printable-load-tags

**Comment by MelissaBraxton** [comment]
@tram - This is looking good, but I think there are some insights that have Christine has included in annotations on the mocks. Can you make sure they're reflected here? Another option would be to add a note and a link to more detail in the annotated mocks, but I worry that folks at the sr level may not be as comfortable with the InVision format.

**Comment by tram** [comment]
@MelissaBraxton Added the insights from the mocks. If there's something else, let me know!
