### ISSUE TITLE
Draft technical recommendations and mitigations report

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#66]
**Background**
_What should we consider when addressing this issue?_

**Acceptance criteria** 
- [ ] Anyone on the team can find and access a report of technical recs and mitigations 

**Tasks**
- [ ] Draft report
- [ ] Draft proposed architecture diagram
- [ ] Circulate for the team to review
- [ ] Publish in GitHub repo

**Definition of done**
- [ ]  meets acceptance criteria
