### ISSUE TITLE
Organize prototypes for usability testing

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#67]
**Background**
_What should we consider when addressing this issue?_

**Acceptance criteria** 
- [x] Usability test facilitators can easily access prototypes to facilitate usability test sessions

**Tasks**
- [x] Prototype links / downloads are available to the 18F and FS team
  - [x] [ Link for participants (comments disabled) ](https://gsa.invisionapp.com/share/R3VA86RNPWK#/screens)
  - [x] [Annotated mockups, exported from Invision](https://github.com/USDAForestService/USFS-timber-permitting/blob/master/docs/design-deliverables/online-timber-permitting-ui/2019-12--mvp-usability-test/FS%20Timber%20MVP1--invision-export-with-annotations.pdf)
- [x] Prototype prompts are integrated with the research plan
- [x] Prototype is tested during a dry run of the usability test plan to verify that participants and researchers can navigate artifacts

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by cmajel** [comment]
Work on this started the week of 12/9 based on what was discussed in #61 

[Initial prototype screens](https://gsa.invisionapp.com/share/9SV8BOWA4Z6#/397431582_FS_MVP1--10-0Notes_On_What_Is_Needed_In_Printed_Permit)

After reviewing our[ key MVP research questions](https://docs.google.com/document/d/1FCSKKF9GBlWx7-SVowEHt-5T_FLA012Ng1T5PVjiySo/edit#) and walking through the prototype at Thurs 12/12 coworking, we're planning on making the following updates:
- [ ] Add load tag language in the following locations:
  - [ ] How to cut firewood page
  - [ ] Rules and regulations acceptance page
  - [ ] Confirmation / instructions page
- [ ] Create a prototype confirmation / instruction page that assumes a printable permit and load tag
- [ ] Remove online location lookup from MVP 

TBD
- [ ] How much of the login.gov flow do we include here? Is that a priority for this test?

**Comment by cmajel** [comment]
We had another good cowork session today on this. We decided to...

- [ ] Remove the first two screens to cut down on test length
- [ ] Map the `print documents` button on the confirmation page to a mock of the load tag

re: how much of the login.gov flow to test, we've decided to keep it exploratory and not show the entire flow in the interest of time. However, understanding what amount of sign up is tolerable to the average permit purchaser is something we'll need to dig into in the future.
