### ISSUE TITLE
Draft RFP

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#68]
**Background**
Whether we are planning to onboard vendors next month or later on next year, we want to draft documents that our partners can include in future solicitations to bring on a team to build out this system. 

**Acceptance criteria** 
- [ ] Anyone on the team can find and access draft RFP

**Tasks**
- [x] Finalize acquisition recommendations (Miatta)
- [x] Draft user stories for MVP (Mark and Melissa) 
- [x] Draft vision (Melissa)
- [x] Draft firewood-specific problem statement
- [x] Draft background
- [x] Draft objectives 
- [x] Draft QASP
- [ ] Circulate for team to review

**Definition of done**
- [ ]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
Let's consider where's the best place for this to live. Not sure if publishing it to the wiki will be best months in advance of it going live, if that ends up being the case.

**Comment by MelissaBraxton** [comment]
@Miatta18F  - Can you please weigh on on whether we should hold off putting draft RFQ material on public-facing GitHub?

**Comment by MelissaBraxton** [comment]
Draft is here: https://docs.google.com/document/d/1-6e55P10IirXyYfkAcB72a1f2ljF2rt34OqgKPCJ_M8/edit#heading=h.ifd2s59ussbm

**Comment by Miatta18F** [comment]
We could use GitHub if we did a full and open competition on IT 70. Since it looks like we're only going to DAITSS BPA holders we wouldn't post on GitHub.

**Comment by MelissaBraxton** [comment]
@Miatta18F  - I added to this and tagged you and @ctro in to try and fill in some blanks.
