### ISSUE TITLE
Audit GitHub for current information

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#69]
**Background**
By the end of the year, we want to make sure GitHub contains our current knowledge and understanding of the work so that anyone can quickly resume working after the pause in funding. 

**Acceptance criteria** 
- [x] current state of knowledge on the project is publicly available.

**Tasks**
- [x] Update wiki homepage to point certain disciplines to the right sections
- [x] Check that all research to date is documented in the wiki
  - [X] Field visit toplines
  - [x] [Service blueprint](https://github.com/USDAForestService/USFS-timber-permitting/wiki/Firewood-permit-service-blueprint,-current-state) (export as PDF)
- [x] [Known UX debt](https://github.com/USDAForestService/USFS-timber-permitting/wiki/Known-Design-debt): note the design loose ends (currently in `/docs/` repo)
- [X] Ensure that product vision is up-to-date
- [x] Ensure that high-level roadmap is accessible from the repo in some form
- [x] Ensure that high-level sustainment plan is accessible from the repo in some form
- [x] Ensure that high-level plan for piloting the system in production is accessible from the repo in some form
- [x] Ensure that team roles and working practices in the wiki are up-to-date
- [x] Ensure that mocks and wireframes are accessible from the repo in some form
  - [x] [Design deliverables](https://github.com/USDAForestService/USFS-timber-permitting/tree/master/docs/design-deliverables) with JPG exports and sketch resources for wireframes and design exploration. Also includes
  - [x] [Exported the invision prototype with annotations](https://github.com/USDAForestService/USFS-timber-permitting/blob/master/docs/design-deliverables/online-timber-permitting-ui/2019-12--mvp-usability-test/FS%20Timber%20MVP1--invision-export-with-annotations.pdf)
- [x] [Service blueprint exported and documented](https://github.com/USDAForestService/USFS-timber-permitting/wiki/Firewood-permit-service-blueprint,-current-state)
- [x] Ensure that timeline and deliverables page is up to date

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
- Discovery research report is not on deck until after this sprint.
- Pilot plan is blocked until we can meet with regional-level folks at each of the three candidate regions. Will post to the wiki once finalized.

**Comment by MelissaBraxton** [comment]
State of knowledge at the time of project pause is documented [here](https://docs.google.com/document/d/1tTqv4SupyHYbt14RH7UIRm1ZQbAHeg0SD7ydYlyVlfk/edit)
