### ISSUE TITLE
Add acq "red flags" documentation to USDA repo

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#70]
**Background**
As part of our sustainment planning to help ensure that FS knows what to look for when reviewing vendor proposals. 
 
**Acceptance criteria** 
- [x] Guidance on what to look for when reviewing vendor proposals is available to the team and findable in the wiki

**Tasks**
- [x] Review guidance from Miatta
- [x] Post to wiki
 
**Definition of done**
- [x]  Meets acceptance criteria

**Comment by Miatta18F** [comment]
Item complete and added to repo on 1/2/2020.

**Comment by MelissaBraxton** [comment]
[Link to considerations doc](https://github.com/USDAForestService/USFS-timber-permitting/blob/master/docs/Considerations%20when%20reviewing%20proposals.pdf)
