### ISSUE TITLE
Forest Service product folks sit in on another agile team's sprint ceremonies

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#73]
**Background**
As part of coaching FS in expanding their product management capabilities, we want to create opportunities for FS product folks to see how different agile teams organize their work.

**Acceptance criteria** 
- [x] At least two FS product folks have attended another agile product team's sprint review and sprint planning sessions. 

**Tasks**
- [x] Melissa reaches out to possible teams and finds a few possibilities
- [x] Melissa schedules FS attendance
- [x] FS folks attend ceremonies

**Definition of done**
- [x]  Meets acceptance criteria
