### ISSUE TITLE
18F documents user research heuristics in USDA repo

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#74]
**Background**
As part of supporting the FS and any vendors joining the team in conducting quality user research at regular intervals, we want to add a list of considerations for doing unbiased (to the extent possible), ethical user research in the project GitHub repo.

**Acceptance criteria** 
- [ ] Anyone on the team, including new vendors onboarding, can easily find and understand user research heuristics and resources for ensuring unbiased, ethical research in the project's GitHub repo. 

**Tasks**
- [ ] Create user research checklist 
- [ ] Curate a list of user research resources specific to the project
- [ ] Document checklist and additional resources on GitHub

**Definition of done**
- [ ]  Meets acceptance criteria
