### ISSUE TITLE
18F adds an accessibility checklist to USDA GitHub repo

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#75]
**Background**
As part of supporting the FS and any vendors joining the team in creating an experience that is accessible for all, we want to add a list of considerations for designing accessibility into every aspect of the system. 

**Acceptance criteria** 
- [ ] Anyone on the team, including new vendors onboarding, can easily find and understand accessibility criteria and resources for ensuring accessible software in the project's GitHub repo. 

**Tasks**
- [ ] Create accessibility checklist specific to the firewood permitting application and envisioned code pipeline
- [ ] Curate a list of accessibility resources specific to the project
- [ ] Document checklist and additional resources on GitHub

**Definition of done**
- [ ]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
Draw from or link to this: https://accessibility.18f.gov/

**Comment by cmajel** [comment]
Adding https://accessibility.digital.gov/ as another resource to help build this.

A few thoughts in my head on this topic:
* The [18F checklist](https://accessibility.18f.gov/checklist/) is an actionable, fast read for testing front end components. But, [accessibility.digital.gov](https://accessibility.digital.gov/) gives some good pointers for content and visual design that we may want to call out (like touch area sizes, plain language, etc)
* Are there specific tools that we can recommend to help run automated accessibility tests? For example, I've used the [Accessibility Insights for Web chrome extension](https://chrome.google.com/webstore/detail/accessibility-insights-fo/pbjjkligggfmakdaogkfomddhfmpjeni?hl=en), but I believe there are also scripts that could be run at the code level to catch things like missing alt tags.

**Comment by cmajel** [comment]
Placeholder wiki page here:
https://github.com/USDAForestService/USFS-timber-permitting/wiki/Accessibility-checklist

**Comment by cmajel** [comment]
I took a pass at this borrowing heavily from the 18F accessibility checklist:

https://github.com/USDAForestService/USFS-timber-permitting/wiki/Accessibility-checklist

I wonder if we need a section on automated accessibility tests vs manual. ccing @ctro who may have thoughts, and linking to a few resources below. Maybe all we need to say is "automated tests can help but also do manual testing" and link to resources, but I haven't written guidance on this before. 
* https://accessibility.18f.gov/tools/
* https://accessibility.digital.gov/front-end/automated-testing/
