### ISSUE TITLE
Prototype a self-print load tag

### ISSUE THREAD

**Issue by cmajel** [USDAForestService/USFS-timber-permitting#78]
**Background**
_What should we consider when addressing this issue?_

**Acceptance criteria** 
- [x] We have a draft tag that clearly communicates 
- Forest
- Current year
- Quantity
- Date harvested

**Tasks**
- [x] Sketch out tag
  - [x] [Mural sketch room ](https://app.mural.co/t/gsa6/m/gsa6/1576278051923/de110b46bfa9ef3ac6715ac7057f952d8b3ea65f)
  - [x] [Screen to demo to usability test participants](https://gsa.invisionapp.com/share/BRVB46ON5MU#/398234481_FS_MVP1--11-0--Printable-Load-Tag)
- [x] Share with team to review
 - [x] Discussed in slack and at 12/17 coworking. [Doc of initial FS reactions here.](https://docs.google.com/document/d/1vz6A0pETZShtSnbMCgWyILFdJZVkYlZb5caZFQ45gHE/edit?folder=1OlKHs8CMYMtryyLuij2pFpcm1fu1aqaD#)

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by cmajel** [comment]
Priority for light testing next week is the load tag.

**Comment by cmajel** [comment]
See LEO report for key information
https://docs.google.com/document/d/1bZmQOczExXEJYbe75os-mpe-xY93a6U6gZphzSjKkZU/edit#

Sounds like key info we want:
* Forest 
* Quantity 
* Date harvested

**Comment by MelissaBraxton** [comment]
A place to put ideas: https://app.mural.co/invitation/mural/gsa6/1576278051923?sender=melissabraxton2796&key=1cc8f367-7427-46b7-8e51-aa6e79207c0c

**Comment by justinbarber0302** [comment]
Apologies if Kris previously brought any of this up or if this is the wrong place to share this info, but our Load Tags for fuelwood permits on the Carson (as well as the ones the Santa Fe NF uses) also feature:

(a) a unique identifier (number). 
(b) printed on a heavy cardstock in a different, vibrant (usually neon) color for each Calendar Year.
(c)  time of removal in addition to date for validation.

These factors make the tags difficult to counterfeit.

1/2 cord tags entails that we distribute 10 per permit (5 cords for $20 on the Carson). In a given season, we distribute around 17,000 of them, so of the three factors I listed above, an identifier unique to each permit/permittee is the most essential. Region 3's limited contracts and vast fuelwood sales separate it from other regions, but these are factors that need to be considered if standardized self-print tags are eventually going to be available nationwide.

I'm not sure if Kris shared this example with the group (B&W because hot pink scans obnoxiously):

![Load Tag F](https://user-images.githubusercontent.com/58951262/70940059-c8dc6100-2006-11ea-83fe-37a79205e473.JPG)
![Load Tag R](https://user-images.githubusercontent.com/58951262/70940061-c8dc6100-2006-11ea-8a4f-db4e9371463c.JPG)

**Comment by MelissaBraxton** [comment]
Thanks @justinbarber0302! This is great and definitely an appropriate place to have this discussion. While the goal is to roll out a program nationwide, the assumptions we're making for an MVP are that we'd be piloting this in an area that:

- does not currently use load tags, 
- does not have many restricted areas for firewood collection (e.g., sales), 
- and has no (or a very high) seasonal limit for firewood.  

I added some clarification to the acceptance criteria. Right now we're prototyping a tag that makes key info for LEOs discernible from a distance when the load is tagged, based on what we heard they need to see before they make a stop. We aren't targeting the other info that needs to be on a tag and/or permit aside from that in this week's usability tests, but we will certainly need to nail that down (and how to prevent fraud in areas that limit quantities) in the coming weeks.
