### ISSUE TITLE
Recap field visit 2 in the project wiki

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#79]
**Background**
As a future team member, I want to be able to easily find what the team worked on so that I can access past research and don't waste time looking through slack/email.

**Acceptance criteria** 
- [x] We have a page on the wiki that recaps our first field trip and includes links to relevant documents.

**Tasks**
- [x] Determine what documents we should link to
- [x] Write a draft, and share with the team for feedback
- [x] Publish to the Wiki

**Definition of done**
- [x]  Meets definition of done

**Comment by cmajel** [comment]
I created a placeholder for this with the same headings as our last field trip recap:
https://github.com/USDAForestService/USFS-timber-permitting/wiki/Field-trip-2:-Observing-LEOs-in-the-field
