### ISSUE TITLE
Create initial prototype(s)/probes for field research

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#8]
**Background**
_What should we consider when addressing this issue?_

**Acceptance criteria** 
- [x] Test hypotheses informed by research to date
- [x] Can be accessed by participants without needing wifi
- [x] ~Clickable mocks are bug free~

**Tasks**
- [x] Articulate design hypotheses and research Qs
- [x] Create mocks 
- [x] ~Simulate interaction // make them clickable~

**Definition of done**
- [x] Meets acceptance criteria

**Comment by cmajel** [comment]
A few notes from planning:

First round of prototyping as research probes. Fidelity of the prototype may vary depending on the scope of the research questions.

**Comment by cmajel** [comment]
A few updates:
* [Design hypotheses exercise here](https://app.mural.co/t/gsa6/m/gsa6/1571679534245/30b77ddd87789da4c6300978b8cdd8ea6ad24dbf). 
* We have [a sketching session](https://app.mural.co/t/gsa6/m/gsa6/1571674517069/a0143a1bc7c4481453a6eacd5f8dc037523b7e56) later today for the top 3 hypotheses we have going into this first round

**Comment by cmajel** [comment]
Adding updates from last week's design conversations.

Based on our [current user task flow](https://app.mural.co/t/gsa6/m/gsa6/1571674517069/a0143a1bc7c4481453a6eacd5f8dc037523b7e56), we identified a few areas for prototyping where we could use early opinions:

* Find out what products might be available to me (mushroom, firewood, Christmas trees)
* Selecting how I want to receive my load tag(s), possibly combined with confirming permit purchase
* Alternative load tag formats for LEO feedback.

**Comment by cmajel** [comment]
Created a field trip scratch pad for mocks:
https://app.mural.co/t/gsa6/m/gsa6/1572366477072/7097e06ec067e2a82a40b4bdba178a82911c20e9
