### ISSUE TITLE
Onboard Justin

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#80]
**Background**

**Acceptance criteria** 
- [x] Forest Management has identified the person and confirmed that they'll be able to work with us (supervisor approval, MOU if needed)
- [x] FS product folks have the required background and access to tools that they need to begin working with the team

**Tasks**
- [x] Schedule 1:1 w/ Mel and Justin
- [x] Review PM/PO role descriptions
- [x] Review project documentation, path analysis report
- [x] Oriented to GitHub
- [x] Invited to Slack
- [x] Review any research reports to date
- [x] Add them to team calendar events/meetings

**Definition of done**
- [x]  Acceptance criteria met
