### ISSUE TITLE
Conduct comparative analysis of ID verification solutions

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#81]
**Background**
We are looking into whether Login.gov can meet the need for users to verify their identify to purchase firewood permits. 

**Acceptance criteria** 
- [x] We understand the tradeoffs of going with Login or another ID proofing solution

**Tasks**
- [x] Identify criteria for choosing a solution
- [x] Gather info from Login.gov
- [x] Spend <2 hours researching other ID proofing options
- [x] Share results with team

**Definition of done**
- [ ]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
https://docs.google.com/spreadsheets/d/1PcHE83oxaQkCO_pSmyiUkiILsUsF_vJrGrl_MUksuug/edit#gid=0

Sheet started here ^
