### ISSUE TITLE
Draft new SOW for next phase

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#82]
**Background**
The Path Analysis SOW that we've been working under doesn't cover the type of work we anticipate in the next phase. 

**Acceptance criteria** 
- [ ] We have an SOW we can begin routing that is inclusive of acquisition work and post-award management activities. 

**Tasks**
- [x] Draft SOW (Melissa)
- [x] Olesya reviews and shares w/ USFS patrners for feedback 

**Definition of done**
- [ ]  PM approval
- [ ] Sponsor approval
