### ISSUE TITLE
Determine level of effort needed to connect with Reporting Systems

### ISSUE THREAD

**Issue by ctro** [USDAForestService/USFS-timber-permitting#83]
**Background**
CDW And EDW are the "Reporting"  components. (See this doc https://docs.google.com/drawings/d/1J37DjKdiM7-zDESnxV8SQNeCIaUmu0BaQjp6DvawRC8/edit)

Fuelwood Permitting work will start with Financial components, but Reporting components will eventually need to be handled.

**Acceptance criteria** 
- [ ] We have clearly articulated considerations for a vendor team in establishing integrations to CDW and EDW
- [ ] We've clearly articulated a decision on what (if any) data beyond what will pass from Open Forest to TIM via FPFS needs to be available to meet reporting needs

**Tasks**
- [ ] Research and document with examples the data that moves from Staging Tables to CDW, EDW
- [ ] Determine minimum data that will meet upward reporting needs for the MVP (Beth)
- [ ] Research and document the methods by which data moves from Staging Tables to CDW EDW
- [ ] Imagine OpenForest putting data in CDW/EDW. Ensure that downstream applications will be unaffected (e.g. GPAS, Tableau) as long as the data that ends up in CDW/EDW is the same.
- [ ] Email Markus to ask about access to CDW Test and EDW Development environments.
- [ ] Follow up with contacts from Beth about scheduling a call/demo with someone who is building services off of EDW

**Definition of done**
- [ ]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
Add review of as-is and proposed architecture to KO agenda - Check with Shadat and Matt Reiss about current status and whether any progress has been made -

**Comment by mgwalker** [comment]
We can fill in more detail later, but (if I understood correctly) we're going to proceed with the assumption that Open Forest will integrate directly with TIM to satisfy reporting needs. That influences the level of effort question, so I wanted to document it here.

**Comment by MelissaBraxton** [comment]
@mgwalker and @bboddiger  - Are there any new updates here? I think some of these tasks could be checked off, and we may also be able to move this to the icebox.

**Comment by mgwalker** [comment]
I think this can be closed because we're going to lean on TIM to handle reporting to CDW/EDW.
