### ISSUE TITLE
Determine level of effort needed to connect with FPFS API

### ISSUE THREAD

**Issue by ctro** [USDAForestService/USFS-timber-permitting#86]
**Background**
The first integration that OpenForest will take from TIM is with financial systems. Dig into the initial connection. Per our proposed architecture, we are currently planning to move data to FMMI from FPFS, and Open Forest will connect FPFS via a new REST API. 

**Acceptance criteria** 
- [ ] We have clearly articulated considerations for a vendor team in establishing an FPFS integration 

**Tasks**
- [x] Meet with FPFS team and cover
    - Introductions, explain what we're trying to do
    - Ask bout details for setting up a new client for the SOAP API, what's the process like? 
    - We'd like to try to replicate "Monthly" and "Hourly" processes that occur between TIM and FPFS
    - Confirm there is a staging environment and ask for access
- [x] @MelissaBraxton schedules time for 18F / Open Forest / FPFS to meet
- [x] Reconnect with FPFS team to learn current status of FPFS/Open Forest API (nicholas.ault@usda.gov and percy.lazarous@usda.gov)
- [x] Learn about where/how FPFS stores reports and any issues around SORN that they went through
- [ ] Get access to FPFS staging environment
- [ ] Successful manual API Requests to FPFS Staging, with documentation
- [ ] Determine whether we need to mimic "monthly" and "hourly" processes over the SOAP API

**Definition of done**
- [ ]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
Refined this a bit, @ctro

**Comment by ctro** [comment]
Meeting set for January 7 to discuss this, moving to "Blocked" for this sprint.

**Comment by MelissaBraxton** [comment]
Mel to review this issue in drafting KO agenda and include prompts for Qs re: these tasks.

**Comment by MelissaBraxton** [comment]
@smahmudFS adding you here, since I know you've been looking into it already. Please feel free to suggest additions/changes to the tasks we've listed and/or add comments on what you've learned most recently.

**Comment by mwreiss** [comment]
@MelissaBraxton there will be a firewall request (or two) that will be required to let this connectivity allowed in/out of the usda network.  We have a good handle on what that looks like, we can setup a card to address.  

Need to identify the destination address in FPFS.  Do we have the system name, IP, etc?

**Comment by MelissaBraxton** [comment]
@mwreiss - We'll need to reconnect with Nick and Percy at FPFS for that info. @mgwalker is going to try and find some time for y'all to chat.

**Comment by mgwalker** [comment]
Going to pause on connecting with Nick and Percy for now, but presumably we'll be back to that before too long.

**Comment by MelissaBraxton** [comment]
I'll take on scheduling time with Percy and the team for the week after next when Greg is back in the office.

**Comment by MelissaBraxton** [comment]
Mtg w/ FPFS folks scheduled for 7/1.

**Comment by MelissaBraxton** [comment]
@smahmudFS and @mwreiss - Here is the model schema for the test service Nick Ault worked on for us back in Dec.

**Model schema for sending firewood permit data to FPFS**
```

Model Schema:
{
 "regionCode": "string",
 "forestCode": "string",
 "districtCode": "string",
 "permitNumber": "string",
 "proclaimedUnitCode": "string",
 "availableDate": "string",
 "sizeClassCode": "string",
 "stateCode": "string",
 "countyCode": "string",
 "spuVolumeRates": [
   {
     "speciesCode": "string",
     "productCode": "string",
     "uomCode": "string",
     "ccfConversionFactor": 0,
     "mbfConversionFactor": 0,
     "soldQuantity": 0,
     "stumpageSoldValue": 0
   }
 ],
 "distributions": [
   {
     "budgetOrg": "string",
     "jobCode": "string",
     "procUnit": "string",
     "distAmount": 0
   }
 ],
 "associatedCharges": [
   {
     "budgetOrg": "string",
     "jobCode": "string",
     "procUnit": "string",
     "distAmount": 0
   }
 ]
}
Sample Permit (number exists, this permit is expected to fail):
{
 "regionCode": "04",
 "forestCode": "01",
 "districtCode": "02",
 "permitNumber": "013479",
 "proclaimedUnitCode": "0496",
 "availableDate": "08/15/2018",
 "sizeClassCode": "3",
 "stateCode": "49",
 "countyCode": "47",
 "spuVolumeRates": [
   {
     "speciesCode": "D",
     "productCode": "07",
     "uomCode": "02",
     "ccfConversionFactor": 0.8500,
     "mbfConversionFactor": 0.5000,
     "soldQuantity": 4.00,
     "stumpageSoldValue": 20.00
   }
 ],
 "distributions": [
   {
     "budgetOrg": "0401",

```

**Comment by MelissaBraxton** [comment]
@smahmudFS and @mwreiss - Is this one covered [by #264](https://code.fs.usda.gov/forest-service/Open-Forest-Program/issues/264) on the program board?

If we can, let's consolidate the last 3 tasks here into the program board issue and then close this issue.

**Comment by mwreiss** [comment]
@MelissaBraxton Yes, we have the first 2 covered in #264, I will add the third so this issue can be closed out.
