### ISSUE TITLE
Schedule sprint ceremonies and milestone mtgs

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#9]
**Background**

**Acceptance criteria** 
- [x] People's vacation days are accounted for
- [x] Holidays are accounted for

**Tasks**
- [x] Discuss mtg cadence w/ team
~- [ ] Create team calendar~
- [x] Add meetings to calendar

**Definition of done**
- [x]  All sprint ceremonies and milestone mtgs are on the team calendar
