### ISSUE TITLE
Establish sprint schedule

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#97]
**Background**
We need to coordinate with the vendor team and USFS partners to establish a sprint schedule that works for all. 

**Acceptance criteria** 
- [x] We have a schedule of recurring sprint ceremonies that work for everyone. 

**Tasks**
- [x] Check Max.gov to suss out Open Forest team schedules
- [x] Coordinate with Eric Carlson (scrum master) to add to or adjust meeting invitations
- [x] Decide on sprintly cadence for 18F team 
- [x] Decide on video conferencing tool for meetings 

**Definition of done**
- [x]  Meets acceptance criteria
