### ISSUE TITLE
Onboard Greg

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#98]
**Background**
Greg will be joining the team as the new engineering lead

**Acceptance criteria**
- [x] Greg has necessary background and access to tools to feel confident beginning to work with the team.

**Tasks**
- [x] Greg reviews relevant project material:
    - [x] Internal KO doc
    - [x] Peruse Open Forest repos
    - [x] Peruse timber permitting repo
    - [x] Timber permitting Path Analysis report
    - [x] Technical path forward doc
    - [x] "Where things stand" doc
- [x] Greg and Melissa have initial onboarding 1:1
- [x] Greg added to GitHub team
- [x] Greg and Mel initiate the process of Greg getting USDA credential
- [X] Greg added to Slack channel

**Definition of done**

- [ ]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
Still working on getting USFS credential but it's in progress.
